/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var h=!0,k=!1,n=n||{},p=this;function r(d){d=d.split(".");var g=p;!(d[0]in g)&&g.execScript&&g.execScript("var "+d[0]);for(var b;d.length&&(b=d.shift());)g=g[b]?g[b]:g[b]={}};"undefined"!==typeof n&&r("PENGO.shared.rpc.endpoint");
(function(){function d(){this.functions={};this.notifications={};this.scopes={};this.defaultScope=this;var c=this;this.exposeRequests=function(a,b){for(var e in b)if(!c.exposeRequest(a,e,b[e].callback,b[e].context))return k;return h};this.exposeRequest=function(a,b,e,f){return c.add(c.functions,c.scopes,a,b,e,f)};this.unExposeRequests=function(a,b){for(var e in b)if(!c.unExposeRequest(a,e))return k;return h};this.unExposeRequest=function(a,b){return c.remove(c.functions,c.scopes,a,b)};this.exposeNotifications=
function(a,b){for(var e in b)if(!c.exposeNotification(a,e,b[e].callback,b[e].context))return k;return h};this.exposeNotification=function(a,b,e,f){return c.add(c.notifications,c.scopes,a,b,e,f)};this.unExposeNotifications=function(a,b){for(var e in b)if(!c.unExposeNotification(a,e,b[e].callback,b[e].context))return k;return h};this.unExposeNotification=function(a,b,e,f){return c.remove(c.notifications,c.scopes,a,b,e,f)};this.handleRequest=function(a,b,e,f){c.handleCall(c.functions,c.scopes,c.defaultScope,
a,b,e,f)};this.handleNotification=function(a,b,e){c.handleCall(c.notifications,c.scopes,c.defaultScope,a,b,e,void 0)};this.add=function(a,b,c,f,d,m){if("function"===typeof d)return a[c+"."+f]||(a[c+"."+f]=[]),a[c+"."+f].push({d:d,a:m}),h;throw new g("Expected to receive a 'function' as callback in "+c+"."+f+" and is "+typeof d);};this.remove=function(a,c,b,f,d,g){try{a[b+"."+f].splice(a[b+"."+f].indexOf({d:d,a:g}),1),!a[b+"."+f].length&&delete a[b+"."+f]}catch(l){return k}return h};this.handleCall=
function(a,c,e,f,d,m,l){if(!a.hasOwnProperty(f))throw new g("Unknown RPC call '"+f+".",b.p);var q;a[f].forEach(function(a){try{q=a.a||e,a.d&&a.d.call(q,d,m,l)}catch(b){throw new g(b);}})}}var g,b;d.prototype={message:{ID:0,METHOD:1,PARAMS:2,JSONRPC:3,RESULT:4,ERROR:5},error:{CODE:0,MESSAGE:1,DATA:2},VERSION:"2.0",j:{CODIFY:1,FIELD:"rpc.codify"}};"undefined"!==typeof exports?(g=require("pengo.liberror/pengoError"),b=require("pengo.liberror/codes").q,module.i=d):window.PENGO.shared.rpc.endpoint.resolve=
function(){return{dependencies:function(c){g=c.pengoError.pengoError.PengoError;b=c.pengoError.codes.codes},implementation:{Endpoint:d}}};"undefined"!==typeof n&&(d.prototype.exposeNotifications=d.prototype.r,d.prototype.unExposeNotifications=d.prototype.t,d.prototype.handleNotification=d.prototype.s,d.prototype.message=d.prototype.message,d.prototype.error=d.prototype.error,d.prototype.flags=d.prototype.j,d.prototype.VERSION=d.prototype.VERSION)})();"undefined"!==typeof n&&r("PENGO.shared.rpc.schema");
(function(){function d(){var b=this;this.m=function(c,a,d){var e=void 0;a.hasOwnProperty("error")||(a.error={});a.error.hasOwnProperty("code")||(a.error.code=-1);try{d.hasOwnProperty(c)&&(e=d[c])}catch(f){if(a.required)throw new g("Required param '"+c+"' not found.",a.error.code,a.error.a);}if(a.hasOwnProperty("required")){if(a.required&&void 0===e)throw new g("Param "+c+" required not found.",a.error.code,a.error.a);if(!a.required&&void 0===e)return}if(a.hasOwnProperty("validateFunction")&&!b.c(c,
a,d))throw new g("Validate function for "+c+" with value "+e+" return not valid.",a.error.code,a.error.a);if(a.hasOwnProperty("type")&&!b.n(e,a))throw new g("Type of "+c+" with value "+e+" Expected: "+a.type+" and is "+Object.prototype.toString.call(e).toLowerCase()+".",a.error.code,a.error.a);if((a.hasOwnProperty("min")||a.hasOwnProperty("max"))&&!b.k(e,a))throw new g("Range of "+c+" with value "+e+" expected to be between "+a.min+" and "+a.max+".",a.error.code,a.error.a);if(a.hasOwnProperty("regexp")&&
!b.l(e,a))throw new g("RegExp of "+c+" with value "+e+" match "+a.e+" as invalid.",a.error.code,a.error.a);};this.o=function a(d,e,f,g){var m=d.split("."),l=m.shift();if(0===m.length||"undefined"===typeof f||"undefined"===typeof f[l])0!==m.length&&(l=d),g.g&&b.f(f,e.code,l),g.b&&b.m(l,e,f),g.h&&b.f(f,l,e.code);else return Array.isArray(f[l])?f[l].every(function(b){return a(m.join("."),e,b,g)===h}):a(m.join("."),e,f[l],g)}}var g;d.prototype={b:function(b,c,a,d){if(!b||0===Object.keys(b).length||!a||
0===Object.keys(a).length)return b;var e=this;d||(d={});var f={};f.b=d.validate||k;f.h=c&&c.encode;f.g=c&&c.decode;if(!f.b&&!f.h&&!f.g)return b;Object.keys(a).forEach(function(c){e.o(c,a[c],b,f)});return b},c:function(b,c,a){if("object"==typeof c.c)return h;if("function"==typeof c.c)c=c.c;else return k;try{if(!c(a[b]))return k}catch(d){return k}return h},n:function(b,c){function a(a){return d==="[object "+a+"]"}var d=Object.prototype.toString.call(b).toLowerCase();if(Array.isArray(c.type)){if(!c.type.some(a))return k}else if(!a(c.type))return k;
return("date"==c.type||~c.type.indexOf("date"))&&isNaN(b)?k:h},k:function(b,c){if(void 0===b||null===b)return k;var a={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase();if(b)switch(a){case "string":case "array":if(Object.prototype.hasOwnProperty.call(c,"min")&&b.length<c.min||Object.prototype.hasOwnProperty.call(c,"max")&&b.length>c.max)return k;break;case "number":if(Object.prototype.hasOwnProperty.call(c,"min")&&b<c.min||Object.prototype.hasOwnProperty.call(c,"max")&&b>c.max)return k;break;
default:return k}return h},l:function(b,c){function a(a){return a.test(b)}if(Array.isArray(c.e)){if(!c.e.every(a))return k}else if(!a(c.e))return k;return h},f:function(b,c,a){"undefined"!==typeof a&&b.hasOwnProperty(c)&&(b[a]=b[c],delete b[c]);return b}};"undefined"!==typeof exports?(g=require("pengo.liberror/pengoError"),require("pengo.liberror/codes"),module.i=d):window.PENGO.shared.rpc.schema.resolve=function(){return{dependencies:function(b){g=b.pengoError.pengoError.PengoError},implementation:{Schema:d}}};
"undefined"!==typeof n&&(d.prototype.validate=d.prototype.b)})();})();
