/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){function h(a){throw a;}var l=void 0,r=r||{},t=this;function v(a){a=a.split(".");var c=t;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)c=c[g]?c[g]:c[g]={}}Math.random();"undefined"!==typeof r&&v("PENGO.shared.net.recipient");
(function(){function a(){this.addLocalRecipient=function(b,a,e,q){c(b);(!e||"function"!==typeof e)&&h(new d(e+" is not a valid msgbox handle, it must be a 'function' Object",k.h));g(q);var n=!1;f[q]||(f[q]=[],n=!0);for(var p=0;p<f[q].length;p++)f[q][p]===e&&h(new d("Msg recipient '"+b+"' is already registered",k.l));m[b]=q;s[b]=a;f[q].push(e);return n};this.removeLocalRecipient=function(b,a){c(b);var e=!1;if(f[m[b]])if(a)for(var d=0;d<f[m[b]].length;d++)f[m[b]][d]===a&&(f[m[b]].splice(d,1),f[m[b]]&&
(e=!0));else delete f[m[b]],e=!0;e&&delete f[m[b]];m[b]&&delete m[b];s[b]&&delete s[b];return e};this.getLocalRecipientList=function(){return m};this.getLocalRecipientProtocolsList=function(){return s};this.getLocalRecipient=function(b){c(b);return m[b]};this.getLocalRecipientProtocol=function(b){c(b);return s[b]};this.addRemoteRecipient=function(b,a,f,q){c(b);g(f);n[b]&&h(new d("MsgBoxRecipient '"+b+"' is already registered",k.l));n[b]=f;p[b]=a;q||("undefined"!==typeof exports?process.r(function(){e.e("REMOTE_SERVICE_AVAILABLE",
b);e.e("MSG_REGISTERED",b)}):_.defer(function(){e.e("REMOTE_SERVICE_AVAILABLE",b);e.e("MSG_REGISTERED",b)}))};this.removeRemoteRecipient=function(b,a){c(b);n[b]||h(new d("MsgBoxRecipient '"+b+"' is not registered",k.v));delete n[b];delete p[b];a||("undefined"!==typeof exports?process.r(function(){e.e("REMOTE_SERVICE_UNAVAILABLE",b);e.e("MSG_UNREGISTERED",b)}):_.defer(function(){e.e("REMOTE_SERVICE_UNAVAILABLE",b);e.e("MSG_UNREGISTERED",b)}))};this.getRemoteRecipient=function(b){c(b);return n[b]};
this.getRemoteRecipientProtocol=function(b){c(b);return p[b]};this.getRemoteRecipientProtocolConstants=function(b){c(b);return p[b]&&p[b].constants};this.getRemoteRecipientList=function(){return n};this.getRemoteRecipientProtocols=function(){return p};this.isRemoteRecipientAvailable=function(b){c(b);return n[b]?!0:!1};this.dispatch=function(b,a){g(b);if(f[b])for(var e=f[b].length,d=0;d<e;d++)f[b][d].apply(this,a),u++;return u};"undefined"!==typeof r&&(a.prototype.addLocalRecipient=this.w,a.prototype.removeLocalRecipient=
this.H,a.prototype.isRemoteRecipientAvailable=this.F,a.prototype.getRemoteRecipient=this.D,a.prototype.getLocalRecipient=this.B,a.prototype.getLocalRecipientList=this.C)}function c(b){(!b||"string"!==typeof b)&&h(new d(b+" is not a valid msgbox, it must be an 'string' Object and is "+typeof b,k.h))}function g(b){(!b||0===b)&&h(new d(b+" is not a valid id, it must be other than 0 ",k.h))}var d=l,k=l,e=l,u=0,m={},s={},f={},n={},p={};a.prototype={f:{MSG_REGISTERED:"msg_recipient_registered",MSG_UNREGISTERED:"msg_recipient_unregistered",
REMOTE_SERVICE_AVAILABLE:"remote_service_available",REMOTE_SERVICE_UNAVAILABLE:"remote_service_unavailable"},q:{id:1,server:"msgServer",client:"msgClient"},protocol:{getAvailableRemoteRecipient:1,addRemoteRecipient:2,removeRemoteRecipient:3,error:4},on:function(b,c){(!b||"string"!==typeof b||!a.prototype.f[b])&&h(new d("Invalid topic "+b+" or not allowed "+Object.keys(a.prototype.f),k.d));(!c||"function"!==typeof c)&&h(new d("Invalid function "+c+" associated to topic "+b,k.d));e.on(b,c)},off:function(b,
c){(!b||!a.prototype.f[b])&&h(new d("Invalid topic "+b+" or not allowed "+Object.keys(a.prototype.f),k.d));(!c||"function"!==typeof c)&&h(new d("Invalid function "+c+" associated to topic "+b,k.d));e.off(b,c)}};"undefined"!==typeof exports?(e=new (require("events").EventEmitter),e.off=e.removeListener,d=require("pengo.liberror/pengoError"),k=require("pengo.liberror/codes").m,module.k=a):window.PENGO.shared.net.recipient.resolve=function(){e=_.clone(Backbone.Events);e.e=e.trigger;return{dependencies:function(b){d=
b.pengoError.pengoError.PengoError;k=b.pengoError.codes.codes},implementation:{Recipient:a}}};"undefined"!==typeof r&&(a.prototype.addRemoteRecipient=a.prototype.z,a.prototype.removeRemoteRecipient=a.prototype.I,a.prototype.dispatch=a.prototype.A,a.prototype.on=a.prototype.on,a.prototype.off=a.prototype.off,a.prototype.msg=a.prototype.q,a.prototype.protocol=a.prototype.protocol)})();"undefined"!==typeof r&&v("PENGO.shared.net.constants");
(function(){var a={dependencies:l,implementation:{messageChunks:{RESULT:0,COMMAND:1,DATA:2},results:{KO:3E3,OK:3001,CLOSE_NORMAL:1E3},commands:{VERIFY:0},commandDataChunks:{verify:{sessionID:0,userID:1,anonymous:2}},error:{codes:{UNEXPECTED_ERROR:3100,SESSION_NOT_VALID:3101,STOPPING_SERVER:3102,DUPLICATE_USER_SESSION:3103},texts:{en:{3101:"Session provided is invalid or expired."},es:{3101:"La sesi\u00f3n actual no es v\u00e1lida o ha caducado."}}}}};"undefined"!==typeof exports?module.k=a.implementation:
window.PENGO.shared.net.constants.resolve=function(){return a}})();"undefined"!==typeof r&&v("PENGO.shared.net.msg");
(function(){function a(){this.a={};this.a.headers=l;this.a.data=l;this.c=[];this.b=l}var c=l,g=l,d=l,k=["GUID","RECIPIENT","TYPE"];a.prototype={headers:{GUID:1,TYPE:2,RECIPIENT:3},types:{REQUEST:1,RESPONSE:2,ERROR:3,NOTIFY:4,CONTROL:5},n:function(){this.c=[];this.b=l;this.a.headers=l;this.a.data=l},getHeader:function(a){-1===k.indexOf(a)&&h(new c("Invalid type of header "+a+" getting the header of msg",g.d));return this.c[this.headers[a]]},u:function(a,d){-1===k.indexOf(a)&&h(new c("Invalid type of header "+
a+" getting the header of msg",g.d));if(!d)return!1;this.c[this.headers[a]]=d;return!0},setData:function(a){this.b=a},t:function(a){this.g=a},s:function(){(!this.b||!this.c)&&h(new c("Serializing msg invalid data "+this.b+" or headers "+this.c,g.d));this.a.data=this.b;this.a.headers=this.c;this.g=d.j(this.a)},o:function(){(this.a=d.i(this.g))||h(new c("Deserializing invalid data "+this.b+" or headers "+this.c,g.d));this.c=this.a.headers;this.b=this.a.data;(!this.b||!this.c)&&h(new c("Deserializing invalid data "+
this.b+" or headers "+this.c,g.d))},getData:function(){return this.b},p:function(){return this.g}};"undefined"!==typeof exports?(d=require("msgpack"),c=require("pengo.liberror/pengoError"),g=require("pengo.liberror/codes").m,d.j=d.G,d.i=d.J,module.k=a):window.PENGO.shared.net.msg.resolve=function(){d={};d.j=msgpack.encode;d.i=msgpack.decode;return{dependencies:function(a){c=a.pengoError.pengoError.PengoError;g=a.pengoError.codes.codes},implementation:{Msg:a}}};"undefined"!==typeof r&&(a.prototype.createMsg=
a.prototype.n,a.prototype.serialize=a.prototype.s,a.prototype.deSerialize=a.prototype.o,a.prototype.setHeader=a.prototype.u,a.prototype.getHeader=a.prototype.getHeader,a.prototype.setData=a.prototype.setData,a.prototype.getData=a.prototype.getData,a.prototype.setBuffer=a.prototype.t,a.prototype.getBuffer=a.prototype.p,a.prototype.headers=a.prototype.headers,a.prototype.types=a.prototype.types)})();})();
