/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var m=m||{},q=this;function r(d){d=d.split(".");var g=q;!(d[0]in g)&&g.execScript&&g.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)g=g[f]?g[f]:g[f]={}}Math.random();"undefined"!==typeof m&&r("PENGO.shared.servicesManager.servicesManager");
(function(){function d(b){if(!b||"string"!==typeof b)throw new c(b+" is not a valid 'id'",l.INVALID_TYPE);}function g(b,e,a,k){if(!b||"object"!==typeof b)throw new c("Service '"+a+"' of plugin '"+k+"' is not a valid service, it must be an Object",l.INVALID_TYPE);if(!b.functions||"object"!==typeof b.functions)throw new c("Service '"+a+"' of plugin '"+k+"' is not a valid service, it must contain a 'functions' Object",l.INVALID_TYPE);if(e)for(var h in b.functions)if("function"!==typeof b.functions[h])throw new c("Service '"+
a+"' of plugin '"+k+"' can only contain functions and '"+h+"' is not a function",l.INVALID_DATA);}function f(){var b,e={};"undefined"!==typeof exports?(b=new (require("events").f),b.h(50)):b=_.clone(Backbone.Events);this.register=function(a,k,h){d(a);g(k,!0,a,h);d(h);if(e[a])for(var n=0;n<e[a].length;n++){if(e[a][n]===k)throw new c("Service '"+a+"' is already registered",l.ALREADY_SET);}else e[a]=[];Object.freeze&&(Object.isFrozen(k.functions)||Object.freeze(k.functions));e[a].push(k);"undefined"!==
typeof exports?process.d(function(){b.b("SERVICE_REGISTERED",a,h)}):_.defer(function(){b.trigger("SERVICE_REGISTERED",a,h)})};this.unregister=function(a,k,h){d(a);g(k,!1,a,h);d(h);if(e[a])for(var c=0;c<e[a].length;c++)if(e[a][c]===k){e[a].splice(c,1);"undefined"!==typeof exports?process.d(function(){b.b("SERVICE_UNREGISTERED",a,h)}):_.defer(function(){b.trigger("SERVICE_UNREGISTERED",a,h)});break}};this.getService=function(a,b){var c=[],d,g,f;if(e[a])for(d=0;d<e[a].length;d++){f=!1;if(b)for(g in b)if(!e[a][d].e||
e[a][d].e[g]!==b[g]){f=!0;break}if(!f)if(Object.isFrozen(e[a][d].functions))c.push(e[a][d].functions);else{f=e[a][d];var l={},p=void 0;for(p in f.functions)l[p]=f.functions[p];c.push(l)}}return c};this.on=function(a,c){b.on(a,c)};this.off=function(a,c){"undefined"!==typeof exports?b.removeListener(a,c):b.off(a,c)}}var c,l;f.prototype={events:{SERVICE_REGISTERED:"service/registered",SERVICE_UNREGISTERED:"service/unregistered",SERVICE_UPDATED:"service/updated"}};"undefined"!==typeof exports?(c=require("pengo.liberror/pengoError"),
l=require("pengo.liberror/codes").a,module.c=f):window.PENGO.shared.servicesManager.servicesManager.resolve=function(){return{dependencies:function(b){c=b.pengoError.pengoError.PengoError;l=b.pengoError.codes.codes},implementation:{ServicesManager:f}}}})();"undefined"!==typeof m&&r("PENGO.shared.servicesManager.pluginServicesManager");
(function(){function d(c,d,b){function e(a){if(b.provides)for(var c in b.provides)if(b.provides[c]===a)return!0;return!1}this.register=function(a,b){if(!e(a))throw new g("Service with id '"+a+"' cannot be registered because is not provided by '"+c+"' plugin",f.INVALID_CONFIG);d.register(a,b,c)};this.unregister=function(a,b){if(!e(a))throw new g("Service with id '"+a+"' cannot be unregistered because is not provided by '"+c+"' plugin",f.INVALID_CONFIG);d.unregister(a,b,c)};this.getService=function(a,
k){var h;a:{if(b.consumes)for(h in b.consumes)if(b.consumes[h]===a){h=!0;break a}h=!1}if(!h&&!e(a))throw new g("Service with id '"+a+"' cannot be got because is not consumed by '"+c+"' plugin",f.INVALID_CONFIG);return d.getService(a,k)};this.getPluginId=function(){return c};this.on=d.on;this.off=d.off}var g,f;"undefined"!==typeof exports?(g=require("pengo.liberror/pengoError"),f=require("pengo.liberror/codes").a,d.prototype={events:require("./servicesManager.js").prototype.g},module.c=d):window.PENGO.shared.servicesManager.pluginServicesManager.resolve=
function(){return{dependencies:function(c){g=c.pengoError.pengoError.PengoError;f=c.pengoError.codes.codes;d.prototype={events:c.servicesMgr.servicesManager.ServicesManager.prototype.events}},implementation:{PluginServicesManager:d}}}})();})();
