/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var k=void 0,p=!0,x=null,y=!1,z=this;function A(a){a=a.split(".");var m=z;!(a[0]in m)&&m.execScript&&m.execScript("var "+a[0]);for(var q;a.length&&(q=a.shift());)m=m[q]?m[q]:m[q]={}};A("PENGO.client.plugins.resManager.model");
window.PENGO.client.plugins.resManager.model.resolve=function(a,m){function q(b){var a=this;this.g=b.resTypes;this.C=b.resStates;this.mimeTypes=b.resMime;Object.freeze&&!Object.isFrozen(this.g)&&Object.freeze(this.g);this.w=function(){return a.g};this.u=function(){return a.C};this.j=function(b){a.i(b);return b>=a.g.VIEW};this.v=function(b){if(!(b===k||b===x||"string"!==typeof b))for(var e in a.mimeTypes)if(b.match(a.mimeTypes[e]))return parseInt(e);throw new h(m.errors.a,"mdl:rmtype#1",[b]);}}var h=
a.pengoError.pengoError.StoredPengoError;q.prototype={i:function(b){var a;Array.isArray(b)||(b=[b]);for(var r in b){a=y;for(var e in this.g)if(this.g[e]==b[r]){a=p;break}if(!a)throw new h(m.errors.a,"mdl:rtype#1",[b[r]]);}},l:function(b){Array.isArray(b)||(b=[b]);for(var a in b)if(b[a]===k||b[a]===x)throw new h(m.errors.a,"mdl:rid#1",[b[a]]);},p:function(b){Array.isArray(b)||(b=[b]);for(var a in b)if(b[a]===k||b[a]===x)throw new h(m.errors.a,"mdl:rname#1",[b[a]]);},o:function(b){Array.isArray(a)||
(b=[b]);for(var a in b)if(b[a]===k||b[a]===x)throw new h(m.errors.a,"mdl:folder#1",[b[a]]);}};return q};A("PENGO.client.plugins.resManager.errors");
window.PENGO.client.plugins.resManager.errors.resolve=function(a){return{a:k,t:{"mod:conf#1":{msg:y,code:a.pengoError.codes.codes.NOT_FOUND},"mod:conf#2":{msg:y,code:a.pengoError.codes.codes.NOT_FOUND},"mod:conf#3":{msg:y,code:a.pengoError.codes.codes.INVALID_TYPE},"mdl:rtype#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"mdl:rid#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"mdl:rname#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"mdl:folder#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},
"mdl:rmtype#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rcre#1":{msg:y,code:a.pengoError.codes.codes.ALREADY_SET},"ct:rcre#2":{msg:y,code:a.pengoError.codes.codes.UNEXPECTED},"ct:rcre#3":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rupd#1":{msg:y,code:a.pengoError.codes.codes.NOT_FOUND},"ct:rupd#2":{msg:y,code:a.pengoError.codes.codes.INVALID_TYPE},"ct:rupd#3":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rupd#4":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},
"ct:rupd#5":{msg:y,code:a.pengoError.codes.codes.UNEXPECTED},"ct:rupd#6":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rget#1":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rget#2":{msg:y,code:a.pengoError.codes.codes.UNEXPECTED},"ct:rget#3":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rget#4":{msg:y,code:a.pengoError.codes.codes.NOT_FOUND},"ct:rdel#1":{msg:y,code:a.pengoError.codes.codes.UNEXPECTED},"ct:rdel#2":{msg:y,code:a.pengoError.codes.codes.INVALID_DATA},"ct:drcpd#1":{msg:y,
code:a.pengoError.codes.codes.INVALID_DATA},"ct:drcp#2":{msg:y,code:a.pengoError.codes.codes.UNEXPECTED}}}};A("PENGO.client.plugins.resManager.controller");
window.PENGO.client.plugins.resManager.controller.resolve=function(a,m){var q=a.util.object,h=a.util.callback,b=a.pengoError.pengoError.StoredPengoError;return function(t,r,e){function c(g,v,d,l,f){!d.file||!(d.file instanceof File)?h.call(l,f,new b(m.errors.a,"ct:rupd#2",[d.file])):d.file.size>r.maxResSize?h.call(l,f,new b(m.errors.a,"ct:rupd#3",[d.file.name,d.file.size])):e.call(r.remoteService,"updateSData",{selector:{id:g,type:v},fields:{size:d.file.size,mime:d.file.type}},k,function(v,e){v?h.call(l,
f,v):e.result===w.OK?(d.callbacks||(d.callbacks={}),d.callbacks.onerror=d.callbacks.onabort=function(g){l.call(f||this,g)},d.callbacks.onloaded=function(){l.call(f||this,k,e.id)},a.require.staticOps.uploadFile(d.file,r.staticResURLWithToken.replace("#id",g).replace("#v","x").replace("#token",e.fields.data),d.callbacks,d.context)):e.result===w.FILE_TOO_BIG?h.call(l,f,new b(m.errors.a,"ct:rupd#3",[d.file.name,d.file.size])):e.result===w.OVER_QUOTA?h.call(l,f,new b(m.errors.a,"ct:rupd#4",[d.file.name,
d.file.size])):h.call(l,f,new b(m.errors.a,"ct:rupd#5",[d.file.name,e.result]))},this)}function u(g,a,d,l,f){e.call(r.remoteService,"updateDData",{selector:{id:g,type:a},fields:{data:d}},k,function(a,d){a?h.call(l,f,a):d.result===w.OK?h.call(l,f,k,d.id):h.call(l,f,new b(m.errors.a,"ct:rupd#5",[g,d.result]))},this)}var w=e.getServiceProtocolConstants(r.remoteService).results,n=e.getServiceProtocolConstants(r.remoteService).resExt;e.getServiceProtocolConstants(r.remoteService);return{r:function(g,a,
d,l,f,s){var c;try{t.i(g),t.p(a),t.o(d)}catch(u){h.call(f,s,u);return}c={name:a,type:g,path:d};if(t.j(g)){if(l)if(q.isObject(l))c.data=l;else{h.call(f,s,new b(m.errors.a,"ct:rcre#3",[l]));return}a+=n[g]}e.call(r.remoteService,"create",c,k,function(g,l){g?h.call(f,s,g):l.result===w.OK?h.call(f,s,k,l.id):l.result===w.ALREADY_CREATED?h.call(f,s,new b(m.errors.a,"ct:rcre#1",[a,d]),l.id):h.call(f,s,new b(m.errors.a,"ct:rcre#2",[a,d,l.result]))},this)},F:function(g,a,d,l,f){try{t.i(a)}catch(e){h.call(l,
f,e);return}q.isObject(d)?t.j(a)?u(g,a,d,l,f):c(g,a,d,l,f):h.call(l,f,new b(m.errors.a,"ct:rupd#6",[d,typeof d]))},q:function(a,v,d,l,f,s){Array.isArray(d)?e.call(r.remoteService,l?"move":"copy",{from:a,to:v,data:d},k,function(e,c){e?h.call(f,s,e):c.result===w.OK?(delete c.result,h.call(f,s,k,c)):h.call(f,s,new b(m.errors.a,"ct:drcp#2",[l,a,v,d,c.result]))},this):h.call(f,s,new b(m.errors.a,"ct:drcpd#1",[d]))},G:function(a,c,d,l){q.isObject(c)?e.call(r.remoteService,"update",{selector:{id:a},fields:c},
k,function(f,e){f?h.call(d,l,f):e.result===w.OK?(delete e.result,h.call(d,l,k,e)):h.call(d,l,new b(m.errors.a,"ct:rupd#5",[a,e.result]))},this):h.call(d,l,new b(m.errors.a,"ct:rupd#6",[c,typeof c]))},z:function(g,c,d,l,f,s){var n;if((g===k||g===x)&&(c===k||c===x))h.call(f,s,new b(m.errors.a,"ct:rget#3",[g,c]));else if(q.isObject(d)){n={};try{g!==k&&g!==x&&(t.l(g),n.id=g),c!==k&&c!==x&&(t.i(c),n.type=c)}catch(u){h.call(f,s,u);return}d.type||(d.type=1);d.version||(d.version=1);e.call(r.remoteService,
"read",{selector:n,fields:d},k,function(e,c){if(e)h.call(f,s,e);else if(c.result===w.OK)if(1===d.data){var n=c.resources.length,v=y,q=p;l||(l={});for(var u in c.resources)t.j(c.resources[u].type)||(q=y,function(g){l.onerror=l.onabort=function(a){n--;v||(v=p,f.call(s||this,a))};l.onloaded=function(a){n--;v||(c.resources[g].data=a,0===n&&f.call(s||this,k,c.resources))};a.require.staticOps.downloadStaticRes({type:c.resources[g].type,resTypes:t.g,src:r.staticResURL.replace("#id",c.resources[g].id).replace("#v",
c.resources[g].version),ext:c.resources[g].name.substring(c.resources[g].name.lastIndexOf(".")+1),cookie:{add:c.resources[g].id+"="+c.resources[g].data+";",remove:c.resources[g].id+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"}},l,s)}(u));q&&h.call(f,s,k,c.resources)}else h.call(f,s,k,c.resources);else c.result===w.NOT_FOUND?h.call(f,s,new b(m.errors.a,"ct:rget#4",[g.toString(),c.result])):h.call(f,s,new b(m.errors.a,"ct:rget#2",[g.toString(),c.result]))},this)}else h.call(f,s,new b(m.errors.a,"ct:rget#1",
["fields",d]))},A:function(a,c,d){_.isObject(a)&&a.hasOwnProperty("id")&&a.id!==k&&a.id!==x&&a.hasOwnProperty("data")&&a.data!==k&&a.data!==x&&a.hasOwnProperty("version")&&a.version!==k&&a.version!==x?(-1<a.data.indexOf("v=")&&-1<a.data.indexOf("token=")||(a.data=r.staticResURLWithToken.replace("#id",a.id).replace("#v",a.version).replace("#token",a.data)),h.call(c,d,k,[a])):h.call(c,context,new b(m.errors.a,"ct:rget#3",[a]))},B:function(a,c,d){var l;if(a===k||a===x)h.call(c,d,new b(m.errors.a,"ct:rget#3",
[a]));else{l={};try{a!==k&&a!==x&&(t.l(a),l.id=a)}catch(f){h.call(c,d,f);return}e.call(r.remoteService,"read",{selector:l,fields:{data:1,version:1}},k,function(l,f){var e;if(l)h.call(c,d,l);else if(f.result===w.OK){for(e=0;e<f.resources.length;e++)f.resources[e].data=r.staticResURLWithToken.replace("#id",f.resources[e].id).replace("#v",f.resources[e].version).replace("#token",f.resources[e].data);h.call(c,d,k,f.resources)}else h.call(c,d,new b(m.errors.a,"ct:rget#2",[a.toString(),f.result]))},this)}},
s:function(a,c,d){try{t.l(a)}catch(l){h.call(c,d,l);return}e.call(r.remoteService,"remove",{id:a},k,function(f,e){f?h.call(c,d,f):e.result===w.OK?h.call(c,d,k,e.id):h.call(c,d,new b(m.errors.a,"ct:rdel#1",[a,e.result]))},this)}}}};A("PENGO.client.plugins.resManager.module");
window.PENGO.client.plugins.resManager.module.resolve=function(a,m){function q(){this.c=this.m=this.e=k;this.b={};this.H=function(){}}var h=a.util.callback,b=a.pengoError.pengoError.StoredPengoError,t={RESMGR_RES_UPDATED:"resMgr/res/updated"};q.prototype={D:function(a,e){this.e=a;if(e===k)throw new b(this.e,"mod:conf#1");if(e.remoteService===k)throw new b(this.e,"mod:conf#2",["remoteService"]);if("string"!==typeof e.remoteService)throw new b(this.e,"mod:conf#3",["remoteService"]);if(e.staticResURL===
k)throw new b(this.e,"mod:conf#2",["staticResURL"]);if("string"!==typeof e.staticResURL)throw new b(this.e,"mod:conf#3",["staticResURL"]);if(e.staticResURLWithToken===k)throw new b(this.e,"mod:conf#2",["staticResURLWithToken"]);if("string"!==typeof e.staticResURLWithToken)throw new b(this.e,"mod:conf#3",["staticResURLWithToken"]);this.b.remoteService=e.remoteService;this.b.staticResURL=e.staticResURL;this.b.staticResURLWithToken=e.staticResURLWithToken},k:function(a,b,c){if(this.c!==a){var m={update:{callback:function(a){this.f.emit("RESMGR_RES_UPDATED",
a)},context:this}};this.c!==k&&this.c.unbind(this.b.remoteService,m,function(){this.c.call(this.b.remoteService,"unsubscribe",k,k,function(){},this)},this);this.c=a;this.c!==k?this.c.call(this.b.remoteService,"subscribe",k,k,function(a,n){a||(this.b.maxResSize=n.config.maxResSize,this.b.maxStorageSize=n.config.maxStorageSize,this.c.bind(this.b.remoteService,m,k,function(a){h.call(b,c,a)},this))},this):h.call(b,c)}},n:function(a){if(this.f!==a){if(this.f)try{this.f.removeEvents(t)}catch(b){this.m.warn("Error "+
b+" while removing events when changing events manager")}(this.f=a)&&this.f.registerEvents(t)}return this.f!==k},start:function(a,b,c,q,t){this.m=a;this.k(b,function(a){a||(this.n(c),this.h=new m.model(this.c.getServiceProtocolConstants(this.b.remoteService)),this.d=new m.controller(this.h,this.b,this.c));h.call(q,t,a)},this)},stop:function(){this.h=this.d=k;this.n(k);this.k(k);this.m=k}};return q};A("PENGO.client.plugins.resManager.activator");
(function(){function a(c){c===u.config.remoteService&&(n.off("REMOTE_SERVICE_AVAILABLE",a),q())}function m(a){a===u.config.remoteService&&(n.off("REMOTE_SERVICE_UNAVAILABLE",m),h(p,p))}function q(){c.off("SERVICE_REGISTERED",q);w=c.getService("igloo.logger")[0];n=c.getService("net")[0];if(!w||!n||!c.getService("igloo.fatal")[0]||!c.getService("igloo.eventsManager")[0])c.on("SERVICE_REGISTERED",q);else if(n.isServiceAvailable(u.config.remoteService)){n.on("REMOTE_SERVICE_UNAVAILABLE",m);g===k&&(g=
new r.module);try{g.D(u.config.errorsStore,u.config)}catch(e){c.getService("igloo.fatal")[0].handleFatal({Message:e.message,Source:"Setting plugin '"+c.getPluginId()+"'"});return}r.errors.a=u.config.errorsStore;g.start(w,n,c.getService("igloo.eventsManager")[0],function(a){a?c.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"Starting plugin '"+c.getPluginId()+"'"}):(v={functions:{getTypes:g.h.w,isDynamicType:g.h.j,getTypeFromMime:g.h.v,getStates:g.h.u,createResource:g.d.r,updateResource:g.d.F,
updateResourceMetadata:g.d.G,copyDynamicResourceContent:g.d.q,readResources:g.d.z,readStaticResURLs:g.d.B,readStaticResURLSFromData:g.d.A,deleteResource:g.d.s},properties:{}},c.register(t,v),c.on("SERVICE_UNREGISTERED",b),c.on("SERVICE_UPDATED",d))},this)}else n.on("REMOTE_SERVICE_AVAILABLE",a)}function h(l,f){v!==k&&c.unregister(t,v);g!==k&&g.stop();if(n!==k)if(!l||!f)n.off("REMOTE_SERVICE_AVAILABLE",a),n.off("REMOTE_SERVICE_UNAVAILABLE",m);else if(f)n.on("REMOTE_SERVICE_AVAILABLE",a);c.off("SERVICE_UNREGISTERED",
b);c.off("SERVICE_UPDATED",d);if(l&&!f)c.on("SERVICE_REGISTERED",q);else c.off("SERVICE_REGISTERED",q);e.remove(u.config.errorsStore)}function b(b){switch(b){case "net":if(c.getService("net")[0]!==n&&(n!==k&&(n.off("REMOTE_SERVICE_UNAVAILABLE",m),n.off("REMOTE_SERVICE_AVAILABLE",a)),g.k(k),n=c.getService("net")[0],n!==k)){if(n.isServiceAvailable(u.config.remoteService))g.k(n,function(a){if(a)c.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"When unregistered service '"+b+"', plugin: '"+
c.getPluginId()+"'"});else n.on("REMOTE_SERVICE_UNAVAILABLE",m)});else n.on("REMOTE_SERVICE_AVAILABLE",a);return}break;default:return}h(p)}var t="resManager",r,e,c,u,w,n,g,v,d=b;window.PENGO.client.plugins.resManager.activator.activator=function(a,b){e=a.pengoError.pengoError.storage;return{start:function(a,d){c=a;u=d;r=b;e.add(d.config.errorsStore,b.errors.t);q()},stop:h}}})();})();
