/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var k=void 0,n=this;function s(a){a=a.split(".");var b=n;!(a[0]in b)&&b.execScript&&b.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)b=b[c]?b[c]:b[c]={}}Math.random();s("PENGO.client.plugins.support.errors");window.PENGO.client.plugins.support.errors.resolve=function(a){return{s:k,l:{"mod:conf#1":{msg:!1,code:a.pengoError.codes.codes.NOT_FOUND}}}};s("PENGO.client.plugins.support.module");
window.PENGO.client.plugins.support.module.resolve=function(a,b){function c(){this.g=this.e=this.k=k;this.d={}}var f=a.pengoError.pengoError.StoredPengoError;c.prototype={q:function(a,b,d){this.k=a;if(b===k)throw new f(this.k,"mod:conf#1");this.d=b;this.d.version=d.version;this.d.type=d.type;this.d.i=d.appkey},j:function(a){this.g=a},start:function(a,c,d,f,m){this.e=a;this.m=c;this.model=new (b.model.n(this))({});this.d.type&&this.model.set("type",this.d.type);this.d.appkey&&this.model.set("appkey",
this.d.appkey);this.j(d);this.h=new b.controller(this);f&&f.call(m||this)},stop:function(){this.h=k;this.j();this.e=this.m=this.model=k}};return c};s("PENGO.client.plugins.support.model");window.PENGO.client.plugins.support.model.resolve=function(a){return{n:function(){return a.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{sessionID:k,type:k,appkey:k}}})}}};s("PENGO.client.plugins.support.controller");
window.PENGO.client.plugins.support.controller.resolve=function(){return function(a){return{p:function(b,c,f){var e;if(a.d.enabled){e=b&&b.sessionID||a.model.get("sessionID");try{$.ajax({url:a.d.errorsURL,type:"POST",data:{a:e,b:b&&b.projectID||a.d.i,c:b&&b.type||a.d.type,f:{id:b&&b.projectID||a.d.i,version:a.d.version,stack:b&&b.stack,platform:window.navigator.platform,userAgent:window.navigator.userAgent}},dataType:"json",success:function(d,b,e){var g;switch(e.status){case 200:try{g=d&&d[0],a.g&&
a.g.emit("error","support",g),c&&c.call(f||this,g)}catch(h){a.e.error("Error '"+h+"' while parsing request response to '"+a.d.errorsURL+"'"),c&&c.call(f||this,h)}break;default:a.e.error("Status "+e.status+" while posting to '"+a.d.errorsURL+"'"),c&&c.call(f||this,Error("Status "+e.status+" while posting to '"+that.d.errorsURL+"'"))}},error:function(d,b,e){a.e.error("Error '"+e+" with response "+d.responseText+"' while posting to '"+a.d.errorsURL+"'");c&&c.call(f||this,Error("Error '"+e+" with response "+
d.responseText+"' while posting to '"+a.d.errorsURL+"'"))}})}catch(g){a.e.error("Unexpected error '"+g+" while posting to '"+a.d.errorsURL+"'"),c&&c.call(f||this,Error("Unexpected error '"+g+" while posting to '"+a.d.errorsURL+"'"))}}else c&&c.call(f||this)},o:function(b,c,f){var e,g;if(a.d.enabled){b||(b={});try{e={id:b.projectID||a.d.i,version:a.d.version,stack:b.stack,platform:window.navigator.platform,userAgent:window.navigator.userAgent};g=e.id||"foo";try{e=JSON.stringify(e)}catch(d){e="{}"}a.g&&
a.g.emit("error","fatal",g,e);c&&c.call(f||this)}catch(l){a.e.error("Unexpected error '"+l+" while emitting error event '"),c&&c.call(f||this,Error("Unexpected error '"+l+" while emitting error event '"))}}else c&&c.call(f||this)},r:function(b){a.model.set("sessionID",b)}}}};s("PENGO.client.plugins.support.activator");
(function(){function a(){d.off("SERVICE_REGISTERED",a);m=d.getService("igloo.logger")[0];if(!m||!d.getService("igloo.fatal")[0]||!d.getService("stats")[0])d.on("SERVICE_REGISTERED",a);else{h===k&&(h=new e.module);try{h.q(l.config.errorsStore,l.config,q)}catch(b){d.getService("igloo.fatal")[0].handleFatal({Message:b.message,Source:"Setting plugin '"+d.getPluginId()+"'"});return}e.errors.s=l.config.errorsStore;try{h.start(m,d.getService("igloo.fatal")[0],d.getService("stats")[0],function(a){a?d.getService("igloo.fatal")[0].handleFatal({Message:a.message,
Source:"Starting plugin '"+d.getPluginId()+"'"}):(p={functions:{sendFatalEvent:h.h.o,sendFatalReport:h.h.p,setSessionID:h.h.r},properties:{}},d.register(f,p),d.on("SERVICE_UNREGISTERED",c),d.on("SERVICE_UPDATED",r))})}catch(g){d.getService("igloo.fatal")[0].handleFatal({Message:g.message,Source:"Starting plugin '"+d.getPluginId()+"'"})}}}function b(b,e){p!==k&&d.unregister(f,p);h!==k&&h.stop();d.off("SERVICE_UNREGISTERED",c);d.off("SERVICE_UPDATED",r);if(b&&!e)d.on("SERVICE_REGISTERED",a);else d.off("SERVICE_REGISTERED",
a);g.remove(l.config.errorsStore)}function c(a){switch(a){case "stats":if(h.j(d.getService(a)[0]))return;break;default:return}b(!0)}var f="support",e,g,d,l,m,q,h,p,r=c;window.PENGO.client.plugins.support.activator.activator=function(c,f){g=c.pengoError.pengoError.storage;return{start:function(b,c,h,m){d=b;l=c;q=m;e=f;g.add(c.config.errorsStore,f.errors.l);a()},stop:b}}})();})();
