/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var b=void 0,c=!0,e=null;var f=["PENGO","client","shared","fullScreen","fullScreen"],g=this;!(f[0]in g)&&g.execScript&&g.execScript("var "+f[0]);for(var h;f.length&&(h=f.shift());){var k;if(k=!f.length)k=!1;k?g[h]=b:g=g[h]?g[h]:g[h]={}}
window.PENGO.client.shared.fullScreen.fullScreen.resolve=function(){var d={set:function(a){a||(a=document.documentElement);a.requestFullScreen?a.requestFullScreen():a.requestFullscreen?a.requestFullscreen():a.webkitRequestFullScreen?(a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT),document.webkitCurrentFullScreenElement||a.webkitRequestFullScreen()):a.webkitRequestFullscreen?(a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT),document.g||a.webkitRequestFullscreen()):a.mozRequestFullScreen?
a.mozRequestFullScreen():a.mozRequestFullscreen?a.mozRequestFullscreen():a.oRequestFullScreen?a.oRequestFullScreen():a.oRequestFullscreen?a.oRequestFullscreen():a.msRequestFullScreen?a.msRequestFullScreen():a.msRequestFullscreen&&a.msRequestFullscreen()},f:function(){document.cancelFullScreen?document.cancelFullScreen(document):document.cancelFullscreen?document.cancelFullscreen(document):document.exitFullScreen?document.exitFullScreen(document):document.exitFullscreen?document.exitFullscreen(document):
document.webkitCancelFullScreen?document.webkitCancelFullScreen(document):document.webkitCancelFullscreen?document.webkitCancelFullscreen(document):document.webkitExitFullScreen?document.webkitExitFullScreen(document):document.webkitExitFullscreen?document.webkitExitFullscreen(document):document.mozCancelFullScreen?document.mozCancelFullScreen(document):document.mozCancelFullscreen?document.mozCancelFullscreen(document):document.mozExitFullScreen?document.mozExitFullScreen(document):document.mozExitFullscreen?
document.mozExitFullscreen(document):document.oCancelFullScreen?document.oCancelFullScreen(document):document.oCancelFullscreen?document.oCancelFullscreen(document):document.oExitFullScreen?document.oExitFullScreen(document):document.oExitFullscreen?document.oExitFullscreen(document):document.msCancelFullScreen?document.msCancelFullScreen(document):document.msCancelFullscreen?document.msCancelFullscreen(document):document.msExitFullScreen?document.msExitFullScreen(document):document.msExitFullscreen&&
document.msExitFullscreen(document)},e:function(){return document.fullScreen!==b||document.fullscreen!==b||document.fullscreenElement!==b&&document.fullscreenElement!==e||document.fullScreenElement!==b&&document.fullScreenElement!==e||document.mozFullScreenElement!==b&&document.mozFullScreenElement!==e||document.webkitFullscreenElement!==b&&document.webkitFullscreenElement!==e||document.msFullscreenElement!==b&&document.msFullscreenElement!==e?c:document.webkitIsFullScreen===c||document.webkitIsFullscreen===
c||document.mozFullScreen===c||document.mozFullscreen===c||document.oFullScreen===c||document.oFullscreen===c||document.msFullScreen===c||document.msFullscreen===c},isEnabled:function(){return document.fullscreenEnabled===c||document.fullScreenEnabled===c||document.webkitFullscreenEnabled===c||document.webkitFullScreenEnabled===c||document.mozFullscreenEnabled===c||document.mozFullScreenEnabled===c||document.msFullscreenEnabled===c||document.msFullScreenEnabled===c||document.oFullscreenEnabled===
c||document.oFullScreenEnabled===c},c:function(a){a||(a=document.documentElement);var d=a.requestFullScreen||a.requestFullscreen||a.webkitRequestFullScreen||a.webkitRequestFullscreen||a.mozRequestFullScreen||a.mozRequestFullscreen||a.oRequestFullScreen||a.oRequestFullscreen||a.msRequestFullScreen||a.msRequestFullscreen;return function(){d.call(a)}},d:function(){var a=document.cancelFullScreen||document.cancelFullscreen||document.exitFullScreen||document.exitFullscreen||document.webkitCancelFullScreen||
document.webkitCancelFullscreen||document.webkitExitFullScreen||document.webkitExitFullscreen||document.mozCancelFullScreen||document.mozCancelFullscreen||document.mozExitFullScreen||document.mozExitFullscreen||document.oCancelFullScreen||document.oCancelFullscreen||document.oExitFullScreen||document.oExitFullscreen||document.msCancelFullScreen||document.msCancelFullscreen||document.msExitFullScreen||document.msExitFullscreen;return function(){a.call(document)}},b:function(){return document.fullScreen!==
b||document.fullscreen!==b||document.fullscreenElement!==b||document.fullScreenElement!==b||document.mozFullScreenElement!==b||document.webkitFullscreenElement!==b||document.msFullscreenElement!==b?function(){return document.fullScreen!==b||document.fullscreen!==b||document.fullscreenElement!==e||document.fullScreenElement!==e||document.mozFullScreenElement!==e||document.webkitFullscreenElement!==e||document.msFullscreenElement!==e}:document.webkitIsFullScreen!==b?function(){return document.webkitIsFullScreen}:
document.webkitIsFullscreen!==b?function(){return document.webkitIsFullscreen}:document.mozFullScreen!==b?function(){return document.mozFullScreen}:document.mozFullscreen!==b?function(){return document.mozFullscreen}:document.oFullScreen!==b?function(){return document.oFullScreen}:document.oFullscreen!==b?function(){return document.oFullscreen}:document.msFullScreen!==b?function(){return document.msFullScreen}:document.msFullscreen!==b?function(){return document.msFullscreen}:document.msFullscreenElement!==
b?function(){return document.msFullscreenElement!==e}:function(){return!1}},a:function(){return document.fullscreenEnabled!==b?function(){return document.fullscreenEnabled}:document.fullScreenEnabled!==b?function(){return document.fullScreenEnabled}:document.webkitFullscreenEnabled!==b?function(){return document.webkitFullscreenEnabled}:document.webkitFullScreenEnabled!==b?function(){return document.webkitFullScreenEnabled}:document.mozFullscreenEnabled!==b?function(){return document.mozFullscreenEnabled}:
document.mozFullScreenEnabled!==b?function(){return document.mozFullScreenEnabled}:document.msFullscreenEnabled!==b?function(){return document.msFullscreenEnabled}:document.msFullScreenEnabled!==b?function(){return document.msFullScreenEnabled}:document.oFullscreenEnabled!==b?function(){return document.oFullscreenEnabled}:document.oFullScreenEnabled!==b?function(){return document.oFullScreenEnabled}:function(){return!1}}};d.set=d.set;d.unset=d.f;d.isSet=d.e;d.isEnabled=d.isEnabled;d.getSetCallback=
d.c;d.getUnsetCallback=d.d;d.getIsSetCallback=d.b;d.getIsEnabledCallback=d.a;return{dependencies:function(){},implementation:{fullScreen:d}}};})();
