/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var m=void 0,n=!0,p=!1,r=this;function u(q){q=q.split(".");var k=r;!(q[0]in k)&&k.execScript&&k.execScript("var "+q[0]);for(var d;q.length&&(d=q.shift());)k=k[d]?k[d]:k[d]={}};u("PENGO.client.shared.runEngine.matchDataStorage.actuators.getMatchData");
window.PENGO.client.shared.runEngine.matchDataStorage.actuators.getMatchData.resolve=function(){function q(e,d,a,b){function c(a,b){function c(a){var b,f={};for(b in a)f[b]=a[b];return f}var d,g;a?d=1:b.result===h.OK?(d=0,g=c(b.data)):d=b.result===h.KO?1:b.result===h.USER_KO?2:1;e.callOnNextUpdateDraw(function(a){l.getting=p;if(g!==m){var b=f.b,c;for(c in g)b[c]&&(l.outParameters[b[c].name]=g[c])}l.fireOutput(d,a)})}var l=new g.runEngine.Blackbox(e,d,a,b,"_GetMatchData_key");l.createOutput("available",
0);l.createOutput("error",1);l.createOutput("accessDenied",2);l.createOutput("onPrevious",3);l.secure=n;l.getting=p;var h=m,f=g.runEngine.getManager();l.createInput("get",0,function(a){var b,e,d;if(l.secure&&l.getting)l.fireOutput(3,a);else if(d=l.getOutParams(),d.length){e=[];for(b=0;b<d.length;b+=1)l.isOutParamConnected(d[b].index)&&f.e[d[b].nameKey]&&e.push(f.e[d[b].nameKey]);e.length?(h||(h=f.s()),h?(l.getting=n,f.D(e,c)||(l.getting=p,l.fireOutput(1,a),h=m)):l.fireOutput(1,a)):l.fireOutput(0,
a)}});return l}function k(e,d){e.secure=d!==m&&d["0_S_0"]}function d(e){e.getting=p}var g;return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("_GetMatchData_key",q);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetMatchData_key",d,k);g=e},implementation:{t:q}}};u("PENGO.client.ide.runEngine.matchDataStorage.actuators.getMatchData");
window.PENGO.client.ide.runEngine.matchDataStorage.actuators.getMatchData.resolve=function(){var q,k,d,g,e=function a(b,c,e,d){c=q.runEngine.actuators.getMatchData.base.t(b,c,e,d);a.prototype.f(c);a.prototype.c(c,q.runEngine.getManager().b,m);c.onDescriptorModified=function(b,c,e){a.prototype.k(this,b,c,e)};q.runEngine.getManager().q(b.getID(c),c);return c};e.prototype={f:function(a){a.addBoolProperty(g,function(a,c){a?c.secure||(c.createOutput("onPrevious",3),c.secure=a):c.secure&&(c.delOutput(3),
c.secure=a)},m,n);a.addSeparatorProperty("all-none-separator1",m,m,m,p);a.addBoolProperty(k,function(a,c){function d(a){return c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=1)c.getProperty(f[h])||c.setProperty(f[h],n);else c.setProperty(k,p);else f.length&&f.every(d)&&c.setProperty(k,n)},m,n,n);a.addBoolProperty(d,function(a,c){function l(a){return!c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=
1)c.getProperty(f[h])&&c.setProperty(f[h],p);else c.setProperty(d,p);else f.length&&f.every(l)&&c.setProperty(d,n)},m,p,n);a.addSeparatorProperty("all-none-separator2",m,m,m,p)},a:function(a){a.splice(a.indexOf(g),1);a.splice(a.indexOf("all-none-separator1"),1);a.splice(a.indexOf(k),1);a.splice(a.indexOf(d),1);a.splice(a.indexOf("all-none-separator2"),1)},d:function(a){a=a.getPropertyKeys();e.prototype.a(a);return a},c:function(a,b,c){function d(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}
var h,f,g=function(a){var b=[],c;for(c in a)b[a[c].index]=c;return b}(b);if(c)for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c[f]===n,b[f].index,b[f].type,b[f].aggregation);else{c=d(a);for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c,b[f].index,b[f].type,b[f].aggregation)}},defineProperty:function(a,b,c,l,h){function f(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}function g(a){return e.prototype.d(a).every(function(b){return!a.getProperty(b)})}
a.addBoolProperty(b,function(a,c){a?(c.hasParamConnector(l)||(c.createOutParam(b,l),c.setParamConnectorValidTypes(l,p,h),c.setParamConnectorAggregation(l,p,p)),!c.getProperty(k)&&f(c)&&c.setProperty(k,n),c.getProperty(d)&&c.setProperty(d,p)):(c.delOutParam(l),c.getProperty(k)&&c.setProperty(k,p),!c.getProperty(d)&&g(c)&&c.setProperty(d,n))},m,c,n)},k:function(a,b,c,d){var h,f,g;for(h in b)a.delProperty(b[h].name),a.delOutParam(b[h].index);e.prototype.j(a);for(h in c)b=c[h],a.hasParamConnector(b.index,
p)&&(f=a.getParamConnectorName(b.index,p),a.setParamConnectorValidTypes(b.index,p,b.type),f!==c[h].name&&(a.changeParamConnectorName(b.index,p,b.name),g=a.getProperty(f),a.delProperty(f),e.prototype.defineProperty(a,b.name,g,b.index,b.type,m)));e.prototype.c(a,d,m)},j:function(a){function b(b){return!a.getProperty(b)}var c=a.getPropertyKeys();e.prototype.a(c);c.every(function(b){return a.getProperty(b)})?a.setProperty(k,n):c.length&&c.every(b)?a.setProperty(d,n):(a.setProperty(k,p),a.setProperty(d,
p))},i:function(a){var b,c={},d=a.getPropertyKeys();e.prototype.a(d);a.getProperty(g)===n&&(c["0_S_0"]=n);var h=q.runEngine.getManager().e;for(b=0;b<d.length;b+=1)a.getProperty(d[b])===n&&(c[h[d[b]]]=n);return c},h:function(a,b){a.setProperty(g,b!==m&&b["0_S_0"]===n);e.prototype.c(a,q.runEngine.getManager().b,b)},g:function(a,b){q.runEngine.getManager().r(b)}};return{dependencies:function(a){a.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_GetMatchData_key",e,"GetGameSessionData","GameSessionStorage/async");
a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetMatchData_key",m,e.prototype.h,e.prototype.i,e.prototype.g);a.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_GetMatchData_key",["both","both","both","sync"]);q=a;k=a.runnerKeys.SPECIAL_STR+"all";d=a.runnerKeys.SPECIAL_STR+"none";g=a.runnerKeys.SPECIAL_STR+"secure"},implementation:{t:e}}};u("PENGO.client.shared.runEngine.matchDataStorage.actuators.resetMatchData");
(function(){function q(d,g){d.secure=g["0_S_0"];d.keysToReset={};for(var e in g)"0_S_0"!=e&&(d.keysToReset[e]=n)}function k(d){d.setting=p}window.PENGO.client.shared.runEngine.matchDataStorage.actuators.resetMatchData.resolve=function(){function d(d,k,a,b){function c(a,b){var c;c=a?1:b.result===h.OK?0:b.result===h.KO?1:b.result===h.USER_KO?2:1;d.callOnNextUpdateDraw(function(a){l.setting=p;l.fireOutput(c,a)})}var l=new g.runEngine.Blackbox(d,k,a,b,"_ResetMatchData_key");l.createOutput("done",0);l.createOutput("error",
1);l.createOutput("accessDenied",2);l.createOutput("onPrevious",3);l.secure=n;l.setting=p;l.keysToReset={};var h=m,f=g.runEngine.getManager();l.createInput("reset",0,function(a){var b,d;if(l.secure&&l.setting)l.fireOutput(3,a);else{d={};for(b in l.keysToReset)f.b[b]&&(d[b]=m);f.o(d)?l.fireOutput(0,a):(h||(h=f.s()),h?(l.setting=n,f.A(d,c)||(l.setting=p,l.fireOutput(1,a),h=m)):l.fireOutput(1,a))}});return l}var g;d.prototype={};return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("_ResetMatchData_key",
d);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ResetMatchData_key",k,q);g=e},implementation:{u:d}}}})();u("PENGO.client.ide.runEngine.matchDataStorage.actuators.resetMatchData");
window.PENGO.client.ide.runEngine.matchDataStorage.actuators.resetMatchData.resolve=function(){var q,k,d,g,e=function a(b,c,d,e){c=q.runEngine.actuators.resetMatchData.base.u(b,c,d,e);a.prototype.f(c);a.prototype.c(c,q.runEngine.getManager().b,m);c.onDescriptorModified=function(b,c,d){a.prototype.k(this,b,c,d)};q.runEngine.getManager().q(b.getID(c),c);return c};e.prototype={f:function(a){a.addBoolProperty(g,function(a,c){a?c.secure||(c.createOutput("onPrevious",3),c.secure=a):c.secure&&(c.delOutput(3),
c.secure=a)},m,n);a.addSeparatorProperty("all-none-separator1",m,m,m,p);a.addBoolProperty(k,function(a,c){function d(a){return c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=1)c.getProperty(f[h])||c.setProperty(f[h],n);else c.setProperty(k,p);else f.length&&f.every(d)&&c.setProperty(k,n)},m,n,n);a.addBoolProperty(d,function(a,c){function l(a){return!c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=
1)c.getProperty(f[h])&&c.setProperty(f[h],p);else c.setProperty(d,p);else f.length&&f.every(l)&&c.setProperty(d,n)},m,p,n);a.addSeparatorProperty("all-none-separator2",m,m,m,p)},a:function(a){a.splice(a.indexOf(g),1);a.splice(a.indexOf("all-none-separator1"),1);a.splice(a.indexOf(k),1);a.splice(a.indexOf(d),1);a.splice(a.indexOf("all-none-separator2"),1)},d:function(a){a=a.getPropertyKeys();e.prototype.a(a);return a},c:function(a,b,c){function d(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}
var h,f,g=function(a){var b=[],c;for(c in a)b[a[c].index]=c;return b}(b);if(c)for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c[f]===n,b[f].index,b[f].type,b[f].aggregation);else{c=d(a);for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c,b[f].index,b[f].type,b[f].aggregation)}},defineProperty:function(a,b,c){function l(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}function h(a){return e.prototype.d(a).every(function(b){return!a.getProperty(b)})}
a.addBoolProperty(b,function(a,b){a?(!b.getProperty(k)&&l(b)&&b.setProperty(k,n),b.getProperty(d)&&b.setProperty(d,p)):(b.getProperty(k)&&b.setProperty(k,p),!b.getProperty(d)&&h(b)&&b.setProperty(d,n))},m,c,n)},k:function(a,b,c,d){var h,f;for(h in b)a.delProperty(b[h].name),a.delOutParam(b[h].index);e.prototype.j(a);for(h in c)b=c[h],f=a.getProperty(b.name),f===m&&e.prototype.defineProperty(a,b.name,f,b.index,b.type,m);e.prototype.c(a,d,m)},j:function(a){function b(b){return!a.getProperty(b)}var c=
a.getPropertyKeys();e.prototype.a(c);c.every(function(b){return a.getProperty(b)})?a.setProperty(k,n):c.length&&c.every(b)?a.setProperty(d,n):(a.setProperty(k,p),a.setProperty(d,p))},i:function(a){var b,c={},d=a.getPropertyKeys();e.prototype.a(d);a.getProperty(g)===n&&(c["0_S_0"]=n);a.keysToReset={};var h=q.runEngine.getManager().e;for(b=0;b<d.length;b+=1)a.getProperty(d[b])===n&&(c[h[d[b]]]=n,a.keysToReset[h[d[b]]]=n);return c},h:function(a,b){a.setProperty(g,b!==m&&b["0_S_0"]===n);e.prototype.c(a,
q.runEngine.getManager().b,b);a.keysToReset={};for(var c in b)"0_S_0"!=c&&(a.keysToReset[c]=n)},g:function(a,b){q.runEngine.getManager().r(b)}};return{dependencies:function(a){a.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_ResetMatchData_key",e,"ResetGameSessionData","GameSessionStorage/async");a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ResetMatchData_key",m,e.prototype.h,e.prototype.i,e.prototype.g);a.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_ResetMatchData_key",
["both","both","both","sync"]);q=a;k=a.runnerKeys.SPECIAL_STR+"all";d=a.runnerKeys.SPECIAL_STR+"none";g=a.runnerKeys.SPECIAL_STR+"secure"},implementation:{u:e}}};u("PENGO.client.shared.runEngine.matchDataStorage.manager");
window.PENGO.client.shared.runEngine.matchDataStorage.manager.resolve=function(){function q(a,b,c,d,h,f,k){this.J=b;var s;b={z:m};for(s in b);Object.defineProperty(this,s,{get:function(){return a.isOnPlay()},enumerable:n,configurable:p});b={b:m};for(s in b);Object.defineProperty(this,s,{get:function(){return e},set:function(a){e=a;t={};for(var b in e)t[e[b].name]=b},enumerable:n,configurable:p});b={e:m};for(s in b);Object.defineProperty(this,s,{get:function(){return t},set:function(a){t=a},enumerable:n,
configurable:p});k=k[g.runnerKeys.DESCRIPTOR];q.prototype.o(e)&&(k&&!q.prototype.o(k))&&(this.b=q.prototype.B(k))}function k(a,b){return function(c,d){a.z&&b(c,d)}}function d(a,b){return function(c,d){a.z&&b(c,d)}}var g,e={},t={};q.prototype={B:function(a){var b,c=[],d=[],e={},f;for(f in a)if(Array.isArray(a[f])&&5===a[f].length){b={name:a[f][0],type:"",scope:"",defaultValue:a[f][3],index:a[f][4]};switch(a[f][1]){case g.runnerKeys.bool:b.type="bool";break;case g.runnerKeys.string:b.type="string";
break;case g.runnerKeys.number:b.type="number";break;case g.runnerKeys._Vector2_:b.type="_Vector2_";break;case g.runnerKeys._Object_:b.type="_Object_"}switch(a[f][2]){case g.runnerKeys.local:b.scope="local";break;case g.runnerKeys.server:b.scope="server";break;case g.runnerKeys.local_server:b.scope="local_server"}c[a[f][4]]=f;d[a[f][4]]=b}for(a=0;a<c.length;a+=1)c[a]!==m&&d[a]!==m&&(e[c[a]]=d[a]);return e},o:function(a){for(var b in a)return p;return n},w:function(){var a={},b;for(b in e)e[b]&&(e[b].name&&
e[b].type&&e[b].scope&&e[b].defaultValue!==m)&&(a[b]={name:e[b].name,type:e[b].type,scope:e[b].scope,defaultValue:e[b].defaultValue,index:e[b].index});return a},G:function(){g.matchDataStorageService&&g.matchDataStorageService.setDescriptor&&g.matchDataStorageService.setDescriptor(this.w())},s:function(){if(g.matchDataStorageService)return g.matchDataStorageService.getProtocolConstants()},D:function(a,b){return g.matchDataStorageService?(g.matchDataStorageService.get(a,k(this,b)),n):p},A:function(a,
b){return g.matchDataStorageService?(g.matchDataStorageService.set(a,d(this,b)),n):p}};q.prototype.getDescriptor=q.prototype.w;q.prototype.provideDescriptor=q.prototype.G;return{dependencies:function(a){g=a},implementation:{Manager:q}}};u("PENGO.client.shared.runEngine.matchDataStorage.actuators.setMatchData");
(function(){function q(d,g){d.secure=g!==m&&g["0_S_0"]}function k(d){d.setting=p}window.PENGO.client.shared.runEngine.matchDataStorage.actuators.setMatchData.resolve=function(){function d(d,k,a,b){function c(a,b){var c;c=a?1:b.result===h.OK?0:b.result===h.KO?1:b.result===h.USER_KO?2:1;d.callOnNextUpdateDraw(function(a){l.setting=p;l.fireOutput(c,a)})}var l=new g.runEngine.Blackbox(d,k,a,b,"_SetMatchData_key");l.createOutput("done",0);l.createOutput("error",1);l.createOutput("accessDenied",2);l.createOutput("onPrevious",
3);l.secure=n;l.setting=p;var h=m,f=g.runEngine.getManager();l.createInput("set",0,function(a){var b,d,e,g;if(l.secure&&l.setting)l.fireOutput(3,a);else if(e=l.getInParams(),e.length){d={};for(b=0;b<e.length;b+=1)g=l.getInParamValue(e[b].index),g!==m&&f.e[e[b].nameKey]&&(d[f.e[e[b].nameKey]]=g);f.o(d)?l.fireOutput(0,a):(h||(h=f.s()),h?(l.setting=n,f.A(d,c)||(l.setting=p,l.fireOutput(1,a),h=m)):l.fireOutput(1,a))}});return l}var g;d.prototype={};return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("_SetMatchData_key",
d);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SetMatchData_key",k,q);g=e},implementation:{v:d}}}})();u("PENGO.client.ide.runEngine.matchDataStorage.actuators.setMatchData");
window.PENGO.client.ide.runEngine.matchDataStorage.actuators.setMatchData.resolve=function(){var q,k,d,g,e=function a(b,c,d,e){c=q.runEngine.actuators.setMatchData.base.v(b,c,d,e);a.prototype.f(c);a.prototype.c(c,q.runEngine.getManager().b,m);c.onDescriptorModified=function(b,c,d){a.prototype.k(this,b,c,d)};q.runEngine.getManager().q(b.getID(c),c);return c};e.prototype={f:function(a){a.addBoolProperty(g,function(a,c){a?c.secure||(c.createOutput("onPrevious",3),c.secure=a):c.secure&&(c.delOutput(3),
c.secure=a)},m,n);a.addSeparatorProperty("all-none-separator1",m,m,m,p);a.addBoolProperty(k,function(a,c){function d(a){return c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=1)c.getProperty(f[h])||c.setProperty(f[h],n);else c.setProperty(k,p);else f.length&&f.every(d)&&c.setProperty(k,n)},m,n,n);a.addBoolProperty(d,function(a,c){function g(a){return!c.getProperty(a)}var h,f=c.getPropertyKeys();e.prototype.a(f);if(a)if(f.length)for(h=0;h<f.length;h+=
1)c.getProperty(f[h])&&c.setProperty(f[h],p);else c.setProperty(d,p);else f.length&&f.every(g)&&c.setProperty(d,n)},m,p,n);a.addSeparatorProperty("all-none-separator2",m,m,m,p)},a:function(a){a.splice(a.indexOf(g),1);a.splice(a.indexOf("all-none-separator1"),1);a.splice(a.indexOf(k),1);a.splice(a.indexOf(d),1);a.splice(a.indexOf("all-none-separator2"),1)},d:function(a){a=a.getPropertyKeys();e.prototype.a(a);return a},c:function(a,b,c){function d(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}
var h,f,g=function(a){var b=[],c;for(c in a)b[a[c].index]=c;return b}(b);if(c)for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c[f]===n,b[f].index,b[f].type,b[f].aggregation);else{c=d(a);for(h=0;h<g.length;h+=1)f=g[h],f!==m&&e.prototype.defineProperty(a,b[f].name,c,b[f].index,b[f].type,b[f].aggregation)}},defineProperty:function(a,b,c,g,h){function f(a){return e.prototype.d(a).every(function(b){return a.getProperty(b)})}function q(a){return e.prototype.d(a).every(function(b){return!a.getProperty(b)})}
a.addBoolProperty(b,function(a,c){a?(c.hasParamConnector(g)||(c.createInParam(b,g),c.setParamConnectorValidTypes(g,n,h),c.setParamConnectorAggregation(g,n,p)),!c.getProperty(k)&&f(c)&&c.setProperty(k,n),c.getProperty(d)&&c.setProperty(d,p)):(c.delInParam(g),c.getProperty(k)&&c.setProperty(k,p),!c.getProperty(d)&&q(c)&&c.setProperty(d,n))},m,c,n)},k:function(a,b,c,d){var g,f,k;for(g in b)a.delProperty(b[g].name),a.delInParam(b[g].index);e.prototype.j(a);for(g in c)b=c[g],a.hasParamConnector(b.index,
p)&&(f=a.getParamConnectorName(b.index,p),a.setParamConnectorValidTypes(b.index,p,b.type),f!==c[g].name&&(a.changeParamConnectorName(b.index,p,b.name),k=a.getProperty(f),a.delProperty(f),e.prototype.defineProperty(a,b.name,k,b.index,b.type,m)));e.prototype.c(a,d,m)},j:function(a){function b(b){return!a.getProperty(b)}var c=a.getPropertyKeys();e.prototype.a(c);c.every(function(b){return a.getProperty(b)})?a.setProperty(k,n):c.length&&c.every(b)?a.setProperty(d,n):(a.setProperty(k,p),a.setProperty(d,
p))},i:function(a){var b,c={},d=a.getPropertyKeys();e.prototype.a(d);a.getProperty(g)===n&&(c["0_S_0"]=n);var h=q.runEngine.getManager().e;for(b=0;b<d.length;b+=1)a.getProperty(d[b])===n&&(c[h[d[b]]]=n);return c},h:function(a,b){a.setProperty(g,b!==m&&b["0_S_0"]===n);e.prototype.c(a,q.runEngine.getManager().b,b)},g:function(a,b){q.runEngine.getManager().r(b)}};return{dependencies:function(a){a.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_SetMatchData_key",e,"SetGameSessionData","GameSessionStorage/async");
a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SetMatchData_key",m,e.prototype.h,e.prototype.i,e.prototype.g);a.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_SetMatchData_key",["both","both","both","sync"]);q=a;k=a.runnerKeys.SPECIAL_STR+"all";d=a.runnerKeys.SPECIAL_STR+"none";g=a.runnerKeys.SPECIAL_STR+"secure"},implementation:{v:e}}};u("PENGO.client.ide.runEngine.matchDataStorage.manager");
window.PENGO.client.ide.runEngine.matchDataStorage.manager.resolve=function(){function q(d,g,e,k,a,b,c){this.m={};q.super_.constructor.call(this,d,g,e,k,a,b,c)}var k;q.prototype={H:function(d){var g=this.b,e={},k={n:{},p:{},l:{}};if(d){for(var a in d)if(d[a]&&d[a].name&&d[a].type&&d[a].scope&&d[a].defaultValue!==m){if(g[a]){if(d[a].name!==g[a].name||d[a].type!==g[a].type)k.p[a]={name:d[a].name,type:d[a].type,scope:d[a].scope,defaultValue:d[a].defaultValue,index:d[a].index}}else k.l[a]={name:d[a].name,
type:d[a].type,scope:d[a].scope,defaultValue:d[a].defaultValue,index:d[a].index};e[a]={name:d[a].name,type:d[a].type,scope:d[a].scope,defaultValue:d[a].defaultValue,index:d[a].index};delete g[a]}for(a in g)k.n[a]={name:g[a].name,type:g[a].type,scope:g[a].scope,defaultValue:g[a].defaultValue,index:g[a].index};this.b=e}return k},I:function(d){var g,e,k=this.b,a={n:{},p:{},l:{},encoded:{}};if(d){for(e in d)if(d[e]){if(k[e])g=k[e].index,a.p[e]={name:d[e].name,type:d[e].type,scope:d[e].scope,defaultValue:d[e].defaultValue,
index:g},delete this.e[k[e].name];else{g=k;var b=[],c=m;for(c in g)b[g[c].index]=c;g=b.length;a.l[e]={name:d[e].name,type:d[e].type,scope:d[e].scope,defaultValue:d[e].defaultValue,index:g}}k[e]={name:d[e].name,type:d[e].type,scope:d[e].scope,defaultValue:d[e].defaultValue,index:g};this.e[d[e].name]=e;a.encoded[e]=this.C(k[e])}else k[e]&&(a.n[e]=k[e],delete this.e[k[e].name],delete k[e],a.encoded[e]=null);return a}},C:function(d){var g;if(d&&d.name){g=[];g[0]=d.name;switch(d.type){case "bool":g[1]=
k.runnerKeys.bool;break;case "string":g[1]=k.runnerKeys.string;break;case "number":g[1]=k.runnerKeys.number;break;case "_Vector2_":g[1]=k.runnerKeys._Vector2_;break;case "_Object_":g[1]=k.runnerKeys._Object_}switch(d.scope){case "local":g[2]=k.runnerKeys.local;break;case "server":g[2]=k.runnerKeys.server;break;case "local_server":g[2]=k.runnerKeys.local_server}g[3]=d.defaultValue;g[4]=d.index}else g=null;return g},q:function(d,g){this.m[d]=g},r:function(d){delete this.m[d]},F:function(d){for(var g in this.m)this.m[g].onDescriptorModified(d.n,
d.p,d.l)}};q.prototype.restoreDescriptor=q.prototype.H;q.prototype.updateDescriptor=q.prototype.I;q.prototype.propagateDescriptorModified=q.prototype.F;return{dependencies:function(d){k=d;d.inheritance.inheritance.inherits(q,d.runEngine.manager.base.Manager)},implementation:{Manager:q}}};})();
