/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var e=void 0,m=!0,p=!1,v=this;function D(g){g=g.split(".");var f=v;!(g[0]in f)&&f.execScript&&f.execScript("var "+g[0]);for(var a;g.length&&(a=g.shift());)f=f[a]?f[a]:f[a]={}}Math.random();D("PENGO.client.plugins.shoppingCart.view");
window.PENGO.client.plugins.shoppingCart.view.resolve=function(g,f){return{Na:function(a,d){var c=a.c.payEnabled===e?m:a.c.payEnabled;return g.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{id:"itemManagerView","class":"modal-form-shopping"},initialize:function(){this.F();this.template=a.c.pgm===a.f.G2A?_.template(d.moduleG2A):_.template(d.module);this.model.set({texts:a.b},{ab:m});this.firstRender()},F:function(){this.listenTo(this.model,"change:texts",this.render,this);this.listenTo(this.model,
"change:total",this.da,this);this.listenTo(this.model,"change:state",this.za,this);this.listenTo(this.model,"change:paymentEnabled",this.ya,this);this.listenTo(this.model.get("items"),"add",this.Sa,this);this.listenTo(this.model.get("items"),"remove",this.Ta,this);this.listenTo(this.model,"change:selectedPaymentMethod",this.U,this)},fb:function(){},render:function(){this.$el.html(this.template());this.$el.find("#title").text(this.model.get("texts").a.title);this.$el.find("#checkoutSubTotal").text(this.model.get("texts").a.checkoutSubTotal);
this.$el.find("#checkoutTaxes").text(this.model.get("texts").a.checkoutTaxes);this.$el.find("#checkoutTotal").text(this.model.get("texts").a.checkoutTotal);this.$el.find("#empty").text(this.model.get("texts").a.emptyItemList);0===this.model.get("items").length?this.$el.find("#empty").show():(this.$el.find("#empty").hide(),this.Ya());this.$el.find("#btnPay,.gvg-paypal,.gvg-total").removeClass("show");this.$el.find("#main-items").addClass("full");this.$el.find("#cart-subtotal").text(this.model.get("subTotal").toFixed(2)+
this.model.get("currency"));this.$el.find("#cart-taxes").text(this.model.get("taxes").toFixed(2)+this.model.get("currency"));this.$el.find("#cart-total").text(this.model.get("total").toFixed(2)+this.model.get("currency"));this.da();this.za();this.$el.find("#errorContainerPay").hide();this.addControllerCallbacks();return this},Ya:function(){for(var c,b,k=0;k<this.model.get("items").length;k++)b=this.model.get("items").at(k),c=this.options.viewsMgr.getViews(b)[0],c===e&&(c=new a.D({model:b,viewsMgr:this.options.viewsMgr})),
this.$el.find("#main-items").append(c.el),0<b.get("count")&&this.$el.find("#checkout-items").append(c.el)},n:function(c){c?a.e.showDomElemWaitView(this.$el.find("#container")):a.e.hideDomElemWaitView(this.$el.find("#container"))},U:function(){this.da();this.model.get("selectedPaymentMethod")&&("paypal"===this.model.get("selectedPaymentMethod").get("_id")||"g2a"===this.model.get("selectedPaymentMethod").get("_id"))&&this.$el.find(".action-bar").addClass("visible")},za:function(){switch(this.model.get("state")){case f.model.g.v:this.$el.find("#empty").hide();
this.$el.find("#error").text(this.model.get("texts").a.koItemList);this.$el.find("#error").show();break;case f.model.g.I:this.$el.find("#empty").hide();this.$el.find("#error").text(this.model.get("texts").a.koConnection);this.$el.find("#error").show();break;case f.model.g.J:this.$el.find("#checkoutView").hide();this.$el.find("#error").hide();this.$el.find("#mainView").show();break;case f.model.g.fa:this.$el.find("#empty").hide(),this.$el.find("#error").text(this.model.get("texts").a.koGetTax),this.$el.find("#error").show()}},
Sa:function(c){var b,k,d=this.$el.find("#main-items");this.$el.find("#checkout-items");if(c.get("_id")!==e&&(b=this.options.viewsMgr.getViews(c.get("_id")))&&0<b.length)for(var l=0;l<b.length;l++)b[l].parent()==d?k=b[l]:b[l].parent();k===e&&(k=new a.D({model:c,viewsMgr:this.options.viewsMgr}));if(1===this.model.get("items").length)this.$el.find("#main-items").append(k.el);else{b=p;for(l=0;l<this.model.get("items").length;l++)if(this.model.get("items").at(l).get("name")!==c.get("name")&&1===this.model.get("items").at(l).get("name").localeCompare(c.get("name"))){k.$el.insertBefore(this.$el.find("#item_"+
this.model.get("items").at(l).get("_id")));b=m;break}b||this.$el.find("#main-items").append(k.el)}1===this.model.get("items").length&&this.$el.find("#empty").hide()},Ta:function(){0===this.model.get("items").length&&this.$el.find("#empty").show()},ya:function(){this.model.get("paymentEnabled")===m?(this.model.get("selectedPaymentMethod")?(this.$el.find("#btnPay,.gvg-paypal,.gvg-total").prop("value",this.model.get("texts").a.pay+" "+this.model.get("selectedPaymentMethod").get("name")+" ( "+this.model.get("total").toFixed(2)+
this.model.get("currency")+" )"),this.$el.find("#btnPay,.gvg-paypal,.gvg-total").addClass("show"),this.$el.find("#main-items").removeClass("full"),this.$el.find(".action-bar").addClass("show")):(this.$el.find("#btnPay,.gvg-paypal,.gvg-total").removeClass("show"),this.$el.find("#main-items").addClass("full"),this.$el.find(".action-bar").removeClass("show"),this.$el.find("#errorContainerPay").hide()),c||(this.$el.find("#btnPay").addClass("disabled"),this.$el.find("#errorContainerPay").text(this.model.get("texts").a.paymentNotAvailable),
this.$el.find("#errorContainerPay").show())):(this.$el.find("#btnPay,.gvg-paypal,.gvg-total").removeClass("show"),this.$el.find("#main-items").addClass("full"),this.$el.find(".action-bar").removeClass("show"),this.$el.find("#errorContainerPay").hide())},da:function(){this.$el.find("#cart-subtotal").text(this.model.get("subTotal").toFixed(2)+this.model.get("currency"));this.$el.find("#cart-taxes").text(this.model.get("taxes").toFixed(2)+this.model.get("currency"));this.$el.find("#cart-total").text(this.model.get("total").toFixed(2)+
this.model.get("currency"));this.ya()},setCloseAction:function(a){this.$el.find("#closeCartBut").off("click");this.$el.find("#closeCartBut").click(a)},setPayButtonAction:function(a){this.$el.find("#btnPay").on("click",function(){a.call()})}})},Ma:function(a,d){return g.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.F();this.template=a.c.pgm===a.f.FTM||a.c.pgm===a.f.FTM_CM?_.template(d.itemFtm):_.template(d.item);this.model.set({texts:a.b},{ab:m});this.firstRender()},
F:function(){this.listenTo(this.model,"change:texts",this.render,this);this.listenTo(this.model,"change:price",this.ia,this);this.listenTo(this.model,"change:count",this.ja,this);this.listenTo(this.model,"change:icon",this.Fa,this);this.listenTo(this.model,"change:onCart",this.Ga,this);this.listenTo(this.model,"remove",this.Xa,this)},render:function(){this.$el.attr({id:"item_"+this.model.get("_id")});this.$el.html(this.template());this.$el.find(".item-name").text(this.model.get("name"));this.$el.find(".item-desc").text(this.model.get("description"));
this.$el.find("#payByMobile").text(this.model.get("payByMobile"));this.model.get("inCart")?this.$el.find("#buyVGLabel").text(this.model.get("texts").a.inCartText):this.$el.find("#buyVGLabel").text(this.model.get("texts").a.buyText);this.ia();this.addControllerCallbacks();return this},ia:function(){this.$el.find("#price").text(this.model.get("price").EUR+a.model.get("currency"));this.ja()},ja:function(){0==this.model.get("count")&&0<a.view.$el.find(".checkout-items").find(this.$el).length&&this.$el.remove();
parseInt(this.$el.find("#vgQuantity").text())!==this.model.get("count")&&this.$el.find("#vgQuantity").text(this.model.get("count"))},Fa:function(){this.model.get("icon")&&this.model.get("icon").src&&this.$el.find(".sc-tool-image").css({backgroundImage:"url("+this.model.get("icon").src+")"})},Ga:function(){this.model.get("onCart")?(this.$el.addClass("inCart"),this.$el.find("#buyVGLabel").text(this.model.get("texts").a.inCartText)):(this.$el.removeClass("inCart"),this.$el.find("#buyVGLabel").text(this.model.get("texts").a.buyText))},
Xa:function(a){this.remove(a)},setAddOneAcion:function(a){this.$el.find("#vgAdd").on("click",a)},setRemoveOneAcion:function(a){this.$el.find("#vgRemove").on("click",a)},setBuyAction:function(a){this.$el.find(".gvgBuy").on("click",a)}})},Oa:function(a,d){return g.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.F();this.template=_.template(d.paymentMethod);this.firstRender()},F:function(){this.listenTo(a.model,"change:paymentEnabled",this.Va,this);this.listenTo(a.model,
"change:selectedPaymentMethod",this.U,this)},Ha:function(){var c=this;this.$el.find("input").change(function(){$(this).prop("checked")?a.model.get("selectedPaymentMethod")!==c.model&&a.model.set("selectedPaymentMethod",c.model):a.model.get("selectedPaymentMethod")===c.model&&a.model.set("selectedPaymentMethod",e)})},render:function(){this.$el.attr({id:this.model.get("_id")});this.$el.html(this.template());this.$el.find("img").attr("src",this.model.get("icon")).attr("alt",this.model.get("name"));this.addControllerCallbacks();
this.Ha();return this},U:function(){a.model.get("selectedPaymentMethod")===this?this.$el.find("input").prop("checked")||this.$el.find("input").prop("checked",m):this.$el.find("input").prop("checked")&&this.$el.find("input").prop("checked",p)},Va:function(){}})}}};D("PENGO.client.plugins.shoppingCart.payment");
window.PENGO.client.plugins.shoppingCart.payment.resolve=function(g){function f(a){var d,c,h=this;this.r={};this.la=p;Object.defineProperty(this,"closed",{get:function(){switch(a){case "android":case "chromews":return h.la;default:return d?d.closed:m}},set:function(b){switch(a){case "android":case "chromews":h.la=b}},enumerable:m,configurable:m});this.i="INITIALISED";this.w="";h.gb=p;this.getError=function(){return this.w};this.open=function(b,c,q){var l=this,h,f;if("INITIALISED"!==this.i&&"CLOSED"!==
this.i)c&&c.call(q||this,Error("Duplicated payment window detected"));else switch(a){case "chromews":window.chrome&&window.chrome.app.window.create("client/plugins/shoppingCart/src/payment.html",{bounds:{left:0,top:0,width:1024,height:798},frame:"chrome"},function(a){a?(l.i="OPENED",d=a,h=function(){l.closed=p;l.Wa(b,c,q)},f=function(){l.close()},a.contentWindow.addEventListener("load",h),a.onClosed.addListener(f)):(l.w="Open window failed",l.i="FAILED")});break;case "android":d=window.open(b,"_blank",
"location=no");if(!d){c&&c.call(q||this,new g.pengoError.pengoError.PengoError("Failed to create payment window.",g.pengoError.codes.codes.INVALID_DATA));break}var n=function(){"LOADED"!==l.i&&(l.i="LOADED",l.closed=p,c&&c.call(q))},t=function(){l.w="Open window failed";l.i="FAILED";l.close()},w=function(){d.removeEventListener("loadstop",n);d.removeEventListener("loaderror",t);d.removeEventListener("exit",w);l.close()};d.addEventListener("loadstop",n);d.addEventListener("loaderror",t);d.addEventListener("exit",
w);break;default:(d=window.open(b,"","width=1024,height=768"))?c&&c.call(q||this):c&&c.call(q||this,new g.pengoError.pengoError.PengoError("Failed to create payment window.",g.pengoError.codes.codes.INVALID_DATA))}};this.close=function(){h.closed=m;h.i="CLOSED";d&&d.close()};this.Wa=function(b,k,q){h.w="";this.i="POLLING";switch(a){case "chromews":if(!d||d.contentWindow.closed){h.i="FAILED";h.w="Window closed before redirect";k&&k.call(q||h,Error(h.w));break}c=d.contentWindow.document.createElement("webview");
c.id="payment";c.setAttribute("style","position:absolute; left: 0px; width: 100%; top: 0px; height: 100%;");c.setAttribute("src",b);c.addEventListener("contentload",function(){"LOADED"!==h.i&&(h.i="LOADED",k&&k.call(q))});d.contentWindow.document.body.appendChild(c);break;case "android":alert("Not supported!! ");break;default:window.location=b}};this.postMessage=function(b,k){var q;switch(a){case "chromews":if("LOADED"===h.i){c.contentWindow.postMessage(b,k);break}c.addEventListener("contentload",
function(){c.contentWindow.postMessage(b,k)});break;case "android":q="window.messageHandlerAndroid( '"+JSON.stringify({origin:k,data:b})+"' )";d.executeScript({code:q},function(a){console.log(a);if(a[0])try{var b=JSON.parse(a[0]);h.r.message.forEach(function(a){setTimeout(function(){a(b)},0)})}catch(c){alert("Err in response "+c)}});break;default:d.postMessage(b,k)}};this.addEventListener=function(b,c,d){switch(a){case "android":this.r[b]||(this.r[b]=[]);this.r[b].push(c);break;default:window.addEventListener(b,
c,d)}};this.removeEventListener=function(b,c,d){switch(a){case "android":if(!this.r[b])break;-1<this.r[b].indexOf(c)&&this.r[b].splice(this.r[b].indexOf(c),1);break;default:window.removeEventListener(b,c,d)}}}f.prototype={};return f};D("PENGO.client.plugins.shoppingCart.errors");
window.PENGO.client.plugins.shoppingCart.errors.resolve=function(g){return{bb:e,Ia:{"md:lang#1":{msg:p,code:g.pengoError.codes.codes.NOT_FOUND},"md:lang#2":{msg:p,code:g.pengoError.codes.codes.UNEXPECTED},"md:cgf#1":{msg:p,code:g.pengoError.codes.codes.INVALID_DATA},"md:scpd#1":{msg:p,code:g.pengoError.codes.codes.UNEXPECTED},"md:scpd#2":{msg:p,code:g.pengoError.codes.codes.INVALID_TYPE},"md:gcpd#1":{msg:p,code:g.pengoError.codes.codes.UNEXPECTED},"md:gcpd#2":{msg:p,code:g.pengoError.codes.codes.INVALID_TYPE}}}};D("PENGO.client.plugins.shoppingCart.module");
window.PENGO.client.plugins.shoppingCart.module.resolve=function(g,f){function a(a,c){this.c=e;this.ca=a;this.cb=c;this.b={a:e,pa:e};this.ea={};this.view=this.model=this.h=this.d=this.q=this.Ba=this.C=this.o=this.k=this.S=this.P=this.f=this.p=this.N=this.H=this.u=this.e=this.t=this.Ca=this.j=this.oa=this.Ja=this.s=this.Da=this.D=this.K=e;this.z=p;this.Pa=function(){var a;switch(this.c.type){case "package":a="android"===window.appPlatform?window.appPlatform:this.c.type;break;default:a=this.c.type}return a}}
var d=g.util.callback,c=g.pengoError.pengoError.StoredPengoError,h={};a.prototype={Za:function(a,d,h){var l,f;if(!g.util.object.isObject(a))throw new g.pengoError.pengoError.PengoError("Configuration must be a defined Object",g.pengoError.codes.codes.NOT_FOUND);if(a.errorsStore===e||"string"!==typeof a.errorsStore)throw new g.pengoError.pengoError.PengoError("Expected config. param. 'errorsStore' must be a defined string, it is '"+a.errorsStore+"'",g.pengoError.codes.codes.INVALID_DATA);if(g.util.object.isObject(a.payRedirect)){if("string"!==
typeof a.payRedirect.link)throw new c(a.errorsStore,"md:cgf#1",["payRedirect.link","object",a.payRedirect.link]);if("string"!==typeof a.payRedirect.cdmOrigin)throw new c(a.errorsStore,"md:cgf#1",["payRedirect.cdmOrigin","object",a.payRedirect.cdmOrigin]);}else throw new c(a.errorsStore,"md:cgf#1",["payRedirect","object",a.payRedirect]);if(g.util.object.isObject(a.payResponse)){if("string"!==typeof a.payResponse.cdmOrigin)throw new c(a.errorsStore,"md:cgf#1",["payResponse.cdmOrigin","object",a.payResponse.cdmOrigin]);
}else throw new c(a.errorsStore,"md:cgf#1",["payResponse","object",a.payResponse]);if(a.pgm===e||null===a.pgm)a.pgm=d.ga;else{f=p;for(l in d)if(a.pgm===d[l]){f=m;break}f||(a.pgm=d.ga)}this.c=a;h&&h.type&&(this.c.type=h.type)},X:function(a){this.Aa=a},m:function(a,c,d,l){this.Aa!==e&&this.Aa.emit(a,c,d,l)},V:function(a){this.j=a;return this.j!==e},sa:function(a){if(a===e){if(this.t!==e){try{this.t.removeEvents(h)}catch(c){this.s.warn("Error '"+c+"' while removing events changing events manager")}this.t.off("LANGUAGE_UPDATED",
this.na);this.t=e}}else this.t=a,this.t.registerEvents(h),this.t.on("LANGUAGE_UPDATED",this.na,this)},$a:function(a){this.Ca=a;return this.Ca!==e},Y:function(a){this.e=a;return this.e!==e},aa:function(a){this.u=a;this.C=this.u===e?e:this.u.getProtocolConstants().results;return this.u!==e},Z:function(a){this.H=a;this.Ba=this.H===e?e:this.H.getProtocolConstants().results;return this.H!==e},xa:function(a){this.N=a;this.h&&this.N.registerShowShoppingCartFunction(this.h.L);return this.N!==e},W:function(a){this.k=
a;this.z=p;return this.k!==e},wa:function(a){this.p=a;this.p===e?this.f=this.q=e:(this.q=this.p.getProtocolConstants(),this.f=this.p.getPGModes());return this.p!==e},ra:function(a){this.P=a;return this.P!==e},va:function(a){this.oa=a;return this.oa!==e},ta:function(a){this.S=a;return this.S!==e},ua:function(a){this.o=a;return this.o!==e},start:function(a,c,h,l,s,r,n,t,w,E,z,F,x,G,u,y){this.s=a;this.Ja=c;this.va(G);this.W(x);this.V(h);this.ua(F);this.qa(function(a,b){if(a)d.call(u,y||this,a);else{this.b.a=
b;this.aa(r);this.Z(n);this.xa(t);this.wa(w);this.ra(E);this.sa(l);this.ta(z);if(this.model===e||this.h===e||this.view===e)this.model=new (f.model.Ra(this))({_id:"PENGO.client.plugins.shoppingCart.module.Module",texts:this.b}),this.h=f.controller(this),this.d=new f.payment(this.Pa()),this.N.registerShowShoppingCartFunction(this.h.L),this.K=f.view.Na(this,this.ca,this.C.results),this.D=f.view.Ma(this,this.ca),this.Da=f.view.Oa(this,this.ca),this.view=new this.K({model:this.model,viewsMgr:(new g.bbWrappers.viewsManager.ViewsManager).addCallback(this.h.Ua)}),
this.Y(s),this.e.addCartView(this.view);this.h.O===m&&this.h.G!==e&&this.h.L(this.h.G);d.call(u,y||this)}},this)},stop:function(){this.h.ka();this.d=e;this.Y(e);this.K=this.D=this.view=e;this.sa(e);this.h=e;this.model.clear();this.model=e;this.$a(e);this.aa(e);this.Z(e);this.W(e);this.ea={};this.b={a:e,pa:e};this.V(e);this.va(e);this.s=e},qa:function(a,k){this.j===e||null===this.j?d.call(a,k||this,new c(this.c.errorsStorage,"md:lang#1",[this.j])):this.j.getTexts(this.cb,a,k||this)},na:function(){this.qa(function(a,
c){a?this.s.warn("Error "+a+" while updating local texts"):(this.b.a=c,this.ea[this.j.getLanguage()]===e?this.k.call(this.c.remoteService,"getTexts",{lang:this.j.getLanguage()},e,function(a,b){a||b.result!==this.C.results.OK?this.s.warn("Error "+a+" while updating remote texts"):(this.ea[this.j.getLanguage()]=b.texts,this.b.pa=b.texts,this.model.A(this.b))},this):this.model.A(this.b))},this)}};return a};D("PENGO.client.plugins.shoppingCart.controller");
window.PENGO.client.plugins.shoppingCart.controller.resolve=function(g,f){return function(a){var d={O:p,G:e,Ua:function(c){c instanceof a.K?(c.addControllerCallback("setPayButtonAction",d.ma(c.model)),c.addControllerCallback("setCloseAction",d.ka)):c instanceof a.D&&(c.addControllerCallback("setAddOneAcion",d.Ka(c.model)),c.addControllerCallback("setRemoveOneAcion",d.Qa(c.model)),a.c.pgm===a.f.FTM||a.c.pgm===a.f.FTM_CM?c.addControllerCallback("setBuyAction",d.ma(c.model)):c.addControllerCallback("setBuyAction",
d.La(c.model)))},ka:function(){d.O=p;a.e&&(a.e.hideSideView(),d.G&&d.G())},R:e,l:function(){d.R===e&&(d.R=a.o.getGameProperty("id"));return d.R},ha:function(){function c(b,c){a.S.getRes(c,e,function(d,l){d||a.model.get("items").get(b).set("icon",{id:c,src:l.data.src})})}function d(b,k){b!==e||k.result!==a.C.OK?a.model.set({state:f.model.g.fa}):a.model.set({taxRate:parseFloat(k.data.tax)});a.k!==e&&a.k.isConnected()?a.k.isAnonymous()?a.H.getProjectVGs({lang:a.j.getLanguage(),type:"game",projectId:a.o.getGameProperty("id"),
projectVersion:a.o.getGameProperty("version")},{price:1,icon:1,promoName:1,promoDesc:1,extra:1},function(b,d){if(b)a.model.set({state:f.model.g.v});else if(d.result==a.Ba.OK)for(var k=0;k<d.virtualGoods.length;k++)a.model.Q(d.virtualGoods[k]),d.virtualGoods[k].icon&&c(d.virtualGoods[k]._id,d.virtualGoods[k].icon);else a.model.set({state:f.model.g.v});a.view.n(p)},this):(a.u.getMaxOrderTotalPrice(function(b,c){b?a.k!==e&&a.k.isConnected()?a.model.set({state:f.model.g.v}):a.model.set({state:f.model.g.I}):
c.result==a.C.OK&&a.model.set("maxTotalPrice",c.data.EUR)},this),a.u.get({lang:a.j.getLanguage(),type:"game",projectId:a.o.getGameProperty("id"),projectVersion:a.o.getGameProperty("version")},{price:1,icon:1,promoName:1,promoDesc:1,extra:1},function(b,d){if(b)a.k!==e&&a.k.isConnected()?a.model.set({state:f.model.g.v}):a.model.set({state:f.model.g.I});else if(d.result==a.C.OK)for(var k=0;k<d.virtualGoods.length;k++)a.model.Q(d.virtualGoods[k]),d.virtualGoods[k].icon&&c(d.virtualGoods[k]._id,d.virtualGoods[k].icon);
else a.model.set({state:f.model.g.v});a.view.n(p)},this)):(a.model.set({state:f.model.g.I}),a.view.n(p))}a.z||(a.model.clear(),a.model.set({state:f.model.g.J}),a.view.n(m),a.u.getTaxInfo(d,this))},L:function(c){d.G=c;d.ha();d.O=m;a.e.showSideView("CartView");0===a.model.get("paymentMethods").length&&a.p.getPaymentGateways({type:"game",lang:a.j.getLanguage()},{},function(c,b){!c&&b.result==a.q.results.OK&&(a.model.Ea(b.pgs),0<a.model.get("paymentMethods").length&&(a.c.pgm===a.f.ga?a.model.set("selectedPaymentMethod",
a.model.get("paymentMethods").get("paypal")):a.c.pgm===a.f.FTM?a.model.set("selectedPaymentMethod",a.model.get("paymentMethods").get("fortumo")):a.c.pgm===a.f.FTM_CM?a.model.set("selectedPaymentMethod",a.model.get("paymentMethods").get("fortumo_cm")):a.c.pgm===a.f.G2A?a.model.set("selectedPaymentMethod",a.model.get("paymentMethods").get("g2a")):a.model.get("paymentMethods").get("paypal")?a.model.set("selectedPaymentMethod",a.model.get("paymentMethods").get("paypal")):a.model.set("selectedPaymentMethod",
a.model.get("paymentMethods").at(0))))},this)},Ka:function(c){return function(){var h;a.m(d.l(),"buyVG",c.get("name"));if(0>=c.get("maxSales")||c.get("count")<c.get("maxSales"))c.set("count",c.get("count")+1),c.get("onCart")&&(h=a.model.get("maxTotalPrice"),-1===h||h>=a.model.T().total?a.model.M():(c.set("count",c.get("count")-1),a.e.showMessageDialog({title:a.b.a.warningMaxTotalTitle,text:a.b.a.warningMaxTotalText.replace("%",h),button1Text:a.b.a.ok})))}},Qa:function(c){return function(){a.m(d.l(),
"notBuyVG",c.get("name"));1<c.get("count")&&(c.set("count",c.get("count")-1),c.get("onCart")&&a.model.M())}},La:function(c){return function(){var h,b;c.get("onCart")?(a.m(d.l(),"removeFromCart",c.get("name")),c.set("onCart",p)):(a.m(d.l(),"addToCart",c.get("name")),h=a.model.get("maxTotalPrice"),b=a.model.T(),b=b.B+c.get("price").EUR*c.get("count"),b+=Math.round(b*a.model.get("taxRate")*a.model.get("decimalFactor"))/a.model.get("decimalFactor"),-1===h||h>=b?c.set("onCart",m):a.e.showMessageDialog({title:a.b.a.warningMaxTotalTitle,
text:a.b.a.warningMaxTotalText.replace("%",h),button1Text:a.b.a.ok}));a.model.M()}},ma:function(c){return function(){function h(){var b,h=p,g=[],f;a.c.pgm===a.f.FTM||a.c.pgm===a.f.FTM_CM?c.set("selectedPaymentMethod",a.model.get("selectedPaymentMethod")):f=c.get("items");if(c.get("selectedPaymentMethod")){if(a.c.pgm===a.f.FTM||a.c.pgm===a.f.FTM_CM)g.push({id:c.get("_id"),quantity:1,price:c.get("price").EUR});else for(var r=0;r<f.length;r++)f.at(r).get("onCart")&&g.push({id:f.at(r).get("_id"),quantity:f.at(r).get("count"),
price:f.at(r).get("price").EUR});a.view.n(m);b={type:"game",id:c.get("selectedPaymentMethod").get("_id")};a.z=m;a.p.pay(b,{currency:"EUR",amount:a.c.pgm===a.f.FTM||a.c.pgm===a.f.FTM_CM?c.get("price").EUR+Math.round(c.get("price").EUR*a.model.get("taxRate")*a.model.get("decimalFactor"))/a.model.get("decimalFactor"):c.get("total"),items:g},{id:a.o.getGameProperty("id"),version:a.o.getGameProperty("version")},function(c,f){function g(b){h||(h=m,a.z=p,a.view.n(p),"PENDING"===b||"OK"!==b&&"KO"!==b?a.e.showMessageDialog({title:a.b.a.pendingPayTitle,
text:a.b.a.pendingPayingText,button1Text:a.b.a.ok}):((b="OK"===b)&&d.ha(),a.e.showNotification(b?a.b.a.paymentOK:a.b.a.paymentKO,b?"ok":"ko")))}var l,z=a.c.payRedirect.cdmOrigin.split(","),r=a.c.payResponse.cdmOrigin.split(","),x,s,u,y,A=5E3,B=0,I=function C(){var c;if(!a.d||a.d.closed)a.d&&(a.d.removeEventListener("message",s,p),a.d.removeEventListener("message",u,p)),clearInterval(y),a.p?a.p.payTrackLost(b,f.orderId,function(b,k){b||k.result!==a.q.results.OK?(a.e.showMessageDialog({title:a.b.a.errorPayTitle,
text:a.b.a.errorPayingText,button1Text:a.b.a.ok}),c="KO"):k.state===a.q.orderStates.APPROVED?c="OK":k.state===a.q.orderStates.CREATED||k.state===a.q.orderStates.PENDING?a.c.pgm!==a.f.PYL?(B+=1,3<=B&&(c="PENDING")):d.O||(A=6E4):c="KO";c!==e?g(c):x=setTimeout(C,A)},this):x=setTimeout(C,A);else try{for(var h=0;h<r.length;h++)a.d.postMessage({msg:"PING_OK",mo:l},r[h]);x=setTimeout(C,A)}catch(n){a.d.removeEventListener("message",s,p),a.d.removeEventListener("message",u,p),clearTimeout(x),a.e.showMessageDialog({title:a.b.a.errorPayTitle,
text:a.b.a.errorPayingText,button1Text:a.b.a.ok}),a.view.n(p),a.d&&a.d.close()}};if(c)a.d&&a.d.close(),a.z=p,a.view.n(p),a.e.showMessageDialog({title:a.b.a.errorPayTitle,text:a.b.a.errorPayingText,button1Text:a.b.a.ok});else if(f.result==a.q.results.OK&&a.d!==e){s=function H(b){-1!==z.indexOf(b.origin)&&(clearInterval(y),a.d.removeEventListener("message",H,p),u=function(b){if(-1!==r.indexOf(b.origin)&&(a.d&&(a.d.removeEventListener("message",u,p),a.d.close()),"OK"===b.data.result||"KO"===b.data.result))g("1"===
b.data.result?"OK":"KO")},a.d.addEventListener("message",u,p))};a.d.addEventListener("message",s,p);try{l=window.parent&&window.parent.location&&(window.parent.location.origin||window.parent.location.protocol+"//"+window.parent.location.hostname+(window.parent.location.port?":"+window.parent.location.port:""))}catch(J){l=window&&window.location&&(window.location.origin||window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""))}y=setInterval(function(){try{for(var b=
0;b<z.length;b++)a.d.postMessage({URL:f.link,mo:l,rw_cpv:1},z[b])}catch(c){clearInterval(y),a.e.showMessageDialog({title:a.b.a.errorPayTitle,text:a.b.a.errorPayingText,button1Text:a.b.a.ok}),a.view.n(p),a.d&&a.d.close()}},3E3);x=setTimeout(I,A)}else a.d.close(),a.z=p,a.view.n(p),f.result==a.q.results.KO_MAX_TOTAL_PRICE?a.e.showMessageDialog({title:a.b.a.warningMaxTotalTitle,text:a.b.a.warningMaxTotalPaymentText,button1Text:a.b.a.ok}):a.e.showMessageDialog({title:a.b.a.errorPayTitle,text:a.b.a.errorPayingText,
button1Text:a.b.a.ok}),a.s.warn("Payment not done "+f.result)},this);return m}}try{a.m(d.l(),"clickPay",a.model.get("selectedPaymentMethod").get("_id"))}catch(b){}a.k.isConnected()?a.k.isAnonymous()?a.e.showMessageDialog({type:"message",title:a.b.a.loginToPurchase,text:a.b.a.needLoginToPurchase,button2Text:a.b.a.cancel,button1Text:a.b.a.login,button1Class:"",button2Action:function(){a.m(d.l(),"cancelLoginPurchaseModal")},button1Action:function(){a.m(d.l(),"okLoginPurchaseModal");a.P.showSignInDialog(e,
e,e,"fromShoppingCart")},closeButtonAction:function(){a.m(d.l(),"cancelLoginPurchaseModal")}}):a.d.open(a.c.payRedirect.link,function(b){if(b){if(b.code===g.pengoError.codes.codes.INVALID_DATA){a.e.showMessageDialog({title:a.b.a.errorPayTitle,text:a.b.a.errorPayingText,button1Text:a.b.a.ok});return}throw b;}h()||a.d.close()}):a.e.showMessageDialog({title:a.b.a.loginToPurchase,text:a.b.a.needConnectionToPurchase,button1Text:a.b.a.ok,button1Action:function(){a.m(d.l(),"okConnectPurchaseModal")},closeButtonAction:function(){a.m(d.l(),
"koConnectPurchaseModal")}})}}};return d}};D("PENGO.client.plugins.shoppingCart.model");
window.PENGO.client.plugins.shoppingCart.model.resolve=function(g){var f={fa:-3,I:-2,v:-1,J:0},a=g.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e,name:e,description:e,icon:e,price:e,count:1,onCart:p,maxSales:0,texts:e}},A:function(a){this.set({texts:a})}}),d=Backbone.Collection.extend({model:a,A:function(a){for(var b=0;b<this.length;b++)this.at(b).A(a)}}),c=g.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e,name:e,icon:e}}});return{Ra:function(h){return g.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){var a=
new d;a.comparator="description";var k=new Backbone.Collection([],{model:c});k.comparator="_id";return{_id:e,texts:e,items:a,subTotal:0,taxRate:0,decimalFactor:100,taxes:0,total:0,currency:"\u20ac",maxTotalPrice:-1,paymentMethods:k,paymentEnabled:p,selectedPaymentMethod:e,state:f.J}},A:function(a){this.set({texts:a});this.get("items").A(a)},eb:function(a){if(a){for(var c=0;c<a.length;c++)this.Q(a[c]);this.get("items").sort()}},Q:function(b){b._id===e?h.s.error("'"+b._id+"' is not a valid item id"):
this.get("items").get(b._id)||(this.get("items").add(new a({_id:b._id,name:b.promoName,description:b.promoDesc,price:b.price,maxSales:b.extra&&b.extra.maxSales?b.extra.maxSales:0})),this.get("items").sort())},Ea:function(a){if(a){for(var d=0;d<a.length;d++)a[d]._id===e?h.s.error("'"+a[d]._id+"' is not a valid payment method id"):this.get("paymentMethods").get(a[d]._id)||this.get("paymentMethods").add(new c(a[d]));this.get("paymentMethods").sort()}},T:function(){for(var a={B:0,ba:0,total:0},c=this.get("items"),
d=0;d<c.length;d++)c.at(d).get("onCart")&&(a.B+=c.at(d).get("price").EUR*c.at(d).get("count"));a.ba=Math.round(this.get("decimalFactor")*a.B*this.get("taxRate"))/this.get("decimalFactor");a.total=a.B+a.ba;return a},M:function(){var a=this.T();this.set({subTotal:a.B,taxes:a.ba,total:a.total});0<a.total&&this.get("state")===f.J?this.set("paymentEnabled",m):this.set("paymentEnabled",p)},clear:function(){for(var a=this.get("items");0<a.length;)a.pop();this.M()}})},g:f}};D("PENGO.client.plugins.shoppingCart.activator");
(function(){function g(){b.off("SERVICE_REGISTERED",g);r=b.getService("igloo.logger")[0];if(!r||!b.getService("igloo.fatal")[0]||!b.getService("languageManager")[0]||!b.getService("igloo.eventsManager")[0]||!b.getService("game.uiManager")[0]||!b.getService("virtualGoods.orders")[0]||!b.getService("virtualGoods.execution")[0]||!b.getService("virtualGoods.cart")[0]||!b.getService("net")[0]||!b.getService("game.loader")[0]||!b.getService("game.gameManager")[0]||!b.getService("paymentsMgr")[0]||!b.getService("game.accountManager")[0])b.on("SERVICE_REGISTERED",
g);else{n||(n=new l.module(s.templates,s.textsURL));try{n.Za(s.config,b.getService("paymentsMgr")[0].getPGModes(),k)}catch(d){b.getService("igloo.fatal")[0].handleFatal({Message:d.message,Source:"Setting plugin '"+b.getPluginId()+"'"});return}l.errors.bb=s.config.errorsStore;b.getService("stats")[0]&&n.X(b.getService("stats")[0]);b.on("SERVICE_REGISTERED",f);b.on("SERVICE_UNREGISTERED",a);n.start(r,b.getService("igloo.fatal")[0],b.getService("languageManager")[0],b.getService("igloo.eventsManager")[0],
b.getService("game.uiManager")[0],b.getService("virtualGoods.orders")[0],b.getService("virtualGoods.execution")[0],b.getService("virtualGoods.cart")[0],b.getService("paymentsMgr")[0],b.getService("game.accountManager")[0],b.getService("game.loader")[0],b.getService("game.gameManager")[0],b.getService("net")[0],b,function(a){a?b.getService("igloo.fatal")[0].handleFatal({Message:"Error '"+a.message+"' while starting plugin '"+b.getPluginId()+"'",Source:"Starting plugin '"+b.getPluginId()+"'"}):(t={functions:{showCart:n.h.L},
properties:{}},b.register(h,t),b.on("SERVICE_UNREGISTERED",c),b.on("SERVICE_UPDATED",w))},this)}}function f(a){"stats"===a&&n.X(b.getService(a)[0])}function a(a){"stats"===a&&n.X(b.getService(a)[0])}function d(a,d){t!==e&&b.unregister(h,t);b.off("SERVICE_UNREGISTERED",c);b.off("SERVICE_UPDATED",w);if(a)if(d)b.off("SERVICE_REGISTERED",g);else b.on("SERVICE_REGISTERED",g);else n!==e&&n.stop();q.remove(s.config.errorsStore)}function c(a){switch(a){case "virtualGoods.orders":if(n.aa(b.getService(a)[0]))return;
break;case "virtualGoods.execution":if(n.Z(b.getService(a)[0]))return;break;case "virtualGoods.cart":if(n.xa(b.getService(a)[0]))return;break;case "paymentsMgr":if(n.wa(b.getService(a)[0]))return;break;case "game.accountManager":if(n.ra(b.getService(a)[0]))return;break;case "game.loader":if(n.ta(b.getService(a)[0]))return;break;case "languageManager":if(n.V(b.getService(a)[0]))return;break;case "game.gameManager":if(n.ua(b.getService(a)[0]))return;break;case "net":if(n.W(b.getService(a)[0]))return;
break;case "game.uiManager":if(n.Y(b.getService(a)[0]))return;break;default:return}d(m)}var h="shoppingCart",b,k,q,l,s,r,n,t,w=c;window.PENGO.client.plugins.shoppingCart.activator.activator=function(a,c){q=a.pengoError.pengoError.storage;return{start:function(a,d,f,h){b=a;s=d;k=h;l=c;q.add(d.config.errorsStore,c.errors.Ia);g()},stop:d}}})();})();
