/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var l;
(function(){var f={},c,g,h;l=function(b){this.id=b;var d=this;this.g=function(a){c=new WebSocket(a);c.binaryType="arraybuffer";d.e();return a};this.disconnect=function(){c.close();return!0};this.l=function(){return c&&c.readyState===c.OPEN};this.j=function(){return c&&c.readyState};this.k=function(){return{OPEN:c.OPEN,CLOSED:c.CLOSED,c:c.c,d:c.d,CONNECTING:c.CONNECTING}}};l.prototype={o:function(b,d){if(!b||"string"!==typeof b)throw new g("Unable to subscribe an event with invalid type "+typeof b,h.INVALID_DATA);
if(!d||"function"!==typeof d)throw new g(b+" must be subscribed with a valid function type and fn type is "+typeof d,h.INVALID_DATA);if(f[b])throw new g("Only a subscriber per event allowed and "+b+" has a previously subscribed method.",h.INVALID_DATA);f[b]=d;return!0},n:function(b,d){if(!b||"string"!==typeof b)throw new g("Unable to unsubscribe with invalid event with invalid type "+typeof b,h.INVALID_DATA);if(!d||"function"!==typeof d)throw new g(b+" must be unsubscribed with a valid function type and fn type is "+
typeof d,h.INVALID_DATA);if(!f[b])throw new g("Unbale to unsubcribe fn not subscribe to event "+b+" previously.",h.INVALID_DATA);delete f[b];return!0},send:function(b){if(!b||"object"!==typeof b)throw new g("Buffer to send invalid "+b+" only ArrayBuffer and buffer is "+typeof b,h.INVALID_DATA);if(c.readyState!==c.OPEN)throw new g(" Socket reasyState is "+c.readyState+" and is invalid state to send msg ",h.NETWORK_ERROR);c.send(b);return c.id},e:function(){c.onopen=function(b){f.connect&&f.connect(b,
c.url)};c.onclose=function(b){f.disconnect&&f.disconnect(b.code,b.reason)};c.onmessage=function(b){f.message&&f.message(b.data)};c.onerror=function(b){f.error&&f.error(b.data)}},p:function(b,d){g=b;h=d}}})();var p;
p=function(f){function c(){d={}}var g=f.pengoError.pengoError.PengoError,h=f.pengoError.codes.codes,b,d;c.prototype={h:function(a){if(d[a||"default"])throw new g("Unable to create client already exixting server with the same id "+(config.id||"default"),h.INVALID_TYPE);a=new l(a||"default");a.p(g,h);d[a.id]=a;return a.id},i:function(a){if(!a)throw new g("Unable to destroy client "+a,h.INVALID_TYPE);if(!d[a])throw new g("Client with id "+a+" to destroy not found.",h.INVALID_TYPE);delete d[a]},m:function(){return Object.keys(d)},
a:function(a){return d[a]},f:function(){var a=Object.keys(d).length,c;for(c in d)this.q(d[c],function(c){c&&b.error(c);a--;if(0===a&&0!==Object.keys(d).length){b.error("Unable to stop all ws client instances ");for(var f in d)b.error(" Unable to stop ws client "+f)}})},b:function(a){b=a}};return c};var q="PENGO client plugins ws websocket activator".split(" "),r=this;!(q[0]in r)&&r.execScript&&r.execScript("var "+q[0]);for(var s;q.length&&(s=q.shift());){var t;if(t=!q.length)t=!1;t?r[s]=void 0:r=r[s]?r[s]:r[s]={}}
(function(){function f(){a.off("SERVICE_REGISTERED",f);if(k=a.getService("igloo.logger")[0])e||(e=new u),m={functions:{createClient:e.h,destroyClient:e.i,listClients:e.m},properties:{type:"ws"}},n={functions:{connect:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).g.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)},disconnect:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).disconnect.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+
a)},on:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).o.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)},off:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).n.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)},send:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).send.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)},isConnected:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).l.apply(e.a(a),
arguments);_logger.error("Unable to execute with an invalid id "+a)},getReadyState:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).j.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)},getReadyStates:function(a){if(a)return e.a(Array.prototype.shift.call(arguments)).k.apply(e.a(a),arguments);_logger.error("Unable to execute with an invalid id "+a)}},properties:{type:"ws"}},e.b(k),a.register(b,n),a.register(d,m),a.on("SERVICE_UNREGISTERED",g),a.on("SERVICE_UPDATED",
h);else a.on("SERVICE_REGISTERED",f)}function c(){n&&a.unregister(b,n);m&&a.unregister(d,m);a.off("SERVICE_UNREGISTERED",g);a.off("SERVICE_UPDATED",h);a.off("SERVICE_REGISTERED",f)}function g(c){switch(c){case "igloo.logger":if(a.getService("igloo.logger")[0]!==k){k=a.getService("igloo.logger")[0];e.b(k);return}break;default:return}e&&e.f();n&&a.unregister(b,n);m&&a.unregister(d,m);a.off("SERVICE_UNREGISTERED",g);a.off("SERVICE_UPDATED",h);a.on("SERVICE_REGISTERED",f)}function h(b){switch(b){case "igloo.logger":a.getService("igloo.logger")[0]!==
k&&(k=a.getService("igloo.logger")[0],e.b(k))}}var b="ws",d="wsfactory",a,u,e,k,n,m;window.PENGO.client.plugins.ws.websocket.activator.activator=function(b){return{start:function(c){a=c;u=p(b);b.require.remove.deleteByName("PENGO.client.plugins.ws.websocket");f()},stop:c}}})();})();
