/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var d=void 0,k=!0,l=!1,t=this;function w(f){f=f.split(".");var g=t;!(f[0]in g)&&g.execScript&&g.execScript("var "+f[0]);for(var a;f.length&&(a=f.shift());)g=g[a]?g[a]:g[a]={}}Math.random();w("PENGO.client.plugins.game.accountManager.view");
window.PENGO.client.plugins.game.accountManager.view.resolve=function(f){var g=f.social.social.social;return{na:function(a,s){return f.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{"class":"accountView"},initialize:function(){this.s();this.template=_.template(s.module);this.model.set({texts:a.b},{ga:k});this.firstRender()},s:function(){this.listenTo(this.model,"change:user",this.Fa,this)},r:function(){var e=this,c=a.t.getGameProperty("name"),b=a.t.getGameProperty("id");this.$el.find("#openMenu .toolbar-button").on("click",
function(){e.$el.find("#openMenu").hide();e.$el.find("#mainMenu").css("display","block");e.$el.find("#mainMenu").addClass("open");a.e(b,"menuWiMi5");e.$el.parents("#pengoApp").children(".SideView").addClass("open")});this.$el.find("#closeMenu").on("click",function(){e.$el.find("#openMenu").show();e.$el.find("#mainMenu").hide();e.$el.find("#mainMenu").removeClass("open");a.e(b,"quitMenuWiMi5");e.$el.parents("#pengoApp").children(".SideView").removeClass("open")});this.$el.find("#rankingIcon").on("click",
function(){function e(){a.h!==d&&a.h.setPauseGameState(0,l)}a.o!==d&&(a.o.a(d,e,d,k),a.h!==d&&a.h.setPauseGameState(0,k));a.e(b,"ranking","fromMenuWiMi5")});this.$el.find("#social").on("click",function(c){e.$el.find("#socialtools").toggle();e.$el.find("#social").toggleClass("open");e.$el.find("#social").hasClass("open")?a.e(b,"share","open"):a.e(b,"share","close");c.stopPropagation()});this.$el.find("#twitter").on("click",function(r){e.$el.find("#socialtools").hide();e.$el.find("#social").removeClass("open");
var p=window.location.href,f=a.b.socialTwitterText;"http"!==p.substr(0,4)&&(p=d,f=a.b.socialTwitterTextShort);g.shareOnTwitter(f.replace("#1",c),p,a.b.socialTwitterVia);a.e(b,"share","twitter");r.stopPropagation()});this.$el.find("#facebook").on("click",function(r){e.$el.find("#socialtools").hide();e.$el.find("#social").removeClass("open");var f=window.location.href,q=a.b.socialFacebookText;"http"!==f.substr(0,4)&&(f=d,q=a.b.socialFacebookTextShort);g.shareOnFacebook(q.replace("#1",c),f,a.b.socialFacebookTitle);
a.e(b,"share","facebook");r.stopPropagation()});this.$el.find("#moregamesIcon").on("click",function(){window.open(a.k.playURL,"_blank");a.e(b,"moreGames")});this.$el.find("#mainMenu").on("click",function(){e.$el.find("#socialtools").hide();e.$el.find("#social").removeClass("open")});window.addEventListener("resize",function(){e.U();setTimeout(function(){e.ea()},a.k.fullScreenButtonsTimeout===d?0:a.k.fullScreenButtonsTimeout)})},render:function(){function e(){var r=window[c()]||1;(window.devicePixelRatio||
1)===r?b.$el.find("#resolution").hide():a.h!==d?a.h.getHDGraphicsMode(0,function(a){a===k&&b.$el.find("#resolution").addClass("hdmode")}):setTimeout(e,250)}function c(){for(var b=["backingStorePixelRatio","webkitBackingStorePixelRatio","mozBackingStorePixelRatio","msBackingStorePixelRatio","oBackingStorePixelRatio"],a=document.createElement("div"),e="",c=0;c<b.length;++c)if("undefined"!=typeof a.style[b[c]]){e=b[c];break}else e=null;return e}var b=this;this.$el.html(this.template());this.U();this.ea();
a.o!==d&&this.fa();e();this.r();this.addControllerCallbacks();return this},fa:function(){function e(b){b===k&&c.$el.find("#rankingIcon").addClass("show")}var c=this;a.o!==d&&a.o.c(e)},U:function(){this.$el.find("#fullScreen").hide();this.$el.find("#fullScreen").removeClass("show");this.$el.find("#restoreScreen").hide();this.$el.find("#restoreScreen").removeClass("show")},ea:function(){a.l.va()?this.$el.find("#restoreScreen").addClass("show"):window.outerHeight<screen.height&&a.l.ua()&&this.$el.find("#fullScreen").addClass("show")},
Fa:function(){this.$el.find(".toolbar-user").text(this.model.get("user"))},da:function(){this.$el.find("#signin").removeClass("show");this.$el.find("#signup").removeClass("show");this.$el.find("#toolbar-user").show();this.$el.find("#signout").addClass("show");this.$el.find("#openMenu").removeClass("log-out");this.$el.find("#closeMenu").removeClass("log-out");this.$el.find("#notification").removeClass("log-out");this.$el.find(".toolbarView ").removeClass("log-out")},J:function(){this.$el.find("#signin").addClass("show");
this.$el.find("#signup").addClass("show");this.$el.find("#toolbar-user").hide();this.$el.find("#signout").hide();this.$el.find("#openMenu").addClass("log-out");this.$el.find("#closeMenu").addClass("log-out");this.$el.find("#notification").addClass("log-out");this.$el.find(".toolbarView").addClass("log-out")},Ga:function(){},setSigninAction:function(a){this.$el.find("#signin").on("click",a)},setSignupAction:function(a){this.$el.find("#signup").on("click",a)},setSignoutAction:function(a){this.$el.find("#signout").on("click",
a)},setFullScreenAction:function(a){this.$el.find("#fullScreen").on("click",a)},setRestoreScreenAction:function(a){this.$el.find("#restoreScreen").on("click",a)},setHdModeAction:function(a){this.$el.find("#resolution").on("click",a)}})},pa:function(a,g){return f.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{"class":"accountManagerView modal-form light game"},initialize:function(){this.s();this.template=_.template(g.signin);this.model.set({texts:a.b},{ga:k});this.firstRender()},
s:function(){this.listenTo(this.model,"change:disabled",this.v,this);this.listenTo(this.model,"change:errorCode",this.w,this);this.listenTo(this.model,"change:errorCode",this.updateFocus,this)},r:function(){},render:function(){this.$el.html(this.template({title:a.b.SigninTitle,message:a.b.SigninMessage,user:a.b.SigninUser,password:a.b.SigninPassword,enterbutton:a.b.SigninEnterButton,cancelbutton:a.b.SigninCancelButton,rememberMe:a.b.SigninRemember,recoverPassword:a.b.SigninRecoverPassword}));this.w();
this.v();this.updateFocus();this.r();this.addControllerCallbacks();return this},v:function(){this.$el.find("#user").prop("disabled",this.model.get("disabled"));this.$el.find("#password").prop("disabled",this.model.get("disabled"));this.$el.find("#button").prop("disabled",this.model.get("disabled"))},w:function(){this.model.get("errorCode")===d?this.$el.find("#error").text(""):this.$el.find("#error").text(a.n.getErrorFn(this.model.get("errorCode")));this.model.get("errorCode")!==d&&this.$el.find("#password").prop("value",
"")},updateFocus:function(){var a=this;_.defer(function(){""===a.$el.find("#user").prop("value")?a.$el.find("#user").focus():a.$el.find("#password").focus()})},setSignedInCallback:function(a){this.$el.find("#enterbutton").on("click",a)},setCancelCallback:function(a){this.$el.find("#cancelbutton").on("click",a)},changeRememberMeCallback:function(a){this.$el.find("#rememberMe").on("change",a)},setRecoverNameCallback:function(a){this.$el.find("#recoverName").on("click",a)},setRecoverPasswordCallback:function(a){this.$el.find("#recoverPassword").on("click",
a)},setSignUpCallback:function(a){this.$el.find(".signup-link a").on("click",a)},setKeyDownSigninActionCallback:function(a,c){this.$el.keydown(function(b){b.which===c.key&&a.call(this)})}})},ra:function(a,g){return f.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{"class":"accountManagerView modal-form modal-column game light"},initialize:function(){this.s();this.template=_.template(g.signup);this.model.set({texts:a.b},{ga:k});this.firstRender()},s:function(){this.listenTo(this.model,
"change:disabled",this.v,this);this.listenTo(this.model,"change:errorCode",this.w,this);this.listenTo(this.model,"change:errorCode",this.updateFocus,this)},r:function(){var a=this;this.$el.find("#eula").next("label").children("span").keydown(function(c){-1<[32].indexOf(c.keyCode)&&(c.preventDefault(),a.$el.find("#eula").click())});this.$el.find("#notify").next("label").children("span").keydown(function(c){-1<[32].indexOf(c.keyCode)&&(c.preventDefault(),a.$el.find("#notify").click())})},render:function(){this.$el.html(this.template({title:a.b.SignUpTitle,
message:a.b.SignUpMessage,user:a.b.SignUpUser,email:a.b.SignUpEmail,password1:a.b.SignUpPassword1,password2:a.b.SignUpPassword2,button:a.b.SignUpButton,termsText:a.b.SignUpTermsAcceptText,termsLink:a.b.SignUpTermsAcceptLink,termsTextAnd:a.b.SignUpTermsAcceptTextAnd,cookiesLink:a.b.SignUpCookiesAcceptLink,notifyText:a.b.SignUpTermsNotifyText,notifyLink:a.b.SignUpTermsNotifyLink,termsTextFinal:a.b.SignUpTermsAcceptTextFinal}));var e=a.q.getLanguage();if(e!==d){var e=a.k.signupSlideShow["slides_"+e],
c=a.k.signupSlideShow.autoSlide;if(e!==d){var b=d,f=d,b=a.u.createSlideshow(e),f=a.u.getSlideshowView(b);a.u.startAutoSlide(b,c);this.$el.find(".iframe").html(f.$el)}}this.w();this.v();this.updateFocus();this.r();this.addControllerCallbacks();return this},v:function(){this.$el.find("#user").prop("disabled",this.model.get("disabled"));this.$el.find("#email").prop("disabled",this.model.get("disabled"));this.$el.find("#password1").prop("disabled",this.model.get("disabled"));this.$el.find("#password2").prop("disabled",
this.model.get("disabled"));this.$el.find("#button").prop("disabled",this.model.get("disabled"))},w:function(){var e=["user","email","password","eula","generic"],c=this.model.get("errorCode"),b=d;c===d&&(c={});for(var f=0;f<e.length;f+=1){var b=c[e[f]]!==d?a.f.getErrorFn(c[e[f]]):"",g=d;switch(e[f]){case "user":g=this.$el.find("#user").parent().find(".error-text.field");break;case "email":g=this.$el.find("#email").parent().find(".error-text.field").html(b);break;case "password":g=this.$el.find("#password1").parent().find(".error-text.field").html(b);
break;case "eula":g=this.$el.find("#eula").parent().find(".error-text.field").html(b);break;case "generic":g=this.$el.find("#error").html(b)}g!==d&&setTimeout(function(a,b){a.html(b)},0,g,b)}},updateFocus:function(){var a=this;_.defer(function(){""===a.$el.find("#user").prop("value")&&(""===a.$el.find("#email").prop("value")&&""===a.$el.find("#password1").prop("value")&&0===a.$el.find(".modal-form-field-input-error").length)&&a.$el.find("#user").focus()})},setSignedUpCallback:function(a){this.$el.find("#button").on("click",
a)},setSignInCallback:function(a){this.$el.find("#signin").on("click",a)},setKeyDownSignUpActionCallback:function(a,c){this.$el.keydown(function(b){b.which===c.key&&a.call(this)})},changeEulaCallback:function(a){this.$el.find("#eula").on("change",a)},changeNotifyCallback:function(a){this.$el.find("#notify").on("change",a)},closeCallback:function(a){this.$el.find(".modal-close").on("click",a)},nameInputCallback:function(e){if(a.f.regExpName)this.$el.find("#user").prop("pattern",a.f.regExpName).on("input",
e)},emailInputCallback:function(e){if(a.f.regExpEmail)this.$el.find("#email").prop("pattern",a.f.regExpEmail).on("input",e)},passwordInputCallback:function(e){if(a.f.regExpPassword)this.$el.find("#password1").prop("pattern",a.f.regExpPassword).on("input",e)},eulaInputCallback:function(a){this.$el.find("#eula").on("change",a)},nameLostfocusCallback:function(a){this.$el.find("#user").on("blur",a)},emailLostfocusCallback:function(a){this.$el.find("#email").on("blur",a)},passwordLostfocusCallback:function(a){this.$el.find("#password1").on("blur",
a)}})}}};w("PENGO.client.plugins.game.accountManager.controller");
window.PENGO.client.plugins.game.accountManager.controller.resolve=function(f){var g=f.fullScreen.fullScreen.fullScreen;return function(a){function f(){a.h!==d&&a.h.setPauseGameState(0,k)}function e(){a.h!==d&&a.h.setPauseGameState(0,l)}var c={F:function(b){b instanceof a.C?(b.addControllerCallback("setSigninAction",c.Ba),b.addControllerCallback("setSignupAction",c.Ca),b.addControllerCallback("setSignoutAction",c.Aa),b.addControllerCallback("setFullScreenAction",c.la(b)),b.addControllerCallback("setRestoreScreenAction",
c.oa(b)),b.addControllerCallback("setHdModeAction",c.ma(b))):b instanceof a.Q?(b.addControllerCallback("setSignedInCallback",a.n.signInAction(b.model,b,c.g)),a.k.key!==d&&b.addControllerCallback("setKeyDownSigninActionCallback",a.n.signInAction(b.model,b,c.g),{key:a.k.key}),b.addControllerCallback("setCancelCallback",c.T(b)),b.addControllerCallback("changeRememberMeCallback",a.n.rememberAction(b.model,b)),b.addControllerCallback("setRecoverPasswordCallback",function(){b.model.set({errorCode:d});a.n.recoverPasswordAction(b.model,
b)()}),b.addControllerCallback("setSignUpCallback",function(){b.model.set({errorCode:d});a.n.signUpAction(b.model,a.O,d,c.g)()})):b instanceof a.R&&(b.addControllerCallback("changeEulaCallback",a.f.eulaAction(b.model,b)),b.addControllerCallback("changeNotifyCallback",a.f.notifyAction(b.model,b)),b.addControllerCallback("setSignedUpCallback",a.f.signUpAction(b.model,b,d,c.g)),b.addControllerCallback("closeCallback",c.T(b)),b.addControllerCallback("nameInputCallback",a.f.nameInputAction(b.model,b)),
b.addControllerCallback("emailInputCallback",a.f.emailInputAction(b.model,b)),b.addControllerCallback("passwordInputCallback",a.f.passwordInputAction(b.model,b)),b.addControllerCallback("eulaInputCallback",a.f.eulaInputAction(b.model,b)),b.addControllerCallback("nameLostfocusCallback",a.f.nameLostfocusAction(b.model,b)),b.addControllerCallback("emailLostfocusCallback",a.f.emailLostfocusAction(b.model,b)),b.addControllerCallback("passwordLostfocusCallback",a.f.passwordLostfocusAction(b.model,b)),a.k.key!==
d&&b.addControllerCallback("setKeyDownSignUpActionCallback",a.f.signUpAction(b.model,b,d,c.g),{key:a.k.key}),b.addControllerCallback("setSignInCallback",function(){b.model.set({errorCode:d});a.f.showStateHandler(l);a.d.signIn({guest:l},a.N,c.g)}))},Ba:function(){function b(){e()}c.g===d&&(c.g=b);f();a.e(c.i(),"showSignInForm","fromMenuWiMi5");c.B(function(){a.d.signIn({guest:l},a.N,b)},b,"fromSignin")},Ca:function(){function b(){a.f.showStateHandler(l);e()}c.g===d&&(c.g=b);f();a.e(c.i(),"showSignUpForm",
"fromMenuWiMi5");c.B(function(){a.d.signUp({guest:l},a.O,d,b)},b,"fromSignup")},qa:function(){return function(){a.d.signOut(d)}},la:function(){return function(){g.set();a.e(c.i(),"fullscreen")}},oa:function(){return function(){g.unset();a.e(c.i(),"quitFullscreen")}},ma:function(b){return function(){a.h!==d&&a.h.getHDGraphicsMode(0,function(e){e===k?(a.h.setHDGraphicsMode(0,l),b.$el.find("#resolution").removeClass("hdmode"),a.e(c.i(),"HD","off")):(a.h.setHDGraphicsMode(0,k),b.$el.find("#resolution").addClass("hdmode"),
a.e(c.i(),"HD","on"))})}},va:function(){return g.isSet()},ua:function(){return g.isEnabled()},D:d,i:function(){c.D===d&&(c.D=a.t.getGameProperty("id"));return c.D},T:function(b){return function(){a.p.hideModalView(b);c.g!==d&&"function"===typeof c.g&&(c.g(),c.g=d)}},ya:function(b,g,p,q){function n(){a.d.signIn({guest:l},a.N,m);g!==d&&"function"===typeof g&&g()}function m(a,f){a!==k&&e();c.g!==d&&(c.g=d);b!==d&&"function"===typeof b&&b(f)}c.g===d&&(c.g=m,a.d.isSignedIn()===l||a.d.isAnonymous()===k?
(a.e(c.i(),"showSignInForm",q),f(),p===k?c.B(n,m,"fromSignin"):n()):m(l,k))},za:function(b,g,p,q){function n(){a.d.signUp({guest:l},a.O,d,m);g!==d&&"function"===typeof g&&g()}function m(f,g){a.f.showStateHandler(l);f!==k&&e();c.g!==d&&(c.g=d);b!==d&&"function"===typeof b&&b(g)}c.g===d&&(c.g=m,a.d.isSignedIn()===l||a.d.isAnonymous()===k?(a.e(c.i(),"showSignUpForm",q),f(),p===k?c.B(n,m,"fromSignup"):n()):m(l,k))},B:function(b,e,f){function g(){a.e(c.i(),"cancelWarning",f);e&&e()}a.p&&a.p.showMessageDialog({type:"message",
title:a.b.SignWarningTitle,text:a.b.SignWarningMessage,button1Text:a.b.SignWarningOkButton,button1Action:function(){a.e(c.i(),"okWarning",f);b!==d&&b()},button2Text:a.b.SignWarningCancelButton,button2Action:g,closeButtonAction:g})},Aa:function(){a.e(c.i(),"signout","fromMenuWiMi5");f();a.p&&a.p.showMessageDialog({type:"message",title:a.b.SignWarningTitle,text:a.b.SignWarningMessage,button1Text:a.b.SignWarningOkButton,button1Action:function(){a.e(c.i(),"okWarning","fromSignout");c.qa()()},button2Text:a.b.SignWarningCancelButton,
button2Action:function(){a.e(c.i(),"cancelWarning","fromSignout");e()},closeButtonAction:function(){a.e(c.i(),"cancelWarning","fromSignout");e()}})},ta:function(){return a.d.isAnonymous()}};return c}};w("PENGO.client.plugins.game.accountManager.module");
window.PENGO.client.plugins.game.accountManager.module.resolve=function(f,g){function a(a,c){this.k=this.ia=d;this.P=a;this.Ea=c;this.view=this.model=this.l=this.u=this.h=this.o=this.d=this.t=this.p=this.ka=this.q=this.m=this.C=this.b=d}var s=f.fullScreen.fullScreen.fullScreen;a.prototype={wa:function(a,c){this.k=a;c&&c.type&&(this.k.type=c.type);this.ia=a.errorsStore},L:function(a){this.ha=a},e:function(a,c,b,f){this.ha!==d&&this.ha.emit(a,c,b,f)},I:function(a){this.q=a;return this.q!==d},ca:function(a){a===
d?this.j!==d&&(this.j.off("LANGUAGE_UPDATED",this.X),this.j.off("USER_SIGNED_IN",this.Y),this.j.off("USER_SIGNED_UP",this.aa),this.j.off("USER_SIGNED_OUT",this.Z),this.j.off("CONNECTION_ESTABLISHED",this.V),this.j.off("CONNECTION_LOST",this.W),this.ka=d):(this.j=a,this.j.on("LANGUAGE_UPDATED",this.X,this),this.j.on("USER_SIGNED_IN",this.Y,this),this.j.on("USER_SIGNED_UP",this.aa,this),this.j.on("USER_SIGNED_OUT",this.Z,this),this.j.on("CONNECTION_ESTABLISHED",this.V,this),this.j.on("CONNECTION_LOST",
this.W,this))},M:function(a){this.p=a;return this.p!==d},H:function(a){this.t=a;return this.t!==d},G:function(a){(this.d=a)&&(this.S=this.d.isSignedIn());return this.d!==d},z:function(a){this.o=a;this.view!==d&&this.view.fa();return this.o!==d},A:function(a){this.h=a;return this.h!==d},K:function(a){this.u=a;return this.u!==d},start:function(a,c,b,r,p,q,n,m,h){this.m=a;this.I(c);this.ba(function(a,c){a||(this.b=c,this.M(r),this.H(p),this.G(q),this.K(n),this.model=new (g.model.sa(this))({_id:"PENGO.client.plugins.game.accountManager.module.Module",
texts:c}),this.l=g.controller(this),this.ca(b),this.C=g.view.na(this,this.P),this.Q=g.view.pa(this,this.P),this.R=g.view.ra(this,this.P),this.view===d&&(this.view=new this.C({model:this.model,viewsMgr:(new f.bbWrappers.viewsManager.ViewsManager).addCallback(this.l.F)}),r.addAccountView(this.view)),this.n=this.d.getSignInViewInfo(),this.n.model.set("profile","gamer"),this.N=new this.Q({model:this.n.model,viewsMgr:(new f.bbWrappers.viewsManager.ViewsManager).addCallback(this.l.F)}),this.f=this.d.getSignUpViewInfo(),
this.O=new this.R({model:this.f.model,viewsMgr:(new f.bbWrappers.viewsManager.ViewsManager).addCallback(this.l.F)}),this.d.isSignedIn()&&!this.d.isAnonymous()?(this.model.set("user",this.d.getUser()),this.view.da()):this.view.J());f.util.callback.call(m,h||this,a)},this)},stop:function(){this.M(d);this.H(d);this.G(d);this.ca(d);this.z(d);this.A(d);this.I(d);this.K(d);this.m=d},ba:function(a,c){this.q===d||null===this.q||this.q.getTexts(this.Ea,a,c||this)},X:function(){this.ba(function(a,c){!a&&this.view!==
d&&(this.b=c,this.model.xa(c))},this)},Y:function(a){this.m.debug("Signin event! "+a);if(this.S)switch(s.isEnabled()&&s.isSet()&&s.unset(),this.k.type){case "chromews":window.chrome&&window.chrome.runtime.reload();break;default:window.open(location.href.split("?")[0],"_self")}this.S=k;this.d.isSignedIn()&&(this.m.debug("Is signed in "+a),this.d.isAnonymous(a)?(this.m.debug("Is anonymous in "+a),this.view.J()):(this.m.debug("Is NOT anonymous in "+a),this.model.set("user",this.d.getUser()),this.view.da()))},
aa:function(a){this.m.debug("Signup event! "+a);this.model.set("signup",a)},Z:function(a){this.m.debug("Signout event! "+a);this.view.J()},V:function(){},W:function(){}};return a};w("PENGO.client.plugins.game.accountManager.errors");window.PENGO.client.plugins.game.accountManager.errors.resolve=function(f){return{Da:d,ja:{"md:lang#1":{msg:l,code:f.pengoError.codes.codes.NOT_FOUND}}}};w("PENGO.client.plugins.game.accountManager.model");window.PENGO.client.plugins.game.accountManager.model.resolve=function(f){return{sa:function(){return f.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:d,texts:d,user:d}},xa:function(f){this.set("texts",f)}})}}};w("PENGO.client.plugins.game.accountManager.activator");
(function(){function f(){b.off("SERVICE_REGISTERED",f);m=b.getService("igloo.logger")[0];if(!m||!b.getService("igloo.fatal")[0]||!b.getService("languageManager")[0]||!b.getService("igloo.eventsManager")[0]||!b.getService("game.uiManager")[0]||!b.getService("game.gameManager")[0]||!b.getService("uitools.slideshow")[0]||!b.getService("accountManager")[0])b.on("SERVICE_REGISTERED",f);else{h||(h=new q.module(n.templates,n.textsURL));try{h.wa(n.config,r)}catch(x){b.getService("igloo.fatal")[0].handleFatal({Message:x.message,
Source:'Setting plugin "'+b.getPluginId()+'"'})}q.errors.Da=n.config.errorsStore;b.getService("game.gameRankings")[0]&&h.z(b.getService("game.gameRankings")[0]);b.getService("game.runnerManager")[0]?h.A(b.getService("game.runnerManager")[0]):b.getService("stats")[0]&&h.L(b.getService("stats")[0]);b.on("SERVICE_REGISTERED",g);b.on("SERVICE_UNREGISTERED",a);h.start(m,b.getService("languageManager")[0],b.getService("igloo.eventsManager")[0],b.getService("game.uiManager")[0],b.getService("game.gameManager")[0],
b.getService("accountManager")[0],b.getService("uitools.slideshow")[0],function(a){a?b.getService("igloo.fatal")[0].handleFatal({Message:'Error "'+a.message+'" while starting plugin "'+b.getPluginId()+'"',Source:'Starting plugin "'+b.getPluginId()+'"'}):(u={functions:{showSignInDialog:h.l.ya,showSignUpDialog:h.l.za,isAnonymous:h.l.ta},properties:{}},b.register(c,u),b.on("SERVICE_UNREGISTERED",e),b.on("SERVICE_UPDATED",v))},this)}}function g(a){"game.gameRankings"===a?h.z(b.getService(a)[0]):"game.runnerManager"===
a?h.A(b.getService(a)[0]):"stats"===a&&h.L(b.getService(a)[0])}function a(a){"game.gameRankings"===a?h.z(b.getService(a)[0]):"game.runnerManager"===a?h.A(b.getService(a)[0]):"stats"===a&&h.L(b.getService(a)[0])}function s(a,g){u!==d&&b.unregister(c,u);h!==d&&h.stop();b.off("SERVICE_UNREGISTERED",e);b.off("SERVICE_UPDATED",v);if(a&&!g)b.on("SERVICE_REGISTERED",f);else b.off("SERVICE_REGISTERED",f);p.remove(n.errorsStore)}function e(a){switch(a){case "languageManager":if(h.I(b.getService("languageManager")[0]))return;
break;case "game.uiManager":if(h.M(b.getService("game.uiManager")[0]))return;break;case "game.gameManager":if(h.H(b.getService("game.gameManager")[0]))return;break;case "accountManager":if(h.G(b.getService("accountManager")[0]))return;break;case "uitools.slideshow":if(h.K(b.getService("uitools.slideshow")[0]))return;break;default:return}s(k)}var c="game.accountManager",b,r,p,q,n,m,h,u,v=e;window.PENGO.client.plugins.game.accountManager.activator.activator=function(a,c){p=a.pengoError.pengoError.storage;
return{start:function(a,e,g,h){b=a;n=e;q=c;r=h;p.add(e.config.errorsStore,c.errors.ja);f()},stop:s}}})();})();
