/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var a=!0,b=!1;var c=["PENGO","client","shared","deviceDetection","browserDevice"],d=this;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());){var h;if(h=!c.length)h=b;h?d[e]=void 0:d=d[e]?d[e]:d[e]={}}
window.PENGO.client.shared.deviceDetection.browserDevice.resolve=function(){var g={b:b,C:b,l:b,j:b,k:b,B:b,A:b,v:b,w:b,t:b,u:b,z:b,W:"webkit",sb:"firefox",Qa:"iphone",Ra:"ipod",Pa:"ipad",Ta:"macintosh",i:"android",Ma:"googletv",q:"htc_flyer",mb:"windows phone os 7",nb:"windows phone 8",lb:"windows ce",ob:"windows",Oa:"iemobile",bb:"ppc",wb:"wm5 pie",za:"blackberry",Aa:"bb10",Nb:"vnd.rim",Ga:"blackberry95",Ba:"blackberry97",Ca:"blackberry 99",Ia:"blackberry96",Da:"blackberry89",Ea:"blackberry 938",
Ha:"blackberry 98",Fa:"playbook",V:"symbian",gb:"symbos",U:"series60",cb:"series70",eb:"series80",fb:"series90",Za:"palm",ib:"webos",jb:"hpwos",rb:"blazer",Ab:"xiino",Ya:"nuvifone",Ja:"bada",hb:"tizen",Ua:"meego",Sa:"kindle",xb:"silk-accelerated",Vb:"vnd.wap",Wb:"wml",r:"tablet",Ka:"brew",La:"danger",Na:"hiptop",T:"playstation",ab:"vita",Xa:"nitro",Wa:"nintendo",kb:"wii",pb:"xbox",ya:"archos",s:"opera",tb:"netfront",zb:"up.browser",vb:"openweb",Va:"midp",Ub:"up.link",yb:"teleca q",ub:"obigo",$a:"pda",
Ib:"mini",h:"mobile",X:"mobi",Cb:"maemo",Bb:"linux",Jb:"sony/com",Gb:"sonyericsson",Hb:"ericsson",Eb:"sec-sgh",Fb:"sony",Db:"htc",Kb:"docomo",Lb:"kddi",Mb:"vodafone",qb:"update",a:"",xa:function(){this.b=b;this.a=navigator.userAgent.toLowerCase();this.k=this.ra();this.C=this.g();this.w=this.J();this.v=this.I();this.t=this.c();this.u=this.D();this.j=this.e();this.l=this.f();this.z=this.o();this.B=this.P();this.A=this.sa();this.b=a},J:function(){return this.b||this.w?this.w:-1<this.a.search(this.Qa)?
this.n()||this.L()?b:a:b},L:function(){return-1<this.a.search(this.Ra)?a:b},K:function(){return this.J()||this.L()?a:b},n:function(){return-1<this.a.search(this.Pa)&&this.g()?a:b},Qb:function(){return this.K()||this.n()?a:b},I:function(){return this.b||this.v?this.v:-1<this.a.search(this.sb)&&-1<this.a.search(this.h)&&0>this.a.search(this.i)?a:b},c:function(){return this.b||this.t?this.t:-1<this.a.search(this.i)||this.ha()?a:-1<this.a.search(this.q)?a:b},D:function(){return this.b||this.u?this.u:
this.c()&&-1<this.a.search(this.h)||this.la()?a:-1<this.a.search(this.q)?a:b},Z:function(){return!this.c()||this.p()||-1<this.a.search(this.q)?b:-1<this.a.search(this.h)?b:a},Ob:function(){return this.c()&&this.g()?a:b},ha:function(){return-1<this.a.search(this.Ma)?a:b},g:function(){return this.b||this.C?this.C:-1<this.a.search(this.W)?a:b},S:function(){return this.ua()||this.va()?a:b},ua:function(){return-1<this.a.search(this.mb)?a:b},va:function(){return-1<this.a.search(this.nb)?a:b},R:function(){return this.S()?
b:-1<this.a.search(this.lb)||(-1<this.a.search(this.Oa)||-1<this.a.search(this.wb))||-1<this.a.search(this.bb)&&!(-1<this.a.search(this.Ta))?a:-1<this.a.search(this.Db)&&-1<this.a.search(this.ob)?a:b},d:function(){return-1<this.a.search(this.za)||-1<this.a.search(this.Nb)?a:this.F()?a:b},F:function(){return-1<this.a.search(this.Aa)&&-1<this.a.search(this.h)?a:b},ba:function(){return-1<this.a.search(this.Fa)?a:b},m:function(){return this.d()&&-1<this.a.search(this.W)?a:b},H:function(){return this.d()&&
(-1<this.a.search(this.Ga)||-1<this.a.search(this.Ha)||-1<this.a.search(this.Ca)||-1<this.a.search(this.Ea))?a:b},G:function(){return this.m()?b:this.d()&&(this.H()||-1<this.a.search(this.Ba)||-1<this.a.search(this.Ia)||-1<this.a.search(this.Da))?a:b},Pb:function(){return this.d()?this.G()||this.m()?b:a:b},O:function(){return this.g()?-1<this.a.search(this.U)||-1<this.a.search(this.V)?a:b:b},qa:function(){return-1<this.a.search(this.V)||-1<this.a.search(this.U)||-1<this.a.search(this.gb)&&this.p||
-1<this.a.search(this.cb)||-1<this.a.search(this.eb)||-1<this.a.search(this.fb)?a:b},ma:function(){return this.N()?b:-1<this.a.search(this.Za)||-1<this.a.search(this.rb)||-1<this.a.search(this.Ab)?a:b},N:function(){return-1<this.a.search(this.ib)?a:b},Q:function(){return-1<this.a.search(this.jb)&&-1<this.a.search(this.r)?a:b},p:function(){return-1<this.a.search(this.s)&&(-1<this.a.search(this.Ib)||-1<this.a.search(this.X))?a:b},la:function(){return-1<this.a.search(this.s)&&-1<this.a.search(this.i)&&
-1<this.a.search(this.X)?a:b},Sb:function(){return-1<this.a.search(this.s)&&-1<this.a.search(this.i)&&-1<this.a.search(this.r)?a:b},M:function(){return-1<this.a.search(this.Sa)&&!this.c()?a:b},Y:function(){return-1<this.a.search(this.xb)?a:b},ga:function(){return-1<this.a.search(this.Ya)?a:b},aa:function(){return-1<this.a.search(this.Ja)?a:b},ta:function(){return-1<this.a.search(this.hb)?a:b},Rb:function(){return-1<this.a.search(this.Ua)?a:b},da:function(){return-1<this.a.search(this.La)||-1<this.a.search(this.Na)?
a:b},oa:function(){return-1<this.a.search(this.Fb)&&(-1<this.a.search(this.Tb)||-1<this.a.search(this.Jb))?a:b},ia:function(){return-1<this.a.search(this.Cb)?a:-1<this.a.search(this.Bb)&&-1<this.a.search(this.r)&&!this.Q()&&!this.c()?a:b},$:function(){return-1<this.a.search(this.ya)?a:b},ea:function(){return this.pa()||this.ka()||this.wa()?a:b},pa:function(){return-1<this.a.search(this.T)?a:b},fa:function(){return-1<this.a.search(this.T)&&-1<this.a.search(this.ab)?a:b},ka:function(){return-1<this.a.search(this.Wa)||
-1<this.a.search(this.kb)||-1<this.a.search(this.Xa)?a:b},wa:function(){return-1<this.a.search(this.pb)?a:b},ca:function(){return-1<this.a.search(this.Ka)?a:b},na:function(){return this.e()||this.O()||this.qa()||this.R()||this.d()||this.ma()?a:b},o:function(){return this.f()?b:this.b||this.z?this.z:this.na()||-1<this.a.search(this.h)||this.M()||this.Y()||-1<this.a.search(this.Va)||this.ca()||this.p()||this.$()||-1<this.a.search(this.ub)||-1<this.a.search(this.tb)||-1<this.a.search(this.zb)||-1<this.a.search(this.vb)?
a:b},ja:function(){return this.o()||this.ea()||(this.da()||this.ia()||this.oa()||this.ga())||-1<this.a.search(this.$a)&&!(-1<this.a.search(this.qb))||-1<this.a.search(this.Eb)||-1<this.a.search(this.Gb)||-1<this.a.search(this.Hb)||-1<this.a.search(this.Kb)||-1<this.a.search(this.Lb)||-1<this.a.search(this.Mb)?a:b},ra:function(){return this.b||this.k?this.k:this.f()||this.e()?a:b},f:function(){return this.b||this.l?this.l:this.n()||this.Z()||this.ba()||this.Q()?a:b},e:function(){return this.b||this.j?
this.j:this.I()||this.K()||this.D()||this.S()||this.F()||this.N()||this.aa()||this.ta()||this.fa()?a:this.m()&&this.H()?a:b},P:function(){return this.b||this.B?this.B:this.e()||(this.M()||this.f())||!this.o()?b:this.g()?a:this.O()||this.G()||this.R()||-1<this.a.search(this.yb)?a:b},sa:function(){return this.b||this.A?this.A:this.e()||this.P()||this.f()?b:this.ja()?a:b}},f={},k=void 0!=(navigator&&navigator.userAgent);Object.defineProperty(f,"isWebBrowser",{get:function(){return k},enumerable:a});
Object.defineProperty(f,"isTierMobile",{get:function(){return g.k},enumerable:a});Object.defineProperty(f,"isTierIphone",{get:function(){return g.j},enumerable:a});Object.defineProperty(f,"isTierIpad",{get:function(){return g.l},enumerable:a});return{dependencies:function(){g.xa()},implementation:{flags:f}}};})();
