/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var l=void 0,n=!0,q=!1,ca=this;function I(d){d=d.split(".");var k=ca;!(d[0]in k)&&k.execScript&&k.execScript("var "+d[0]);for(var b;d.length&&(b=d.shift());)k=k[b]?k[b]:k[b]={}};I("PENGO.client.shared.runEngine.two.actuators.setActiveScene");
window.PENGO.client.shared.runEngine.two.actuators.setActiveScene.resolve=function(){function d(b,r,e,d){var a=new k.runEngine.Blackbox(b,r,e,d,"SActScnTwo");a.createInParam("SceneToSet",0);var c=k.runEngine.getManager();a.createOutput("set",0);a.createInput("set",0,function(b){a.inParameters.SceneToSet&&(c.K(a.inParameters.SceneToSet,l,l,b,c),a.fireOutput(0,b))});return a}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("SActScnTwo",d);k=b},implementation:{X:d}}};I("PENGO.client.shared.runEngine.two.actuators.deleteObject2D");
window.PENGO.client.shared.runEngine.two.actuators.deleteObject2D.resolve=function(){function d(b,r,e,d){var a=new k.runEngine.Blackbox(b,r,e,d,"DeleteTWO"),c=k.runEngine.getManager();a.createInParam("target",0);a.createInput("do",0,function(b){a.inParameters.target&&c.z(a.inParameters.target,l,l,b,c)&&a.fireOutput(0,b)});a.createOutput("deleted",0);return a}var k;return{dependencies:function(b){k=b;k.runEngine.blackboxRepository.addBlackboxType("DeleteTWO",d)},implementation:{ia:d}}};I("PENGO.client.shared.runEngine.two.actuators.setTextProperties");
window.PENGO.client.shared.runEngine.two.actuators.setTextProperties.resolve=function(){function d(b,r,e,d){var a=new k.runEngine.Blackbox(b,r,e,d,"SetTextPropertiesTwo");a.createInParam("target",0);a.createInput("do",0,function(c){a.inParameters.target&&(a.inParameters.text!==l&&(a.inParameters.target.text=""+a.inParameters.text),a.inParameters.fontSize!==l&&(a.inParameters.target.fontSize=a.inParameters.fontSize),a.inParameters.borderWidth!==l&&(a.inParameters.target.borderWidth=a.inParameters.borderWidth),
a.fireOutput(0,c))});a.createOutput("done",0);return a}var k;return{dependencies:function(b){k=b;k.runEngine.blackboxRepository.addBlackboxType("SetTextPropertiesTwo",d);k.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SetTextPropertiesTwo","text","");k.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SetTextPropertiesTwo","fontSize",0);k.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SetTextPropertiesTwo","borderWidth",0)},implementation:{ta:d}}};I("PENGO.client.shared.runEngine.two.actuators.resetScene");
window.PENGO.client.shared.runEngine.two.actuators.resetScene.resolve=function(){function d(b,r,e,d){var a=new k.runEngine.Blackbox(b,r,e,d,"RScnTwo"),c=k.runEngine.getManager();a.createInParam("SceneToReset",0);a.createOutput("reseted",0);a.createInput("reset",0,function(b){a.inParameters.SceneToReset&&(c.s(a.inParameters.SceneToReset,l,l,b,c),a.fireOutput(0,b))});return a}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("RScnTwo",d,l,l);k=b},implementation:{X:d}}};I("PENGO.client.shared.runEngine.two.sensors.spriteAnimationSelector");
window.PENGO.client.shared.runEngine.two.sensors.spriteAnimationSelector.resolve=function(){function d(b){b.previousAnimation=l}function k(b,d,a,c){var f=new r.runEngine.Blackbox(b,d,a,c,"_SpriteAnimationSelector_TWO");f.createInParam("sprite",0);f.previousAnimation=l;f.createOutput("started",0);f.createOutput("changed",1);f.createOutput("paused",2);f.createOutput("finished",3);f.createInput("pause",0,function(a){var c=f.inParameters.sprite;c&&(c.paused=!c.paused,f.fireOutput(2,a))});return f}function b(b,
r){function a(){c.callOnNextUpdateDraw(function(a){b.fireOutput(3,a)})}var c=b.getRunner();return function(c){var d=b.inParameters.sprite;d&&(d.startAnimation(r,l,l,l,a),b.previousAnimation!==r&&(b.previousAnimation=r,b.fireOutput(1,c)),b.fireOutput(0,c))}}var r;return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("_SpriteAnimationSelector_TWO",k);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SpriteAnimationSelector_TWO",d,l);e.runEngine.blackboxRepository.setInputCallbackCreatorToBlackboxType("_SpriteAnimationSelector_TWO",
b,l);r=e},implementation:{wa:k}}};I("PENGO.client.shared.runEngine.two.actuators.visibility");
window.PENGO.client.shared.runEngine.two.actuators.visibility.resolve=function(){function d(b,r,e,d){var a=new k.runEngine.Blackbox(b,r,e,d,"VisibilityTWO");a.createInParam("target",0);a.createInParam("alpha",1);a.createOutput("shown",0);a.createOutput("hidden",1);a.createInput("show",0,function(c){a.inParameters.target&&(a.inParameters.alpha!==l?(a.inParameters.target.alpha=a.inParameters.alpha,0<a.inParameters.alpha?(a.inParameters.target.visible=n,a.fireOutput(0,c)):(a.inParameters.target.visible=
q,a.fireOutput(1,c))):(a.inParameters.target.visible=n,a.fireOutput(0,c)))});a.createInput("hide",1,function(c){a.inParameters.target&&(a.inParameters.target.visible=q,a.fireOutput(1,c))});return a}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("VisibilityTWO",d);k=b},implementation:{Ba:d}}};I("PENGO.client.shared.runEngine.two.actuators.getRandomLabels");
window.PENGO.client.shared.runEngine.two.actuators.getRandomLabels.resolve=function(){function d(r,e,d,a){var c=new b.runEngine.Blackbox(r,e,d,a,"GetRandomLabelsTwo"),f=b.runEngine.getManager(),k=l;c.setProdideResultMode=function(a){function b(a){var m=c.getOutParam(0);m&&(m.value=m.value.concat(a))}function f(a){var b=c.getOutParam(0);b&&(b.value=a)}k=a?f:b};c.setProdideResultMode(n);c.createInParam("target",0);c.createInParam("children",1);c.createInParam("numberOfLabels",2);c.createOutParam("collectionOfLabels",
0);c.createOutParam("numberOfLabels",1);c.createInput("do",0,function(a){var b,e,r,m,d;if(c.inParameters.target&&c.isOutCollection(0)){b=f.L(c.inParameters.target,c.inParameters.children);r=0;m=[];for(d=c.inParameters.numberOfLabels;r<d&&0<b.length;)e=Math.floor(Math.random()*b.length),m.push(b[e]),b.splice(e,1),r++;k(m);c.outParameters.numberOfLabels=m.length;c.fireOutput(0,a)}});c.createOutput("done",0);return c}function k(b,e){e&&e.A?b.setProdideResultMode(q):b.setProdideResultMode(n)}var b;return{dependencies:function(r){b=
r;b.runEngine.blackboxRepository.addBlackboxType("GetRandomLabelsTwo",d);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("GetRandomLabelsTwo",l,k);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("GetRandomLabelsTwo","children",q);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("GetRandomLabelsTwo","numberOfLabels",1)},implementation:{pa:d}}};I("PENGO.client.shared.runEngine.two.actuators.getAbsolutePosition");
window.PENGO.client.shared.runEngine.two.actuators.getAbsolutePosition.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"GetAbsolutePositionTwo"),c,f;a.createInParam("target",0);a.createOutParam("position",0);a.createInput("get",0,function(b){if((c=a.inParameters.target)&&a.outParameters.position)y.set(0,0),c.dirtyTransform&&(f=c._parent?c._parent.finalTransform:l,c._updateObject2d(0,0,f,1,q)),c.finalTransform.transformVector2(y),a.outParameters.position.x=y.x,a.outParameters.position.y=
y.y,a.fireOutput(0,b)});a.createOutput("done",0);var y=new window.TWO.core.math.Vector2;return a}var k;return{dependencies:function(b){k=b;k.runEngine.blackboxRepository.addBlackboxType("GetAbsolutePositionTwo",d)},implementation:{ka:d}}};I("PENGO.client.shared.runEngine.two.actuators.getName");
window.PENGO.client.shared.runEngine.two.actuators.getName.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"GetNameTwo");a.createInParam("target",0);a.createOutParam("name",0);a.createInput("get",0,function(b){a.inParameters.target&&("string"==typeof a.outParameters.name&&(a.outParameters.name=a.inParameters.target.name),a.fireOutput(0,b))});a.createOutput("done",0);return a}var k;return{dependencies:function(b){k=b;k.runEngine.blackboxRepository.addBlackboxType("GetNameTwo",
d)},implementation:{na:d}}};I("PENGO.client.shared.runEngine.two.actuators.spriteText");
window.PENGO.client.shared.runEngine.two.actuators.spriteText.resolve=function(){function d(b,a){b.anchor=a.A;b["text alignment"]=a.TA===l?"left":a.TA;b["max width"]=a.M;b["clear before"]=a.C===l?n:a.C}function k(){}function b(b,a,c,f){var d=new e.runEngine.Blackbox(b,a,c,f,"SpriteTextTWO");d.createInParam("sprite text",0);d.createInParam("text",1);d.createInParam("parent",2);var k=d.createOutput("done",0),E=d.createOutput("failed",1),C=e.runEngine.getManager();d.createInput("create",0,function(a){function b(a){var c=
{x:0,y:0};A[a].width!==B&&("center"==P?c.x=0.5*(B-A[a].width):"right"==P&&(c.x=B-A[a].width));c.y=a*f.h;"CENTER"==w[0]?c.y-=0.5*A.length*f.h:"BOTTOM"==w[0]&&(c.y-=A.length*f.h);w[1]==l||"CENTER"==w[1]?c.x-=0.5*B:"RIGHT"==w[1]&&(c.x-=B);return c}function c(a){for(var b,m,e=0,h=0;e<a.length&&!v;)b=a[e],b=r(b),m=f.spriteDef.animations[b],m!==l?h+=m.frameWidth:(h+=20,console.warn('Character "'+b+'" not found in spriteDef')),e++;return v===n?-1:h}function h(b,c,m){b=A[b].text;for(var h,e,s={},k=0;k<b.length;k++)if(C.l(f,
d.inParameters,s,a,C))h=b[k],h=r(h),e=s.clone,e.x=c,e.y=m,e.scaleX=e.scaleY=1,e.rotation=0,e.visible=n,e.alpha=1,e.anchorType="TOP_LEFT",f.spriteDef.animations[h]!==l?e.startAnimation(h):(e._w=20,e._h=0!==Object.keys(f.spriteDef.animations).length?f.spriteDef.animations[Object.keys(f.spriteDef.animations)[0]].frameHeight:20,e._image=l),c+=e.currentAnimation.frameWidth;else{console.warn("Clone failed for character for spriteFont");break}}var f=d.inParameters["sprite text"],e=d.inParameters.text,s=
d.inParameters.parent,v=q,w=d.anchor.split("_"),H=0,P=d["text alignment"],A=[],O,L,K,N,B=0,F;if(f&&f.spriteDef!==l&&s&&e!==l){F=f.spriteDef.animations.space?f.spriteDef.animations.space.frameWidth:20;e+="";H=d["max width"];if(0===H)B=c(e),A.push({text:e,width:B});else if(F!==l){O=e.split(" ");L="";for(e=K=0;e<O.length&&!v;)N=c(O[e]),-1!==N?K+N+F<H?(K+=N,0<L.length&&(L+=" ",K+=F),L+=O[e],e++):0!==K?(A.push({text:L,width:K}),B<K&&(B=K),L="",K=0):(A.push({text:O[e],width:N}),B<H&&(B=H),e++):v=n;!v&&
""!=L&&(A.push({text:L,width:K}),B<K&&(B=K))}else v=n,console.warn('Character "space" must be defined for multiline texts');if(!v){if(d["clear before"]===n)for(;0<s.children.length;)C.z(s.children[0],l,l,a,C);for(e=0;e<A.length;e++)s=b(e),h(e,s.x,s.y)}}else v=n;v?d.fireOutput(E,a):d.fireOutput(k,a)});return d}function r(b){var a=b;"."===b?a="point":" "===b?a="space":"$"===b?a="dollar":"%"===b?a="percentile":"'"===b&&(a="apostrophe");return a}var e;return{dependencies:function(r){r.runEngine.blackboxRepository.addBlackboxType("SpriteTextTWO",
b);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SpriteTextTWO",k,d);e=r},implementation:{ya:b}}};I("PENGO.client.shared.runEngine.two.actuators.text");
window.PENGO.client.shared.runEngine.two.actuators.text.resolve=function(){function d(b,e){b.font=e.F;b.fontSize=e.FS;b.RComponent=e.R;b.GComponent=e.G;b.BComponent=e.B;b.borderWidth=e.BW;b.BRComponent=e.BR;b.BGComponent=e.BG;b.BBComponent=e.BB}function k(d,e,k,a){var c=new b.runEngine.Blackbox(d,e,k,a,"TextCreatorTwo");c.createInParam("text",0);c.createInParam("parent",1);c.createInParam("position",2);c.font=l;c.fontSize=l;c.RComponent=l;c.GComponent=l;c.BComponent=l;c.borderWidth=l;c.BRComponent=
l;c.BGComponent=l;c.BBComponent=l;c.createOutParam("text",0);c.createInput("do",0,function(a){if(c.inParameters.parent&&c.inParameters.text!==l){var b=new window.TWO.core.renderables.Text;c.inParameters.position!==l&&(b._x=c.inParameters.position.x,b._y=c.inParameters.position.y);c.font!==l&&(b._font=c.font);c.fontSize!==l&&(b.fontSize=c.fontSize);c.RComponent!==l&&(b._colorR=c.RComponent);c.GComponent!==l&&(b._colorG=c.GComponent);c.BComponent!==l&&(b._colorB=c.BComponent);c.borderWidth!==l&&(b._borderWidth=
c.borderWidth);c.BRComponent!==l&&(b._bColorR=c.BRComponent);c.BGComponent!==l&&(b._bColorG=c.BGComponent);c.BBComponent!==l&&(b._bColorB=c.BBComponent);b._text=""+c.inParameters.text;c.outParameters.text=b;c.inParameters.parent.appendChild(b);c.fireOutput(0,a)}});c.createOutput("done",0);return c}var b;return{dependencies:function(r){b=r;b.runEngine.blackboxRepository.addBlackboxType("TextCreatorTwo",k);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("TextCreatorTwo",l,d)},implementation:{za:k}}};I("PENGO.client.shared.runEngine.two.actuators.cloneObject2D");
window.PENGO.client.shared.runEngine.two.actuators.cloneObject2D.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"CloneTWO"),c=k.runEngine.getManager();a.createInParam("target",0);a.createInParam("parent",1);a.createOutParam("clone",0);a.createInput("do",0,function(b){a.inParameters.target&&a.inParameters.parent&&(c.l(a.inParameters.target,a.inParameters,a.outParameters,b,c),a.fireOutput(0,b))});a.createOutput("done",0);return a}var k;return{dependencies:function(b){k=
b;k.runEngine.blackboxRepository.addBlackboxType("CloneTWO",d)},implementation:{ga:d}}};I("PENGO.client.shared.runEngine.two.sensors.moveFromTo");
window.PENGO.client.shared.runEngine.two.sensors.moveFromTo.resolve=function(){function d(b,d,e,w){function a(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._scaleX=N,h._scaleY=B,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,a)):(h._scaleX+=z.x*a.event.deltaTime,h._scaleY+=z.y*a.event.deltaTime,h.setDirtyTransform())}function c(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._rotation=L,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):
p=l,m.fireOutput(1,a)):(h._rotation+=J*a.event.deltaTime,h.setDirtyTransform())}function f(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._x=P,h._y=A,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,a)):(h._x+=F.x*a.event.deltaTime,h._y+=F.y*a.event.deltaTime,h.setDirtyTransform())}function y(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._rotation=L,h._scaleX=N,h._scaleY=B,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,
a)):(h._rotation+=J*a.event.deltaTime,h._scaleX+=z.x*a.event.deltaTime,h._scaleY+=z.y*a.event.deltaTime,h.setDirtyTransform())}function D(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._x=P,h._y=A,h._scaleX=N,h._scaleY=B,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,a)):(h._x+=F.x*a.event.deltaTime,h._y+=F.y*a.event.deltaTime,h._scaleX+=z.x*a.event.deltaTime,h._scaleY+=z.y*a.event.deltaTime,h.setDirtyTransform())}function E(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),
h._x=P,h._y=A,h._rotation=L,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,a)):(h._x+=F.x*a.event.deltaTime,h._y+=F.y*a.event.deltaTime,h._rotation+=J*a.event.deltaTime,h.setDirtyTransform())}function C(a){u+=a.event.deltaTime;s<=u?(b.unsubscribeOnUpdateDraw(p),h._x=P,h._y=A,h._rotation=L,h._scaleX=N,h._scaleY=B,h.setDirtyTransform(),v?(x=t,b.callOnNextUpdateDraw(x)):p=l,m.fireOutput(1,a)):(h._x+=F.x*a.event.deltaTime,h._y+=F.y*a.event.deltaTime,h._rotation+=J*a.event.deltaTime,
h._scaleX+=z.x*a.event.deltaTime,h._scaleY+=z.y*a.event.deltaTime,h.setDirtyTransform())}function t(a){x=l;p&&(F&&(h._x=H.x,h._y=H.y),J&&(h._rotation=O),z&&(h._scaleX=K.x,h._scaleY=K.y),h.setDirtyTransform(),u=0,b.subscribeOnUpdateDraw(p),m.fireOutput(0,a))}var m=new k.runEngine.Blackbox(b,d,e,w,"MoveFromToTWO");m.createInParam("target",0);m.createInParam("seconds",1);m.createInParam("loop",2);m.createOutput("started",0);m.createOutput("arrived",1);m.createOutput("paused",2);m.createOutput("stopped",
3);var G,h,p=l,u=0,s=0,v=q,M=q,H={x:0,y:0},P=0,A=0,O=0,L=0,K={x:0,y:0},N=0,B=0,F={x:0,y:0},J=0,z={x:0,y:0},x=l;m.createInput("start",0,function(e){function d(a,b,c){a.isInParamConnected(4)&&(b._x=a.inParameters.fromPosition.x,b._y=a.inParameters.fromPosition.y);a.isInParamConnected(6)&&(b._rotation=a.inParameters.fromRotation);a.isInParamConnected(8)&&(b._scaleX=a.inParameters.fromScale.x,b._scaleY=a.inParameters.fromScale.y);b.setDirtyTransform();a.fireOutput(0,c)}function k(a,b,c){a.isInParamConnected(4)&&
(b._x=a.inParameters.toPosition.x,b._y=a.inParameters.toPosition.y);a.isInParamConnected(6)&&(b._rotation=a.inParameters.toRotation);a.isInParamConnected(8)&&(b._scaleX=a.inParameters.toScale.x,b._scaleY=a.inParameters.toScale.y);b.setDirtyTransform();a.fireOutput(0,c);a.fireOutput(1,c)}function r(){if(F&&J&&z)return C;if(F&&J)return E;if(F&&z)return D;if(J&&z)return y;if(F)return f;if(J)return c;if(z)return a}if(G=m.inParameters.target)if(p&&M&&h===G)M=q,v&&x?b.callOnNextUpdateDraw(x):b.subscribeOnUpdateDraw(p),
m.fireOutput(2,e),m.fireOutput(0,e);else if(h=G,s=m.getInParamValue(1),G!==l&&0<=s&&(m.isInParamConnected(3)&&m.isInParamConnected(4)||m.isInParamConnected(5)&&m.isInParamConnected(6)||m.isInParamConnected(7)&&m.isInParamConnected(8)))if(x&&(b.avoidCallOnNextUpdateDraw(x),x=l),p&&(b.unsubscribeOnUpdateDraw(p),p=l),u=0,M=q,0===s)k(m,h,e);else if(v=m.inParameters.loop===n,s*=1E3,m.isInParamConnected(3)?(H.x=m.inParameters.fromPosition.x,H.y=m.inParameters.fromPosition.y,P=m.inParameters.toPosition.x,
A=m.inParameters.toPosition.y,F={x:(P-H.x)/s,y:(A-H.y)/s}):F=l,m.isInParamConnected(5)?(O=m.inParameters.fromRotation,L=m.inParameters.toRotation,J=(L-O)/s):J=l,m.isInParamConnected(7)?(K.x=m.inParameters.fromScale.x,K.y=m.inParameters.fromScale.y,N=m.inParameters.toScale.x,B=m.inParameters.toScale.y,z={x:(N-K.x)/s,y:(B-K.y)/s}):z=l,F&&(0!==F.x||0!==F.y)||J||z&&(0!==z.x||0!==z.y)){if(p=r())b.subscribeOnUpdateDraw(p),d(m,h,e)}else k(m,h,e)});m.createInput("pause",1,function(a){p&&(M?(M=q,v&&x?b.callOnNextUpdateDraw(x):
b.subscribeOnUpdateDraw(p)):(M=n,v&&x?b.avoidCallOnNextUpdateDraw(x):b.unsubscribeOnUpdateDraw(p)),m.fireOutput(2,a))});m.createInput("stop",2,function(a){p&&(x&&(b.avoidCallOnNextUpdateDraw(x),x=l),b.unsubscribeOnUpdateDraw(p),p=l,m.fireOutput(3,a))});return m}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("MoveFromToTWO",d);b.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("MoveFromToTWO","timeToMove",1);b.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("MoveFromToTWO",
"seconds",1);b.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("MoveFromToTWO","loop",q);k=b},implementation:{ra:d}}};I("PENGO.client.shared.runEngine.two.sensors.spriteAnimate");
window.PENGO.client.shared.runEngine.two.sensors.spriteAnimate.resolve=function(){function d(b,d){b.animation=d.A}function k(b){b.inParameters.target&&b.inParameters.target.stopAnimation()}function b(b,d,a,c){var f=new r.runEngine.Blackbox(b,d,a,c,"AnimSpriteTWO");f.createInParam("target",0);f.createInParam("loop",1);f.createInParam("fps",2);f.createInParam("revert",3);f.animation=l;var k=f.createOutput("started",0),D=f.createOutput("stopped",1),E=f.createOutput("paused",2),C=f.createOutput("finished",
3);f.createInput("start",0,function(a){var c=f.inParameters.target;c&&(c.startAnimation(f.animation,f.inParameters.fps,f.inParameters.revert,f.inParameters.loop,function(){b.callOnNextUpdateDraw(function(a){f.fireOutput(C,a)})}),f.fireOutput(k,a))});f.createInput("stop",1,function(a){f.inParameters.target&&(f.inParameters.target.stopAnimation(),f.fireOutput(D,a))});f.createInput("pause",2,function(a){f.inParameters.target&&(f.inParameters.target.paused=!f.inParameters.target.paused,f.fireOutput(E,
a))});return f}var r;return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("AnimSpriteTWO",b);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("AnimSpriteTWO",k,d);r=e},implementation:{va:b}}};I("PENGO.client.shared.runEngine.two.actuators.setTransform");
window.PENGO.client.shared.runEngine.two.actuators.setTransform.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"SetTransformTWO");a.createInParam("target",0);a.createOutput("done",0);a.createInput("set",0,function(b){a.inParameters.target&&(a.inParameters.position&&(a.inParameters.target._x=a.inParameters.position.x,a.inParameters.target._y=a.inParameters.position.y),a.inParameters.rotation!==l&&(a.inParameters.target._rotation=a.inParameters.rotation),a.inParameters.scale&&
(a.inParameters.target._scaleX=a.inParameters.scale.x,a.inParameters.target._scaleY=a.inParameters.scale.y),a.inParameters.target.setDirtyTransform(),a.fireOutput(0,b))});return a}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("SetTransformTWO",d);k=b},implementation:{ua:d}}};I("PENGO.client.shared.runEngine.two.actuators.picking");
window.PENGO.client.shared.runEngine.two.actuators.picking.resolve=function(){function d(d,e,k,a){var c=new b.runEngine.Blackbox(d,e,k,a,"PickTwo"),f=b.runEngine.getManager(),y=f.a;c.createInParam("pickPosition",0);c.createInParam("pixelPerfect",1);c.createInParam("radius",2);c.createOutParam("pickedObjects",0);c.createOutParam("numberOfObjects",1);var D=[],E=[],C=n;c.updateInParamsKeyList=function(a){a?(C=n,D.length=0,E=c.getInParams(),E.splice(0,3)):(C=q,D.length=0,E.length=0)};c.createOutput("true",
0);c.createOutput("false",1);c.createInput("test",0,function(a){var b,e,d,k=c.getInParamValue(3);if(d=c.getInParamValue(0)){if(C){k=[];for(b=D.length=0;b<E.length;b++)if(e=c.inParameters[E[b].nameKey])k.push(e),D.push(E[b].index)}b={numObjs:l,pixelPerfect:c.getInParamValue(1),radius:l};Array.isArray(c.getOutParamValue(0))||(b.numObjs=1);b.pixelPerfect||(b.radius=c.getInParamValue(2));if((d=y.getIntersectingObjects(d.x,d.y,k,b,n))&&0<d.length){c.isOutParamConnected(0)&&(f.k(d,c.getOutParamType(0)),
c.outParameters.pickedObjects=1===b.numObjs?d[0]:d);c.outParameters.numberOfObjects=d.length;if(C)for(b=0;b<d.length;b++)e=k.indexOf(d[b]),-1!=e&&c.fireOutput(D[e]-1,a);c.fireOutput(0,a)}else 1===b.numObjs?c.outParameters.pickedObjects=l:c.outParameters.pickedObjects.length=0,c.outParameters.numberOfObjects=0,c.fireOutput(1,a)}});return c}function k(b,d){switch(d.C){case 0:b.updateInParamsKeyList(q);break;case 1:b.updateInParamsKeyList(q);break;case 2:b.updateInParamsKeyList(n);break;default:b.updateInParamsKeyList(q)}}
var b;return{dependencies:function(r){r.runEngine.blackboxRepository.addBlackboxType("PickTwo",d);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("PickTwo",l,k);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("PickTwo","pixelPerfect",n);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("PickTwo","radius",0);b=r},implementation:{sa:d}}};I("PENGO.client.shared.runEngine.two.sensors.spritePanel");
window.PENGO.client.shared.runEngine.two.sensors.spritePanel.resolve=function(){function d(b){b.inParameters.target&&(b.inParameters.target.stopAnimation(),b.freeSpritePanel())}function k(b,d){b.normalAnimation=d.N;b.overAnimation=d.O;b.pressedAnimation=d.P;b.disabledAnimation=d.D}function b(b,d,a,c){function f(a){if((a=a||window.event)&&a.touches){R||(s.removeEventListener("mousedown",C,q),s.removeEventListener("mouseup",J,q),s.removeEventListener("mousemove",G,q),R=n);x=q;for(z=0;z<a.touches.length&&
!x;z+=1)x=t(a.touches[z]);x?(M||m(n),C({button:0})):M&&m(q)}}function k(a){if((a=a||window.event)&&a.touches){x=q;for(z=0;z<a.touches.length&&!x;z+=1)x=t(a.touches[z]);if(M&&(!x||0===a.touches.length))H&&(s.removeEventListener("mouseup",J,q),H=q,v&&h(v,p.normalAnimation),b.callOnNextUpdateDraw(N),A++),s.addEventListener("mousedown",C,q),s.addEventListener("mousemove",G,q),R=q}}function D(a){E(a);a&&(a.touches&&0===a.touches.length)&&(s.addEventListener("mousedown",C,q),s.addEventListener("mousemove",
G,q),R=q)}function E(a){if((a=a||window.event)&&a.touches){x=q;for(z=0;z<a.touches.length&&!x;z+=1)x=t(a.touches[z]);x?M||m(n):M&&m(q)}}function C(a){a=a||window.event;"mousedown"===a.type&&(M=t(a));!H&&(M&&0===a.button)&&(H=n,v&&h(v,p.pressedAnimation),b.callOnNextUpdateDraw(K),P++,s.addEventListener("mouseup",J,q))}function t(a){var b,c;if(v){c=b=0;var d=u.renderMgr._scaleX||1,h=u.renderMgr._scaleY||1;if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+
document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;var e=a.target,m=0;a=0;for(var f=e.clientWidth,k=e.clientHeight;null!=e;)m+=e.offsetLeft+e.clientLeft,a+=e.offsetTop+e.clientTop,e=e.offsetParent;b=u.renderMgr.initialWidth*(b-m)/(f*d);c=u.renderMgr.initialHeight*(c-a)/(k*h);return 0<u.getIntersectingObjects(b,c,[v],{pixelPerfect:p.inParameters.pixelPerfect}).length}return q}function m(a){(M=a)?(h(v,p.overAnimation),b.callOnNextUpdateDraw(B),
O++):(h(v,p.normalAnimation),b.callOnNextUpdateDraw(F),L++,H&&(s.removeEventListener("mouseup",J,q),H=q))}function G(a){a=a||window.event;if(v){var c=M;M=t(a);c!=M&&(M?(h(v,p.overAnimation),b.callOnNextUpdateDraw(B),O++):(h(v,p.normalAnimation),b.callOnNextUpdateDraw(F),L++,H&&(s.removeEventListener("mouseup",J,q),H=q)))}}function h(a,b){b!=l&&a.startAnimation(b)}var p=new r.runEngine.Blackbox(b,d,a,c,"SpritePanelTWO"),u=r.runEngine.getManager().a,s=b.getContainer();p.createInParam("target",0);p.createInParam("pixelPerfect",
1);p.normalAnimation=l;p.overAnimation=l;p.pressedAnimation=l;p.disabledAnimation=l;p.createOutput("down",0);p.createOutput("up",1);p.createOutput("enter",2);p.createOutput("exit",3);var v=l,M=q,H=q,P=0,A=0,O=0,L=0,K=function T(a){P--;0<P&&b.callOnThisUpdateDraw(T);p.fireOutput(0,a)},N=function U(a){A--;0<A&&b.callOnThisUpdateDraw(U);p.fireOutput(1,a)},B=function V(a){O--;0<O&&b.callOnThisUpdateDraw(V);p.fireOutput(2,a)},F=function W(a){L--;0<L&&b.callOnThisUpdateDraw(W);p.fireOutput(3,a)},J=function X(a){a=
a||window.event;H&&0===a.button&&(s.removeEventListener("mouseup",X,q),H=q,v&&h(v,p.overAnimation),b.callOnNextUpdateDraw(N),A++,s.addEventListener("mousedown",C,q),s.addEventListener("mousemove",G,q))},z,x=q,R=q;p.freeSpritePanel=function(){v=l;H=q;s.removeEventListener("mousedown",C,q);s.removeEventListener("mouseup",J,q);s.removeEventListener("mousemove",G,q);s.removeEventListener("touchstart",f,q);s.removeEventListener("touchend",k,q);s.removeEventListener("touchcancel",D,q);s.removeEventListener("touchmove",
E,q)};p.createInput("activate",0,function(){v||(v=p.inParameters.target);v&&(h(v,p.normalAnimation),s.addEventListener("mousedown",C,q),s.addEventListener("mousemove",G,q),s.addEventListener("touchstart",f,q),s.addEventListener("touchend",k,q),s.addEventListener("touchcancel",D,q),s.addEventListener("touchmove",E,q))});p.createInput("disable",1,function(){v||(v=p.inParameters.target);v&&(h(v,p.disabledAnimation),p.freeSpritePanel())});return p}var r;return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("SpritePanelTWO",
b);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SpritePanelTWO",d,k);e.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SpritePanelTWO","pixelPerfect",q);r=e},implementation:{xa:b}}};I("PENGO.client.shared.runEngine.two.actuators.transform");
window.PENGO.client.shared.runEngine.two.actuators.transform.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"TransformTWO");a.createInParam("target",0);a.createOutput("done",0);a.createInput("do",0,function(b){a.inParameters.target&&(a.inParameters.translation&&(a.inParameters.target._x+=a.inParameters.translation.x,a.inParameters.target._y+=a.inParameters.translation.y,a.outParameters.positionResult&&(a.outParameters.positionResult={x:a.inParameters.target._x,y:a.inParameters.target._y})),
a.inParameters.rotation!==l&&(a.inParameters.target._rotation+=a.inParameters.rotation,a.outParameters.rotationResult!=l&&(a.outParameters.rotationResult=a.inParameters.target._rotation)),a.inParameters.scale&&(a.inParameters.target._scaleX*=a.inParameters.scale.x,a.inParameters.target._scaleY*=a.inParameters.scale.y,a.outParameters.scaleResult&&(a.outParameters.scaleResult={x:a.inParameters.target._scaleX,y:a.inParameters.target._scaleY})),a.inParameters.target.setDirtyTransform(),a.fireOutput(0,
b))});return a}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("TransformTWO",d);k=b},implementation:{Aa:d}}};I("PENGO.client.shared.runEngine.two.actuators.move");
window.PENGO.client.shared.runEngine.two.actuators.move.resolve=function(){function d(b,d,e,w){function a(a){m._scaleX+=u.x*a.event.deltaTime;m._scaleY+=u.y*a.event.deltaTime;m.setDirtyTransform()}function c(a){m._rotation+=p*a.event.deltaTime;m.setDirtyTransform()}function f(a){m._x+=h.x*a.event.deltaTime;m._y+=h.y*a.event.deltaTime;m.setDirtyTransform()}function y(a){m._rotation+=p*a.event.deltaTime;m._scaleX+=u.x*a.event.deltaTime;m._scaleY+=u.y*a.event.deltaTime;m.setDirtyTransform()}function D(a){m._x+=
h.x*a.event.deltaTime;m._y+=h.y*a.event.deltaTime;m._scaleX+=u.x*a.event.deltaTime;m._scaleY+=u.y*a.event.deltaTime;m.setDirtyTransform()}function E(a){m._x+=h.x*a.event.deltaTime;m._y+=h.y*a.event.deltaTime;m._rotation+=p*a.event.deltaTime;m.setDirtyTransform()}function C(a){m._x+=h.x*a.event.deltaTime;m._y+=h.y*a.event.deltaTime;m._rotation+=p*a.event.deltaTime;m._scaleX+=u.x*a.event.deltaTime;m._scaleY+=u.y*a.event.deltaTime;m.setDirtyTransform()}var t=new k.runEngine.Blackbox(b,d,e,w,"MoveTWO");
t.createInParam("target",0);t.createOutput("started",0);t.createOutput("stopped",1);var m,G=l,h={x:0,y:0},p=0,u={x:0,y:0};t.createInput("start",0,function(d){function e(){if(h&&p&&u)return C;if(h&&p)return E;if(h&&u)return D;if(p&&u)return y;if(h)return f;if(p)return c;if(u)return a}m=t.inParameters.target;if(m!==l&&(t.isInParamConnected(1)||t.isInParamConnected(2)||t.isInParamConnected(3)))if(G&&(b.unsubscribeOnUpdateDraw(G),G=l),h=t.isInParamConnected(1)?{x:t.inParameters.translatePerSecond.x/1E3,
y:t.inParameters.translatePerSecond.y/1E3}:l,p=t.isInParamConnected(2)?t.inParameters.rotatePerSecond/1E3:l,u=t.isInParamConnected(3)?{x:t.inParameters.scalePerSecond.x/1E3,y:t.inParameters.scalePerSecond.y/1E3}:l,h&&(0!==h.x||0!==h.y)||p||u&&(0!==u.x||0!==u.y))if(G=e())b.subscribeOnUpdateDraw(G),t.fireOutput(0,d)});t.createInput("stop",1,function(a){G&&(b.unsubscribeOnUpdateDraw(G),G=l,t.fireOutput(1,a))});return t}var k;return{dependencies:function(b){b.runEngine.blackboxRepository.addBlackboxType("MoveTWO",
d);k=b},implementation:{qa:d}}};I("PENGO.client.shared.runEngine.two.actuators.getChildren");
window.PENGO.client.shared.runEngine.two.actuators.getChildren.resolve=function(){function d(b,d,e,w){var a=new k.runEngine.Blackbox(b,d,e,w,"GetChildrenTwo");a.createInParam("target",0);a.createOutParam("children",0);a.createOutParam("childNumber",1);a.createInput("get",0,function(b){if(a.inParameters.target&&a.outParameters.children){var d=a.inParameters.target.children.slice();k.runEngine.getManager().k(d,a.getOutParamType(0));a.outParameters.children=d;a.outParameters.childNumber=d.length;a.fireOutput(0,
b)}});a.createOutput("done",0);return a}var k;return{dependencies:function(b){k=b;k.runEngine.blackboxRepository.addBlackboxType("GetChildrenTwo",d)},implementation:{la:d}}};I("PENGO.client.shared.runEngine.two.actuators.getLabels");
window.PENGO.client.shared.runEngine.two.actuators.getLabels.resolve=function(){function d(d,e,k,a){var c=new b.runEngine.Blackbox(d,e,k,a,"GetLabelsTwo"),f=b.runEngine.getManager(),y=l;c.setProdideResultMode=function(a){function b(a){function d(a){this.push(a)}var e=c.getOutParamValue(0);e&&a.length&&a.forEach(d,e)}function d(a){c.setOutParamValue(0,a)}y=a?d:b};c.setProdideResultMode(n);c.createInParam("target",0);c.createInParam("children",1);c.createOutParam("labels",0);c.createOutParam("numberOfLabels",
1);c.createInput("do",0,function(a){var b;c.inParameters.target&&(b=f.L(c.inParameters.target,c.inParameters.children),y(b),c.outParameters.numberOfLabels=b.length,c.fireOutput(0,a))});c.createOutput("done",0);return c}function k(b,d){d&&d.A?b.setProdideResultMode(q):b.setProdideResultMode(n)}var b;return{dependencies:function(r){b=r;b.runEngine.blackboxRepository.addBlackboxType("GetLabelsTwo",d);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("GetLabelsTwo",l,k);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("GetLabelsTwo",
"children",q)},implementation:{ma:d}}};I("PENGO.client.shared.runEngine.two.manager");
window.PENGO.client.shared.runEngine.two.manager.resolve=function(){function d(g,a,b,c,d,e,h){function m(g){k.a.updateAndDraw(g.event.time,g.event.Ca)}var f={};this.n=g;this.j=h;this.Da=a;this.m=document.createElement("div");this.m.name="TWO_Render_Div_"+a;this.m.id="TWO_Layer_Div_"+a;this.m.setAttribute("style","position: absolute; width: 100%; height: 100%; top: 0px; left: 0px;");c.appendChild(this.m);f.container=this.m;this.U=f.width=d;this.T=f.height=e;f.maxBatchSize=32;this.a=new window.TWO.Engine(f);
this.i={};this.ea=this.a.viewport=new window.TWO.core.math.Rect(0,0,f.width||c.innerWidth,f.height||c.innerHeight);this.p=b;this.v=Q.resourceManager.getTypes().VIEW;this.u=Q.resourceManager.getTypes().LAYER;this.w=Q.resourceManager.getTypes().SPRITE;var k=this;b.registerAssetType({type:[this.v,this.u,this.w],callbacks:{load:function(g,a,b,ha){k.ba(g,a,b,ha)},get:function(g,a){return k.$(g,a)},unload:function(g){return function(a){switch(g){case k.v:k.s(a,l,l,l,k);break;case k.u:k.a.resourceMgr.removeResource("layer",
a.id);break;case k.w:k.a.resourceMgr.removeResource("spriteDef",a.id)}k.i[a.id]&&delete k.i[a.id]}}}});k.getDrawCallback=function(){return m};this.d={};this.e={};this.f={};this.Q=function(){}}function k(g,a){g.name=a.name;g._rotation=0;g._scaleX=1;g._scaleY=1;g._x=0;g._y=0;g.snapToPixel=n;g._visible=n;g._alpha=1;g._anchor.set(0.5,0.5);g._anchorType="CENTER";g._customAnchor=q;g._rotation=a.rotation==l?0:a.rotation;a.scale&&(g._scaleX=a.scale[0],g._scaleY=a.scale[1]);a.position&&(g._x=a.position[0],
g._y=a.position[1]);g.snapToPixel=a.snapToPixel==l?n:a.snapToPixel;g._visible=a.visible==l?n:a.visible;g._alpha=a.alpha==l?1:a.alpha;a.anchor&&(g.anchorType=a.anchor.type,a.anchor.value&&(g.anchor=a.anchor.value));g.dirty=n;g.dirtyTransform=n}function b(g){g.position={};g.scale={};g.pivot={};Object.defineProperty(g.position,"x",{get:function(){return g._x},set:function(a){g._x=a;g.setDirtyTransform()},enumerable:n,configurable:n});Object.defineProperty(g.position,"y",{get:function(){return g._y},
set:function(a){g._y=a;g.setDirtyTransform()},enumerable:n,configurable:n});Object.defineProperty(g.scale,"x",{get:function(){return g._scaleX},set:function(a){g._scaleX=a;g.setDirtyTransform()},enumerable:n,configurable:n});Object.defineProperty(g.scale,"y",{get:function(){return g._scaleY},set:function(a){g._scaleY=a;g.setDirtyTransform()},enumerable:n,configurable:n});Object.defineProperty(g.pivot,"x",{get:function(){return g._pivotX},set:function(a){g._pivotX=a;g.setDirtyTransform()},enumerable:n,
configurable:n});Object.defineProperty(g.pivot,"y",{get:function(){return g._pivotY},set:function(a){g._pivotY=a;g.setDirtyTransform()},enumerable:n,configurable:n})}function r(g){Object.defineProperty(g,"animation",{get:function(){return g.currentAnimationName},set:function(){},enumerable:n,configurable:n});Object.defineProperty(g,"animations",{get:function(){var a=[],b;for(b in g.spriteDef.animations)a.push(b);return a},set:function(){},enumerable:n,configurable:n})}function e(g,a,b,c,d){var e,
h,m,k,f=b["object(s)"],p=a.name;if(p!==l){p=p.toString();k=Array.isArray(f);a=a.asSubString;m=c.getOutParamType(0);k?f.length=0:f=[];for(c=0;c<g.layers.length;c++)if(h=g.layers[c],"LayerTwo"==m)(a&&-1!=h.name.indexOf(p)||h.name==p)&&f.push(h);else for(e=0;e<h.children.length;e++)d.I(h.children[e],p,f,a);m&&Q.runEngine.getManager().k(f,m);b.numberOfObjects=f.length;!k&&0<f.length&&(b["object(s)"]=f[0]);return n}return q}function w(g,a,b){var c=b.layers;if(c){for(a=c.length=0;a<g.layers.length;a++)g.layers[a]&&
c.push(g.layers[a]);b.numberOfLayers=c.length;return n}return q}function a(g,a,b,c,d){var e,f=b["object(s)"],h=a.name;return h!==l?(h=h.toString(),e=Array.isArray(f),c=c.getOutParamType(0),a=a.asSubString,e?f.length=0:f=[],d.I(g,h,f,a,q),c&&Q.runEngine.getManager().k(f,c),b.numberOfObjects=f.length,!e&&0<f.length&&(b["object(s)"]=f[0]),n):q}function c(g,a){if(a.parent!==l){if(g._parent){var b=g._parent.children.indexOf(g);-1<b&&g._parent.children.splice(b,1)}g._ownerLayer&&(g._ownerLayer.dirty=n);
a.parent.appendChild(g);g._updateObject2d(0,0,a.parent.finalTransform,1,q);g._dirtyTransform=q;return g._dirty=n}return q}function f(g,a,b){return b.transparency!==l?(b.transparency=g._alpha,n):q}function y(g,a){return a.transparency!==l?(g._alpha=a.transparency,n):q}function D(g,a,b){return b.visibility!==l?(b.visibility=g._visible,n):q}function E(g,a){return a.visibility!==l?(g._visible=a.visibility==n,g.dirty=n):q}function C(g,a,b,c,d){return b.children!==l?(g=g.children.slice(),d.k(g,c.getOutParamType(0)),
b.children=g,b.childNumber=g.length,n):q}function t(g,a,b){return b.name!==l&&"string"===typeof b.name?(b.name=g.name,n):q}function m(g,a,b,c,d){return d.J(g._parent.type,c.getOutParamType(0))?(b.parent=g._parent,n):q}function G(g,a,b){return b.position!==l?(a=new window.TWO.core.math.Vector2(0,0),g.finalTransform.transformVector2(a),b.position={x:a.x,y:a.y},n):q}function h(g,a,b){return b.position!==l?(b.position={x:g._x,y:g._y},n):q}function p(g,a,b){return b["X position"]!==l&&b["Y position"]!==
l?(b["X position"]=g._x,b["Y position"]=g._y,n):q}function u(g,a,b){return b["X position"]!==l?(b["X position"]=g._x,n):q}function s(g,a,b){return b["Y position"]!==l?(b["Y position"]=g._y,n):q}function v(g,a,b){return b.scale!==l?(b.scale={x:g._scaleX,y:g._scaleY},n):q}function M(g,a,b){return b.rotation!==l?(b.rotation=g._rotation,n):q}function H(g,a){return a.position!==l?(g._x=a.position.x,g._y=a.position.y,g.setDirtyTransform(),n):q}function P(g,a){return a["X position"]!==l&&a["Y position"]!==
l?(g._x=a["X position"],g._y=a["Y position"],g.setDirtyTransform(),n):q}function A(g,a){return a["X position"]!==l?(g._x=a["X position"],g.setDirtyTransform(),n):q}function O(g,a){return a["Y position"]!==l?(g._y=a["Y position"],g.setDirtyTransform(),n):q}function L(g,a){return a.scale!==l?(g._scaleX=a.scale.x,g._scaleY=a.scale.y,g.setDirtyTransform(),n):q}function K(g,a){return a.rotation!==l?(g._rotation=a.rotation,g.setDirtyTransform(),n):q}function N(g,a,b){return a.translation!==l?(g._x+=a.translation.x,
g._y+=a.translation.y,b.positionResult!==l&&(b.positionResult={x:g._x,y:g._y}),g.setDirtyTransform(),n):q}function B(g,a,b){return a["X translation"]!==l&&a["Y translation"]!==l?(g._x+=a["X translation"],g._y+=a["Y translation"],b["X result"]!==l&&(b["X result"]=g._x),b["Y result"]!==l&&(b["Y result"]=g._y),g.setDirtyTransform(),n):q}function F(g,a,b){return a["X translation"]!==l?(g._x+=a["X translation"],b["X result"]!==l&&(b["X result"]=g._x),g.setDirtyTransform(),n):q}function J(g,a,b){return a["Y translation"]!==
l?(g._y+=a["Y translation"],b["Y result"]!==l&&(b["Y result"]=g._y),g.setDirtyTransform(),n):q}function z(g,a,b,c,d){return b.speed!==l?(b.speed=d.d[g.id]?{x:d.d[g.id].speed.x,y:d.d[g.id].speed.y}:{x:0,y:0},n):q}function x(g,a,b,c,d){function e(a){f>a.event.time?(g._x+=h*a.event.deltaTime,g._y+=m*a.event.deltaTime,g.setDirtyTransform()):(c.runner.unsubscribeOnUpdateAnimation(d.d[g.id].c),delete d.d[g.id])}var f,h=0,m=0;b=a.seconds;(b===l||0<b)&&a.translatePerSecond!==l&&(0!==a.translatePerSecond.x||
0!==a.translatePerSecond.y)?(f=b===l?Number.MAX_VALUE:c.event.time+1E3*b,h=a.translatePerSecond.x/1E3,m=a.translatePerSecond.y/1E3,d.d[g.id]?c.runner.unsubscribeOnUpdateAnimation(d.d[g.id].c):d.d[g.id]={},d.d[g.id].c=e,d.d[g.id].speed={x:a.translatePerSecond.x,y:a.translatePerSecond.y},d.d[g.id].o=f,c.runner.subscribeOnUpdateAnimation(d.d[g.id].c)):d.d[g.id]&&(c.runner.unsubscribeOnUpdateAnimation(d.d[g.id].c),delete d.d[g.id]);return n}function R(a,b,c,d,e){return c.speed!==l?(c.speed=e.e[a.id]?
e.e[a.id].speed:0,n):q}function da(a,b,c,d,e){function f(b){h>b.event.time?(a._rotation+=m*b.event.deltaTime,a.setDirtyTransform()):(d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),delete e.e[a.id])}var h,m=0;c=b.seconds;(c===l||0<c)&&b.rotatePerSecond!==l&&0!==b.rotatePerSecond?(h=c===l?Number.MAX_VALUE:d.event.time+1E3*c,m=b.rotatePerSecond/1E3,e.e[a.id]?d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c):e.e[a.id]={},e.e[a.id].c=f,e.e[a.id].speed=b.rotatePerSecond,e.e[a.id].o=h,d.runner.subscribeOnUpdateAnimation(e.e[a.id].c)):
e.e[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),delete e.e[a.id]);return n}function T(a,b,c,d,e){return c.speed!==l?(c.speed=e.f[a.id]?{x:e.f[a.id].speed.x,y:e.f[a.id].speed.y}:{x:0,y:0},n):q}function U(a,b,c,d,e){function f(b){h>b.event.time?(a._scaleX+=m*b.event.deltaTime,a._scaleY+=k*b.event.deltaTime,a.setDirtyTransform()):(d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c),delete e.f[a.id])}var h,m=0,k=0;c=b.seconds;(c===l||0<c)&&b.scalePerSecond!==l&&(0!==b.scalePerSecond.x||
0!==b.scalePerSecond.y)?(h=c===l?Number.MAX_VALUE:d.event.time+1E3*c,m=b.scalePerSecond.x/1E3,k=b.scalePerSecond.y/1E3,e.f[a.id]?d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c):e.f[a.id]={},e.f[a.id].c=f,e.f[a.id].speed={x:b.scalePerSecond.x,y:b.scalePerSecond.y},e.f[a.id].o=h,d.runner.subscribeOnUpdateAnimation(e.f[a.id].c)):e.f[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c),delete e.f[a.id]);return n}function V(a,b,c,d,e){function f(b){h>b.event.time?(a._x+=m*b.event.deltaTime,a._y+=
k*b.event.deltaTime):(a._x=p,a._y=s,d.runner.unsubscribeOnUpdateAnimation(e.d[a.id].c),delete e.d[a.id]);a.setDirtyTransform()}var h,m=0,k=0,p=0,s=0;c=b.seconds;b.endPosition!==l?(p=b.endPosition.x,s=b.endPosition.y,0<c&&(p!==a._x||s!==a._y)?(h=1E3*c,m=(p-a._x)/h,k=(s-a._y)/h,h+=d.event.time,e.d[a.id]?d.runner.unsubscribeOnUpdateAnimation(e.d[a.id].c):e.d[a.id]={},e.d[a.id].c=f,e.d[a.id].speed={x:1E3*m,y:1E3*k},e.d[a.id].o=h,d.runner.subscribeOnUpdateAnimation(e.d[a.id].c)):(e.d[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.d[a.id].c),
delete e.d[a.id]),a._x=p,a._y=s,a.setDirtyTransform())):e.d[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.d[a.id].c),delete e.d[a.id]);return n}function W(a,b,c,d,e){function h(b){f>b.event.time?a._rotation+=m*b.event.deltaTime:(a._rotation=k,d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),delete e.e[a.id]);a.setDirtyTransform()}var f,m=0,k=b.endRotation;b=b.seconds;k!==l?0<b&&k!==a._rotation?(f=1E3*b,m=(k-a._rotation)/f,f+=d.event.time,e.e[a.id]?(d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),
d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c)):e.e[a.id]={},e.e[a.id].c=h,e.e[a.id].speed=1E3*m,e.e[a.id].o=f,d.runner.subscribeOnUpdateAnimation(e.e[a.id].c)):(e.e[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),delete e.e[a.id]),a._rotation=k,a.setDirtyTransform()):e.e[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.e[a.id].c),delete e.e[a.id]);return n}function X(a,b,c,d,e){function f(b){h>b.event.time?(a._scaleX+=m*b.event.deltaTime,a._scaleY+=k*b.event.deltaTime):(a._scaleX=p,
a._scaleY=s,d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c),delete e.f[a.id]);a.setDirtyTransform()}var h,m=0,k=0,p=0,s=0;c=b.seconds;b.endScale!==l?(p=b.endScale.x,s=b.endScale.y,0<c&&(p!==a._scaleX||s!==a._scaleY)?(h=1E3*c,m=(p-a._scaleX)/h,k=(s-a._scaleY)/h,h+=d.event.time,e.f[a.id]?d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c):e.f[a.id]={},e.f[a.id].c=f,e.f[a.id].speed={x:1E3*m,y:1E3*k},e.f[a.id].o=h,d.runner.subscribeOnUpdateAnimation(e.f[a.id].c)):(e.f[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c),
delete e.f[a.id]),a._scaleX=p,a._scaleY=s,a.setDirtyTransform())):e.f[a.id]&&(d.runner.unsubscribeOnUpdateAnimation(e.f[a.id].c),delete e.f[a.id]);return n}function ea(a,b,c){return b.rotation!==l?(a._rotation+=b.rotation,c.rotationResult!==l&&(c.rotationResult=a._rotation),a.setDirtyTransform(),n):q}function fa(a,b,c){return b.scale!==l?(a._scaleX*=b.scale.x,a._scaleY*=b.scale.y,c.scaleResult!==l&&(c.scaleResult={x:a._scaleX,y:a._scaleY}),a.setDirtyTransform(),n):q}function ga(a,b){return b.text!==
l?(a.text=b.text.toString(),n):q}function ia(a,b){return b.fontSize!==l?(a.fontSize=b.fontSize,n):q}function ja(a,b){return b.borderWidth!==l?(a.borderWidth=b.borderWidth,n):q}function ka(a,b){if(b.text===l&&b.fontSize===l&&b.borderWidth===l)return q;b.text!==l&&(a.text=""+b.text);b.fontSize!==l&&(a.fontSize=b.fontSize);b.borderWidth!==l&&(a.borderWidth=b.borderWidth);return n}function la(a,b,c){return c.animationName!==l&&"string"===typeof c.animationName?(c.animationName=a.currentAnimationName,
n):q}function ma(a,b){return b.animationName!==l&&a.currentAnimation?a.startAnimation(b.animationName.toString(),l,l,l,l):q}function na(a,b,c){return c.fps!==l&&a.currentAnimation?(c.fps=a.fps,n):q}function oa(a,b,c){return c.loop!==l&&a.currentAnimation?(c.loop=a.loop,n):q}function pa(a,b){return 0<=b.fps&&a.currentAnimation?(a.fps=b.fps,n):q}function qa(a,b){return b.loop!==l&&a.currentAnimation?(a.loop=b.loop,n):q}var Q,S=[];new window.TWO.core.math.Matrix3;new window.TWO.core.math.Vector2;new window.TWO.core.math.Vector2;
new window.TWO.core.math.Vector2;new window.TWO.core.math.Vector2;var ra=window.TWO.core.renderables.Object2d;window.TWO.core.renderables.Object2d=function(){var a=new ra;b(a);a.setValuesFromJson=function(a){k(this,a)};return a};var Z=window.TWO.core.renderables.Bitmap;window.TWO.core.renderables.Bitmap=function(){var a=new Z;b(a);a.setValuesFromJson=function(a){k(this,a);this.image=a.image;a.anchor&&(this.anchorType=a.anchor.type,a.anchor.value&&(this.anchor=a.anchor.value))};return a};window.TWO.core.renderables.Bitmap.uber=
Z.uber;var $=window.TWO.core.renderables.Text;window.TWO.core.renderables.Text=function(){var a=new $;b(a);a.setValuesFromJson=function(a){k(this,a);this._font="arial";this._fontSize=10;this._text="";this._fill=n;this._borderWidth=this._colorB=this._colorG=this._colorR=0;a.text&&(this._text=a.text);a.font&&(this._font=a.font);a.fontSize&&(this._fontSize=a.fontSize,this._h=2*this._fontSize);a.fill&&(this._fill=a.fill);a.color&&(Array.isArray(a.color)&&3==a.color.length)&&(this._colorR=a.color[0],this._colorG=
a.color[1],this._colorB=a.color[2]);a.borderWidth&&(this._borderWidth=a.borderWidth);a.borderColor&&(Array.isArray(a.borderColor)&&3==a.borderColor.length)&&(this._bColorR=a.borderColor[0],this._bColorG=a.borderColor[1],this._bColorB=a.borderColor[2]);a.anchor&&(this.anchorType=a.anchor.type,a.anchor.value&&(this.anchor=a.anchor.value));this._recalcSize=n};return a};window.TWO.core.renderables.Text.uber=$.uber;var aa=window.TWO.core.renderables.Sprite;window.TWO.core.renderables.Sprite=function(){var a=
new aa;b(a);r(a);a.setValuesFromJson=function(a){this._loop=a.loop;this._spriteDefName=a.spriteDef;this.currentAnimationName=a.currentAnimation;if(this.spriteDef=this.resourceMgr.getResource("spriteDef",this._spriteDefName))(this.currentAnimationName=a.currentAnimation||this.spriteDef.defaultAnimation)&&this.spriteDef.animations[this.currentAnimationName]?(this.startAnimation(this.currentAnimationName,this.spriteDef.animations[this.currentAnimationName].fps||this.spriteDef.defaultFps||0,this.spriteDef.animations[this.currentAnimationName].revert||
q,this.spriteDef.animations[this.currentAnimationName].loop),a.image=this.spriteDef.image):a.image=l;a.anchor&&(this.anchorType=a.anchor.type,a.anchor.value&&(this.anchor=a.anchor.value));k(this,a)};return a};window.TWO.core.renderables.Sprite.uber=aa.uber;var ba=window.TWO.core.renderables.Layer;window.TWO.core.renderables.Layer=function(){var a=new ba;a.setValuesFromJson=function(a){this.name=a.name||"";this._visible=a.visible!==l?a.visible:n;this._alpha=a.alpha!==l?a.alpha:1;this.dirty=n};return a};
window.TWO.core.renderables.Layer.uber=ba.uber;d.prototype={Y:function(){return this.j.DefaultScene},W:function(a,b){function c(e){e&&d.K(e,l,l,a,d);b()}var d=this;this.j&&this.j.DefaultScene?this.p.get(this.j.DefaultScene,c,l,this.Q):b()},V:function(){this.p.reloadAssets(this.fa);this.a.scene=l;for(var a=0;a<S.length;a+=1)S[a]&&this.s(S[a],l,l,l,this);S.length=0;this.j&&this.j.DefaultScene&&this.p.release(this.j.DefaultScene,this.Q);this.d={};this.e={};this.f={}},da:function(a){this.a.setRenderingParams({doNotUseDevicePixelRatio:!a});
this.n.setViewScaleFactor(this.a.renderMgr._scaleX,this.a.renderMgr._scaleY)},ca:function(a,b){this.m.setAttribute("style","position:absolute;width:"+a+"px;height:"+b+"px;");this.U=a;this.T=b;this.a.resize(a,b);this.n.setViewScaleFactor(this.a.renderMgr._scaleX,this.a.renderMgr._scaleY)},L:function(a,b){function c(a){if(a.customProperties!==l)for(h in a.customProperties)-1==d.indexOf(h)&&d.push(h)}for(var d=[],e=a,h,f=function Y(a){for(var b=0;b<a.length;b++)c(a[b]),a[b].children!==l&&0<a[b].children.length&&
Y(a[b].children)};e!==l;)c(e),e=e._parent;b&&(a.children!==l&&0<a.children.length)&&f(a.children);return d},Z:function(a,b,c,d,e){function h(b,c){c.length=0;for(var f=function sa(a,g){var d=g;if(g||a.customProperties!==l&&a.customProperties[b]!==l)"Layer"!==a.type&&c.push(a),d=n;for(var e=0;e<a.children.length;e++)sa(a.children[e],d)},m=a,k=q;m!==l;)m.customProperties!==l&&m.customProperties[b]!==l?(k=n,m=l):m=m._parent;d&&(k||a.customProperties!==l&&a.customProperties[b]!==l)&&"Layer"!==a.type&&
c.push(a);e&&f(a,k)}var f=[],m=[],k=[],p;if(Array.isArray(b)){if(0<b.length){h(b[0],f);c&&(k=f.slice(0));for(var s=1;s<b.length&&0!=f.length;s++){c||(k.length=0);h(b[s],m);for(var r=0;r<m.length;r++)p=f.indexOf(m[r]),(-1!=p&&!c||-1==p&&c)&&k.push(m[r]);f=k.slice(0)}}}else h(b,f);return f},k:function(a,b){for(var c=a.length-1;0<=c;c--)this.J(a[c].type,b)||a.splice(c,1)},J:function(a,b){function c(a){switch(a){case "Scene":a="SceneTwo";break;case "Layer":a="LayerTwo";break;case "Object2d":a="Object2DTwo";
break;case "Bitmap":a="BitmapTwo";break;case "Sprite":a="SpriteTwo";break;case "Text":a="TextTwo"}return a}var d=q;a=c(a);b=c(b);if(a==b)d=n;else switch(b){case "Object2DTwo":if("TextTwo"==a||"SpriteTwo"==a||"BitmapTwo"==a)d=n;break;case "BitmapTwo":"SpriteTwo"==a&&(d=n)}return d},S:function(a,b){var c=this;Q.resourceManager.getRes(a,l,function(a,g){if(a)Q.logger.warn("Error downloading resource "+a);else if(!c.a.resourceMgr.getResource("image",g.id)){var d=g.data,e=document.createElement("canvas"),
h=e.getContext("2d");e.width=d.width;e.height=d.height;h.clearRect(0,0,e.width,e.height);h.drawImage(d,0,0,d.width,d.height);c.a.resourceMgr.addResource("image",g.id,e,g.id)}b()})},aa:function(a,b,c){function d(){function a(){f--;0==m&&(0==f&&0==k)&&c()}if(0<f)for(var g=0;g<b.images.length;g++)b.images[g].url&&!p.a.resourceMgr.getResource("image",b.images[g].url)?p.S(b.images[g].url,a):a();else 0==m&&(0==f&&0==k)&&c()}function e(){if(0<m)for(var c=0;c<b.spriteDefs.length;c++)h(b.spriteDefs[c].url,
function(a,g,c){if(a&&(p.a.resourceMgr.addResource("spriteDef",c,a,c),a.image))a:{a=a.image;for(g=b.images.length;g--;)if(b.images[g].url==a)break a;b.images.push({url:a,name:a});f++}m--;0==m&&d()},a);else d()}function h(a,b,g){p.p.get(a,function(g,c){b(g,c,a)},["scene"],l,g)}var f=0,m=0,k=0,p=this;b.spriteDefs&&(m=b.spriteDefs.length);b.images&&(f=b.images.length);b.layers&&(k=b.layers.length);if(0==m&&0==f&&0==k)c();else if(e(),0<k)for(var s=0;s<b.layers.length;s++)h(b.layers[s].url,function(a,
b,g){p.a.resourceMgr.addResource("layer",g,a,g);k--;0==m&&(0==f&&0==k)&&c()},a)},ba:function(a,b,c,d){var e=this;e.aa(c,a,function(){switch(d){case e.v:var f=e.a.createElement("Scene");a.id=c;f.load(e.a,a,function(){f.q=a;b&&b(c,f)});break;case e.u:e.a.resourceMgr.resources.layer||(e.a.resourceMgr.resources.layer={});if(!e.a.resourceMgr.resources.layer[c]){e.a.resourceMgr.addResource("layer",c,n,c);var h=e.a.createElement("Layer");a.id=c;h.load(e.a,a,function(d){e.a.resourceMgr.resources.layer[c]=
{res:d,url:c};e.a.resourceMgr.resourcesByUrl[c]=d;d.q=a;for(var f in a.objects)a.objects[f]&&a.objects[f].customProperties&&(d.objects[f].customProperties=a.objects[f].customProperties);b(c,d)})}break;case e.w:e.a.resourceMgr.resources.spriteDef||(e.a.resourceMgr.resources.spriteDef={});e.a.resourceMgr.resources.spriteDef[c]={res:a,url:c};e.a.resourceMgr.resourcesByUrl[c]=a;b(c,e.a.resourceMgr.getResource("spriteDef",c));break;default:b(c)}})},$:function(a,b){var c=a;b&&1<b.length&&(c=a.getById(b[1]));
return c},I:function(a,b,c,e,f){if(e&&-1!=a.name.indexOf(b)||a.name==b)if(c.push(a),f)return;for(var h=0;h<a.children.length&&!(d.prototype.I(a.children[h],b,c,e),f&&0<c.length);h++);},t:function(a,b){this.e[a]&&(b.unsubscribeOnUpdateAnimation(this.e[a].c),delete this.e[a]);this.d[a]&&(b.unsubscribeOnUpdateAnimation(this.d[a].c),delete this.d[a]);this.f[a]&&(b.unsubscribeOnUpdateAnimation(this.f[a].c),delete this.f[a])},s:function(a,b,c,d,e){var f,h,m,k;b=a.q;for(c=0;c<a.layers.length;c++)if(d=e.a.resourceMgr.getResource("layer",
b.layers[c].url),d!==l)for(h in d.objects)e.t(h,e.n);if(a.__newSceneObject)delete a;else for(c=0;c<a.layers.length;c++)if(d=e.a.resourceMgr.getResource("layer",b.layers[c].url),d!==l)if(k=d.q,d.__newSceneObject)a.removeLayer(d.id);else for(h in d.objects)d.objects[h]&&(d.objects[h].__newSceneObject||!k.objects[h])&&d.removeObject(h,n,n);h=e.i;for(f in a.layersById)if(c=h[f]){for(d=0;d<c.length;d++)a.layersById[f].addObject(c[d]);delete h[f]}a.layers.length=0;a.layersById={};for(c=0;c<b.layers.length;c++)if(d=
e.a.resourceMgr.getResource("layer",b.layers[c].url),d!==l){if(k=d.q){var p;for(m in k.objects)if(p=d.getById(m)){if(p.setValuesFromJson(k.objects[m]),p.children.length=0,k.objects[m].children)for(f=0;f<k.objects[m].children.length;f++)(h=d.getById(k.objects[m].children[f]))?(p.children.push(h),h._parent=p):Q.logger.warn("Warning: elements with invalid children in layer. Invalid child id: "+k.objects[m].children[f]+" in object "+p.name+" (id: "+m+")")}else Q.logger.warn("Warning: invalid elements in layer. Element id: "+
m+" in layer "+d.name+" (id: "+d.id+")");if(k.children)for(f=d.children.length=0;f<k.children.length;f+=1)d.appendChild(d.objects[k.children[f]]);d.setValuesFromJson(k);a.appendLayer(d)}}else Q.logger.warn("Warning: invalid layer. Layer id: "+b.layers[c].url);a.setDirty();return n},K:function(a,b,c,d,e){function f(a,b,c,d,g){c.update&&c.update(a,b,d,g);if(c.children){d=c._visible?c.finalAlpha:0;for(g=0;g<c.children.length;g+=1)f(a,b,c.children[g],c.finalTransform,d)}}e.a.scene=a;-1===S.indexOf(a)&&
S.push(a);for(a=0;a<e.a.scene.layers.length;a+=1)f(d.event.time,0,e.a.scene.layers[a],l,1);return n},l:function(a,b,c){function d(a,b){b.__newSceneObject=n;if(a.customProperties){b.customProperties={};for(var c in a.customProperties)b.customProperties[c]=a.customProperties[c]}for(c=0;c<a.children.length;c++)d(a.children[c],b.children[c])}if(b.parent){var e=a.clone();d(a,e);b.parent.appendChild(e);e._updateObject2d(0,0,b.parent.finalTransform,1,q);e._dirtyTransform=q;e._dirty=n;c.clone=e;return n}return q},
z:function(a,b,c,d,e){b=function Y(a,b){for(var c=0;c<a.length;c++)Y(a[c].children,b),b.t(a[c].id,b.n),delete a[c].ownerLayer.objects[a[c].id],a[c].__newSceneObject||(b.i[a[c].ownerLayer.id]||(b.i[a[c].ownerLayer.id]=[]),b.i[a[c].ownerLayer.id].push(a[c])),a[c].children.length=0};var f;d=n;if("Layer"!==a.type)if(c=a._parent,c!==l){var h=c.children.indexOf(a);-1!==h?(c.children.splice(h,1),a.ownerLayer!==l&&a.ownerLayer.objects[a.id]!==l&&(f=a.ownerLayer,b(a.children,e),e.t(a.id,e.n),delete f.objects[a.id],
a.children.length=0),a.__newSceneObject||(e.i[f.id]||(e.i[f.id]=[]),e.i[f.id].push(a)),f.dirty=n):d=q}else d=q;return d}};d.prototype.resizeRenderer=d.prototype.ca;d.prototype.setHDGraphicsMode=d.prototype.da;d.prototype.getDefaultSceneKey=d.prototype.Y;d.prototype.beforePlayNotify=d.prototype.W;d.prototype.afterStopNotify=d.prototype.V;return{dependencies:function(b){Q=b;b=b.runEngine.paramManager;b.addParamType("SceneTwo","Scene",l);b.addParamTypeAction("SceneTwo","activate",d.prototype.K,"two");
b.addParamTypeAction("SceneTwo","findByName",e,"two");b.addParamTypeAction("SceneTwo","getLayers",w,"two");b.addParamTypeAction("SceneTwo","reset",d.prototype.s,"two");b.addParamType("LayerTwo","Layer",{visible:{type:"bool"},alpha:{type:"number"}});b.addParamTypeAction("LayerTwo","findByName",a,"two");b.addParamTypeAction("LayerTwo","getChildren",C,"two");b.addParamTypeAction("LayerTwo","getTransparency",f);b.addParamTypeAction("LayerTwo","getVisibility",D);b.addParamTypeAction("LayerTwo","setTransparency",
y);b.addParamTypeAction("LayerTwo","setVisibility",E);b.addParamType("Object2DTwo","Object2D",{position:{type:"_Vector2_"},rotation:{type:"number"},scale:{type:"_Vector2_"},visible:{type:"bool"},alpha:{type:"number"}});b.addParamTypeAction("Object2DTwo","clone",d.prototype.l);b.addParamTypeAction("Object2DTwo","delete",d.prototype.z,"two");b.addParamTypeAction("Object2DTwo","findByName",a,"two");b.addParamTypeAction("Object2DTwo","getAbsPosition",G);b.addParamTypeAction("Object2DTwo","getChildren",
C,"two");b.addParamTypeAction("Object2DTwo","getName",t);b.addParamTypeAction("Object2DTwo","getParent",m,"two");b.addParamTypeAction("Object2DTwo","getPosition",h);b.addParamTypeAction("Object2DTwo","getPositionXY",p);b.addParamTypeAction("Object2DTwo","getPositionX",u);b.addParamTypeAction("Object2DTwo","getPositionY",s);b.addParamTypeAction("Object2DTwo","getRotation",M);b.addParamTypeAction("Object2DTwo","getRotationSpeed",R,"two");b.addParamTypeAction("Object2DTwo","getScalationSpeed",T,"two");
b.addParamTypeAction("Object2DTwo","getScale",v);b.addParamTypeAction("Object2DTwo","getTranslationSpeed",z,"two");b.addParamTypeAction("Object2DTwo","getTransparency",f);b.addParamTypeAction("Object2DTwo","getVisibility",D);b.addParamTypeAction("Object2DTwo","goTo",V,"two");b.addParamTypeAction("Object2DTwo","rotate",ea);b.addParamTypeAction("Object2DTwo","rotateTo",W,"two");b.addParamTypeAction("Object2DTwo","scale",fa);b.addParamTypeAction("Object2DTwo","scaleTo",X,"two");b.addParamTypeAction("Object2DTwo",
"setParent",c);b.addParamTypeAction("Object2DTwo","setPosition",H);b.addParamTypeAction("Object2DTwo","setPositionXY",P);b.addParamTypeAction("Object2DTwo","setPositionX",A);b.addParamTypeAction("Object2DTwo","setPositionY",O);b.addParamTypeAction("Object2DTwo","setRotation",K);b.addParamTypeAction("Object2DTwo","setRotationSpeed",da,"two");b.addParamTypeAction("Object2DTwo","setScalationSpeed",U,"two");b.addParamTypeAction("Object2DTwo","setScale",L);b.addParamTypeAction("Object2DTwo","setTranslationSpeed",
x,"two");b.addParamTypeAction("Object2DTwo","setTransparency",y);b.addParamTypeAction("Object2DTwo","setVisibility",E);b.addParamTypeAction("Object2DTwo","translate",N);b.addParamTypeAction("Object2DTwo","translateXY",B);b.addParamTypeAction("Object2DTwo","translateX",F);b.addParamTypeAction("Object2DTwo","translateY",J);b.addParamType("BitmapTwo","Bitmap",{position:{type:"_Vector2_"},rotation:{type:"number"},scale:{type:"_Vector2_"},visible:{type:"bool"},alpha:{type:"number"}});b.addParamType("SpriteTwo",
"Sprite",{position:{type:"_Vector2_"},rotation:{type:"number"},scale:{type:"_Vector2_"},visible:{type:"bool"},alpha:{type:"number"},animation:{type:"string"}});b.addParamType("TextTwo","Text",{font:{type:"string"},fontSize:{type:"number"},fill:{type:"bool"},r:{type:"number"},g:{type:"number"},b:{type:"number"},borderWidth:{type:"number"},borderR:{type:"number"},borderG:{type:"number"},borderB:{type:"number"},position:{type:"_Vector2_"},rotation:{type:"number"},scale:{type:"_Vector2_"},visible:{type:"bool"},
alpha:{type:"number"}});b.setCompatibleWith("TextTwo",["Object2DTwo"]);b.addParamTypeAction("TextTwo","clone",d.prototype.l);b.addParamTypeAction("TextTwo","setText",ga);b.addParamTypeAction("TextTwo","setBorderWidth",ja);b.addParamTypeAction("TextTwo","setFontSize",ia);b.addParamTypeAction("TextTwo","setProperties",ka);b.setCompatibleWith("SpriteTwo",["BitmapTwo","Object2DTwo"]);b.addParamTypeAction("SpriteTwo","clone",d.prototype.l);b.addParamTypeAction("SpriteTwo","getCurrentAnimationFPS",na);
b.addParamTypeAction("SpriteTwo","getCurrentAnimationLoop",oa);b.addParamTypeAction("SpriteTwo","getCurrentAnimationName",la);b.addParamTypeAction("SpriteTwo","setAnimation",ma);b.addParamTypeAction("SpriteTwo","setCurrentAnimationFPS",pa);b.addParamTypeAction("SpriteTwo","setCurrentAnimationLoop",qa);b.setCompatibleWith("BitmapTwo",["Object2DTwo"]);b.addParamTypeAction("BitmapTwo","clone",d.prototype.l)},implementation:{Manager:d,config:{}}}};I("PENGO.client.shared.runEngine.two.actuators.collisionTest");
window.PENGO.client.shared.runEngine.two.actuators.collisionTest.resolve=function(){function d(a,c,d,f){var r=new e.runEngine.Blackbox(a,c,d,f,"CollisionTestTWO"),E=e.runEngine.getManager();r.createInParam("object1",0);r.createInParam("object2",1);r.createOutParam("testResult",0);r.withCollection=q;var A,w,y,D,N,B,F,J;r.createInput("test",0,function(a){if(r.withCollection){if(N=r.inParameters.object,B=r.inParameters.objects,N&&B)if(y=r.outParameters.objectsOnCollision,0<B.length){w=q;k(N,m,h,C);if(y){y.length=
0;D=r.getOutParamType(1);for(A=0;A<B.length;A++)k(B[A],G,p,t),b(C,h,G)&&b(t,p,m)&&(w=n,E.J(B[A].type,D)&&y.push(B[A]))}else for(A=0;A<B.length&&w!=n;A++)k(B[A],G,p,t),w=b(C,h,G)&&b(t,p,m);(r.outParameters.testResult=w)?r.fireOutput(0,a):r.fireOutput(1,a)}else y&&(y.length=0),r.fireOutput(1,a)}else F=r.inParameters.object1,J=r.inParameters.object2,F&&J&&(k(F,m,h,C),k(J,G,p,t),b(C,h,G)&&b(t,p,m)?(r.outParameters.testResult=n,r.fireOutput(0,a)):(r.outParameters.testResult=q,r.fireOutput(1,a)))});r.createOutput("true",
0);r.createOutput("false",1);return r}function k(b,d,e,f){for(var h=w,m=[],k=b,p=q;k._parent;)m.push(k),k=k._parent;for(h.identity();0<m.length;)k=m.pop(),p||k._dirtyTransform?(p=n,a.makeTranslate(k._x,k._y),a.rotate(k._rotation),a.scale(k._scaleX,k._scaleY),h.multiply(a)):h.copy(k.finalTransform);d[0].set(0,0);d[1].set(b._w,0);d[2].set(b._w,b._h);d[3].set(0,b._h);c.makeTranslate(b._pivotX,b._pivotY);w.multiply(c);for(b=0;4>b;b++)w.transformVector2(d[b]);e[0].sub(d[1],d[0]);e[1].sub(d[3],d[0]);e[0].divideScalar(e[0].lengthSq());
e[1].divideScalar(e[1].lengthSq());f.x=d[0].dot(e[0]);f.y=d[0].dot(e[1])}function b(a,b,c){var d;E=D=y=c[0].dot(b[0]);for(d=1;4>d;d+=1)y=c[d].dot(b[0]),y<D?D=y:y>E&&(E=y);if(D>1+a.x||E<a.x)return q;E=D=y=c[0].dot(b[1]);for(d=1;4>d;d+=1)y=c[d].dot(b[1]),y<D?D=y:y>E&&(E=y);return D>1+a.y||E<a.y?q:n}function r(a,b){b&&(a.withCollection=n)}var e,w,a,c,f,y,D,E,C,t,m=[],G=[],h=[],p=[];for(f=0;4>f;f++)m.push(new window.TWO.core.math.Vector2),G.push(new window.TWO.core.math.Vector2);for(f=0;2>f;f++)h.push(new window.TWO.core.math.Vector2),
p.push(new window.TWO.core.math.Vector2);C=new window.TWO.core.math.Vector2;t=new window.TWO.core.math.Vector2;w=new window.TWO.core.math.Matrix3;a=new window.TWO.core.math.Matrix3;c=new window.TWO.core.math.Matrix3;return{dependencies:function(a){e=a;e.runEngine.blackboxRepository.addBlackboxType("CollisionTestTWO",d);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("CollisionTestTWO",l,r)},implementation:{ha:d}}};I("PENGO.client.shared.runEngine.two.actuators.getObjectsByLabel");
window.PENGO.client.shared.runEngine.two.actuators.getObjectsByLabel.resolve=function(){function d(d,e,k,a){function c(a){return a.toString()}var f=new b.runEngine.Blackbox(d,e,k,a,"GetObjectsByLabelTWO"),y=b.runEngine.getManager(),D=l;f.setProdideResultMode=function(a){function b(a){var c=f.getOutParamValue(0);c&&f.setOutParamValue(0,c.value.concat(a))}function c(a){f.setOutParamValue(0,a)}D=a?c:b};f.setProdideResultMode(n);f.createInParam("target",0);f.createInParam("labels",1);f.createOutParam("objects",
0);f.createOutParam("numberOfObjects",1);f.createInput("do",0,function(a){var b=f.getInParamValue(1);b!==l&&"string"!==f.getInParamType(1)&&(b=Array.isArray(b)?b.map(c):c(b));f.inParameters.target&&b!==l&&(b=y.Z(f.inParameters.target,b,!f.inParameters.allLabels,q,n),y.k(b,f.getOutParamType(0)),D(b),f.outParameters.numberOfObjects=b.length,f.fireOutput(0,a))});f.createOutput("done",0);return f}function k(b,d){d&&d.A?b.setProdideResultMode(q):b.setProdideResultMode(n)}var b;return{dependencies:function(r){b=
r;b.runEngine.blackboxRepository.addBlackboxType("GetObjectsByLabelTWO",d);r.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("GetObjectsByLabelTWO",l,k);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("GetObjectsByLabelTWO","allLabels",q)},implementation:{oa:d}}};I("PENGO.client.shared.runEngine.two.actuators.findByName");
window.PENGO.client.shared.runEngine.two.actuators.findByName.resolve=function(){var d,k=function r(e,k,a,c){var f=new d.runEngine.Blackbox(e,k,a,c,"FindByNameTwo");f.createInParam("name",0);f.createInParam("target",1);f.createInParam("containsName",2);f.createOutParam("result",0);f.createOutParam("numberOfElements",1);f.createInput("do",0,function(a){var c,e,k,t=[],m=Array.isArray(f.outParameters.result),w=f.inParameters.target,h=f.inParameters.containsName,p=f.inParameters.name;if(w&&p!==l){var p=
p.toString(),u=f.getOutParamType(0),s=q;if("SceneTwo"==f.getInParamType(1))for(c=0;c<w.layers.length&&!s;c++)if(k=w.layers[c],"LayerTwo"==u){if(h&&-1!=k.name.indexOf(p)||k.name==p)t.push(k),m||(s=n)}else for(e=0;e<k.children.length&&!s;e++)r.prototype.H(k.children[e],p,t,h),0<t.length&&!m&&(s=n);else r.prototype.H(w,p,t,h,!m);d.runEngine.getManager().k(t,f.getOutParamType(0));m?(f.outParameters.result=t,f.outParameters.numberOfElements=t.length):0<t.length?(f.outParameters.result=t[0],f.outParameters.numberOfElements=
1):f.outParameters.numberOfElements=0;f.fireOutput(0,a)}});f.createOutput("done",0);return f};k.prototype={H:function(d,e,w,a,c){if(a&&-1!=d.name.indexOf(e)||d.name==e)if(w.push(d),c)return;for(var f=0;f<d.children.length&&!(k.prototype.H(d.children[f],e,w,a),c&&0<w.length);f++);}};return{dependencies:function(r){d=r;d.runEngine.blackboxRepository.addBlackboxType("FindByNameTwo",k);r.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("FindByNameTwo","containsName",q)},implementation:{ja:k}}};})();
