/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var k=void 0,n=this;function s(c){c=c.split(".");var d=n;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var a;c.length&&(a=c.shift());)d=d[a]?d[a]:d[a]={}}Math.random();s("PENGO.client.plugins.stats.model");window.PENGO.client.plugins.stats.model.resolve=function(){function c(){}c.prototype={};return c};s("PENGO.client.plugins.stats.errors");window.PENGO.client.plugins.stats.errors.resolve=function(c){return{O:k,J:{"mod:conf#1":{msg:!1,code:c.pengoError.codes.codes.NOT_FOUND},"mod:conf#2":{msg:!1,code:c.pengoError.codes.codes.NOT_FOUND},"mod:conf#3":{msg:!1,code:c.pengoError.codes.codes.INVALID_TYPE},"ct:vgid#1":{msg:!1,code:c.pengoError.codes.codes.INVALID_DATA},"ct:rget#1":{msg:!1,code:c.pengoError.codes.codes.UNEXPECTED}}}};s("PENGO.client.plugins.stats.controller");
window.PENGO.client.plugins.stats.controller.resolve=function(){return function(c){return{N:function(){this.A=!0},o:function(d,a,f,b,e,h){!this.A&&(d&&a)&&(h=h||c.m||[],h.forEach(function(h){h.emit(d,a,f,b,e)}))},p:function(d,a,f){this.A||(f=f||c.m||[],f.forEach(function(b){b.pageView(d,a)}))},q:function(d,a,f){!this.A&&d&&(a=a||c.m||[],a.forEach(function(b){b.setUser(d,f)}))},H:function(d,a){if("string"===typeof d)c.m.name=a;else throw new PengoError("Transport name invalid",errorCodes.INVALID_DATA);
},K:function(d){"string"===typeof d&&delete c.m.name}}}};s("PENGO.client.plugins.stats.transports.wimi5AnalyticsTracker");
window.PENGO.client.plugins.stats.transports.wimi5AnalyticsTracker.resolve=function(){function c(d,a){this.h=d;this.i=a;this.z=k;this.u=5;this.D=function(f,b,a){var d=this;f||(f={});try{$.ajax({url:f.url,type:f.method,data:b,dataType:"json",headers:f.headers,success:function(b,c,g){switch(g.status){case 200:a&&a.call(this,k,b,g.status);break;default:d.h.j.error("Status "+g.status+" while posting to '"+f.url),a&&a.call(this,k,k,g.status)}},error:function(b,c,g){d.h.j.error("Error '"+g+" with response "+
b.responseText+"' while posting to '"+f.url);a&&a.call(this,k,g,b.status)}})}catch(c){d.h.j.error("Unexpected error '"+c+" while posting to '"+f.url),a&&a.call(this,c)}};this.G=function(a){this.z=a}}c.prototype={L:function(d,a){var f=this;this.D({url:f.i.tokenURL,method:"POST"},{a:this.z,b:this.h.i.appkey,c:this.h.i.type,d:"stats"},function(b,e,h){b?d&&d.call(a||f,b,h):e?d&&d.call(a||f,k,e,h,f.z):d&&d.call(a||f,Error("Empty token received."),h)})},t:function(d,a,f){var b=this;this.B?b.D({url:b.i.statsURL,
method:"POST"},{e:b.B,f:{c:d&&d.I,a:d&&d.action,l:d&&d.label,v:d&&d.value}},function(e,h,c){if(e)a&&a.call(f||b,e,c);else switch(c){case 200:b.u=5;a&&a.call(f||b);break;case 401:b.u--;0<=b.u?(b.B=k,b.t(d,a,f)):b.u=5;break;default:a&&a.call(f||b,Error("Bad HTTP status code "+c+" while sending stats."))}}):b.L(function(e,c){e?(b.h.j.error(e+" sending stats."),a&&a.call(f||this,e)):(b.B=c,b.t(d,a,f))})}};return c};s("PENGO.client.plugins.stats.transports.wimi5Analytics");
window.PENGO.client.plugins.stats.transports.wimi5Analytics.resolve=function(c,d){function a(a,b){this.h=a;this.g={};this.status="initialized";this.i=b}a.prototype={r:function(a,b){var e=this;try{"started"===e.status?a&&a.call(b||e):(e.status="loading",e.i.properties.forEach(function(b){e.g[b.name]=new d.wimi5AnalyticsTracker(e.h,e.i);e.g[b.name].s=b}),e.status="started",a&&a.call(b||this))}catch(c){"initialized"===e.status&&a&&a.call(b||e,"Unable to use Google Analytics stats due to error "+c+" "+
c.stack)}},finish:function(a,b){callback&&callback.call(b||this)},q:function(a,b){var d,c,g=this;try{d=a&&a.userID,c=a&&a.sid,b?this.g[b]&&this.g[b].s.userIDTracking&&(this.g[b].P=d,this.g[b].G(c)):Object.keys(g.g).forEach(function(b){g.g[b].s.userIDTracking&&(g.g[b].P=d,g.g[b].G(c))})}catch(l){this.h.j.error("Unexpected error "+l+" setting userID on wimi5 stats.")}},o:function(a,b,d,c,g){var l=this;if("started"===this.status)try{g&&l.g[g]?l.g[g]&&l.g[g].t({category:a,action:b,label:d,value:c}):Object.keys(l.g).forEach(function(g){l.g[g].t({I:a,
action:b,label:d,value:c})})}catch(p){this.h.j.error("Unexpected error "+p+" emitting event on piwik.")}},p:function(a,b,d){"started"===this.status&&(d||Object.keys(this.g).forEach(function(){}))}};a.prototype.init=a.prototype.r;a.prototype.finish=a.prototype.finish;a.prototype.setUser=a.prototype.q;a.prototype.emit=a.prototype.o;a.prototype.pageView=a.prototype.p;return a};s("PENGO.client.plugins.stats.transports.piwikAnalytics");
window.PENGO.client.plugins.stats.transports.piwikAnalytics.resolve=function(){function c(d,a){this.h=d;this.g={};this.status="initialized";this.i=a}c.prototype={r:function(d,a){function c(){try{if("started"!==b.status){window.piwikAsyncInit=function(){b.i.properties.forEach(function(a){try{b.g[a.name]=Piwik.getAsyncTracker(),b.g[a.name].setDocumentTitle(document.domain+"/"+document.title),b.g[a.name].setSiteId(a.id),b.g[a.name].setTrackerUrl(a.trackerURL),a.id&&b.g[a.name].setRequestMethod("POST"),
b.g[a.name].enableLinkTracking(),b.g[a.name].s=a}catch(d){b.h.j.error(d+" during initializing piwik transport "+a)}});b.status="started"};var a=document,d=a.createElement("script"),f=a.getElementsByTagName("script")[0];d.type="text/javascript";d.async=!0;d.defer=!0;d.Q="anonymous";d.src=b.i.clientURL;f.parentNode.insertBefore(d,f);setTimeout(function(){"started"!==b.status&&b.h.j.error("Timeout getting piwik stats working.")},5E3);b.status="loading"}}catch(l){"initialized"===b.status&&b.h.j.error("Unable to use Piwik Analytics stats due to error "+
l+" "+l.stack)}}var b=this;if(this.i.autoStart)c();else this.h.C.on("COOKIEPOLICY_ACCEPTED",c);d&&d.call(a||this)},finish:function(d,a){callback&&callback.call(a||this)},q:function(d,a){var c,b=this;try{c=d&&d.userID,a?this.g[a]&&this.g[a].s.userIDTracking&&(this.g[a].setUserId(c),this.g[a].trackPageView()):Object.keys(b.g).forEach(function(a){b.g[a].s.userIDTracking&&(b.g[a].setUserId(c),b.g[a].trackPageView())})}catch(e){this.h.j.error("Unexpected error "+e+" setting userID on piwik.")}},o:function(d,
a,c,b,e){var h=this;if("started"===this.status)try{e?h.g[e]&&h.g[e].trackEvent(d,a,c,b):Object.keys(h.g).forEach(function(e){h.g[e].trackEvent(d,a,c,b)})}catch(g){this.h.j.error("Unexpected error "+g+" emitting event on piwik.")}},p:function(d,a,c){var b=this;if("started"===this.status)try{c?b.g[c]&&b.g[c].trackPageView():Object.keys(b.g).forEach(function(a){b.g[a].trackPageView()})}catch(e){this.h.j.error("Unexpected error "+e+" emitting page view on piwik.")}}};c.prototype.init=c.prototype.r;c.prototype.finish=
c.prototype.finish;c.prototype.setUser=c.prototype.q;c.prototype.emit=c.prototype.o;c.prototype.pageView=c.prototype.p;return c};s("PENGO.client.plugins.stats.transports.googleAnalytics");
window.PENGO.client.plugins.stats.transports.googleAnalytics.resolve=function(){function c(d,a){this.h=d;this.k=k;this.g={};this.status="initialized";"function"===typeof __gaTracker&&(this.k=__gaTracker);this.k&&(this.i=a)}c.prototype={r:function(d,a){function c(){try{"started"!==b.status&&(b.i.properties.forEach(function(a){b.g[a.name]=b.k.create(a.id,"auto",a.name);b.g[a.name].send("pageView")}),b.status="started")}catch(a){b.k=k}}var b=this;if(this.k)if(this.i.autoStart)c();else this.h.C.on("COOKIEPOLICY_ACCEPTED",
c);d&&d.call(a||this)},finish:function(d,a){d&&d.call(a||this)},q:function(d,a){var c,b=this;this.k&&(c=d&&d.userID,this.i.userIDTracking&&c&&(a&&b.g[a]?b.g[a].set("&uid",c):Object.keys(b.g).forEach(function(a){b.g[a].set("&uid",c)})))},o:function(d,a,c,b,e){var h=this;this.k&&"started"===this.status&&(e&&h.g[e]?h.g[e].send("event",d,a,c,b):Object.keys(h.g).forEach(function(e){h.g[e].send("event",d,a,c,b)}))},p:function(c,a,f){var b=this;this.k&&"started"===this.status&&(f&&b.g[f]?b.g[f].send("pageView",
{page:c,title:a||c}):Object.keys(b.g).forEach(function(e){b.g[e].send("pageView",{page:c,title:a||c})}))}};c.prototype.init=c.prototype.r;c.prototype.finish=c.prototype.finish;c.prototype.setUser=c.prototype.q;c.prototype.emit=c.prototype.o;c.prototype.pageView=c.prototype.p;return c};s("PENGO.client.plugins.stats.module");
window.PENGO.client.plugins.stats.module.resolve=function(c,d){function a(){this.j=this.w=k;this.i={};this.m=[]}a.prototype={M:function(a,b,c){var h=this;this.w=a;if(b===k)throw new StoredPengoError(this.w,"mod:conf#1");if(c){switch(c.type){case "package":this.i.type=2;break;case "chromews":this.i.type=4}c.appkey&&(this.i.appkey=c.appkey)}if(b.transports===k||!Array.isArray(b.transports))throw new StoredPengoError(this.w,"mod:conf#2",["transports"]);(b.transports||[]).forEach(function(a){h.m.push(new d.transports[a.name](h,
a.config))})},F:function(a){this.C=a},start:function(a,b,c,h){var g=this,l=[];try{this.j=a,this.model=new d.model,this.n=new d.controller(this),this.F(b),this.m.forEach(function(a){l.push(function(b){a.init(b)})}),async.parallel(l,function(a){a&&g.j.error("Error "+a+" starting stats service.");c&&c.call(h||this)})}catch(p){error&&g.j.error("Unexpected error "+p+" starting stats service."),c&&c.call(h||this)}},stop:function(a,b){var c=[];this.model=this.n=k;this.F(k);this.j=k;this.m.forEach(function(a){c.push(function(){a.finish()})});
async.parallel(c,function(c){c&&k.j.error("Error "+c+" stopping stats service.");a&&a.call(b||this)})}};return a};s("PENGO.client.plugins.stats.activator");
(function(){function c(){g.off("SERVICE_REGISTERED",c);p=g.getService("igloo.logger")[0];m===k&&(m=new b.module);try{m.M(l.config.errorsStore,l.config,h)}catch(d){g.getService("igloo.fatal")[0].handleFatal({Message:d.message,Source:"Setting plugin '"+g.getPluginId()+"'"});return}b.errors.O=l.config.errorsStore;m.start(p,g.getService("igloo.eventsManager")[0],function(b){b?g.getService("igloo.fatal")[0].handleFatal({Message:b.message,Source:"Starting plugin '"+g.getPluginId()+"'"}):(q={functions:{setUser:m.n.q,
setSilent:m.n.N,addTransport:m.n.H,removeTransport:m.n.K,emit:m.n.o,pageView:m.n.p},properties:{}},g.register(f,q),window.stmaha4kiam=q.functions.emit,g.on("SERVICE_UNREGISTERED",a),g.on("SERVICE_UPDATED",r))},this)}function d(b,d){q!==k&&(g.unregister(f,q),q=k,window.stmaha4kiam=k);m!==k&&m.stop(function(){g.off("SERVICE_UNREGISTERED",a);g.off("SERVICE_UPDATED",r);if(b&&!d)g.on("SERVICE_REGISTERED",c);else g.off("SERVICE_REGISTERED",c);e.remove(l.config.errorsStore)})}function a(){}var f="stats",
b,e,h,g,l,p,m,q,r=a;window.PENGO.client.plugins.stats.activator.activator=function(a,f){e=a.pengoError.pengoError.storage;return{start:function(a,d,m,p){g=a;l=d;h=p;b=f;e.add(d.config.errorsStore,f.errors.J);c()},stop:d}}})();})();
