/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var l=void 0,m=!0,n=!1,s=this;function t(f){f=f.split(".");var k=s;!(f[0]in k)&&k.execScript&&k.execScript("var "+f[0]);for(var e;f.length&&(e=f.shift());)k=k[e]?k[e]:k[e]={}};t("PENGO.client.shared.runEngine.matchDataStorage.manager");
window.PENGO.client.shared.runEngine.matchDataStorage.manager.resolve=function(){function f(u,b,e,c,h,g,r){this.n=b;var q;b={f:l};for(q in b);Object.defineProperty(this,q,{get:function(){return u.isOnPlay()},enumerable:m,configurable:n});b={c:l};for(q in b);Object.defineProperty(this,q,{get:function(){return a},set:function(c){a=c;p={};for(var b in a)p[a[b].name]=b},enumerable:m,configurable:n});b={b:l};for(q in b);Object.defineProperty(this,q,{get:function(){return p},set:function(c){p=c},enumerable:m,
configurable:n});r=r[d.runnerKeys.DESCRIPTOR];f.prototype.a(a)&&(r&&!f.prototype.a(r))&&(this.c=f.prototype.h(r))}function k(a,b){return function(d,c){a.f&&b(d,c)}}function e(a,b){return function(d,c){a.f&&b(d,c)}}var d,a={},p={};f.prototype={h:function(a){var b,e=[],c=[],h={},g;for(g in a)if(Array.isArray(a[g])&&5===a[g].length){b={name:a[g][0],type:"",scope:"",defaultValue:a[g][3],index:a[g][4]};switch(a[g][1]){case d.runnerKeys.bool:b.type="bool";break;case d.runnerKeys.string:b.type="string";
break;case d.runnerKeys.number:b.type="number";break;case d.runnerKeys._Vector2_:b.type="_Vector2_";break;case d.runnerKeys._Object_:b.type="_Object_"}switch(a[g][2]){case d.runnerKeys.local:b.scope="local";break;case d.runnerKeys.server:b.scope="server";break;case d.runnerKeys.local_server:b.scope="local_server"}e[a[g][4]]=g;c[a[g][4]]=b}for(a=0;a<e.length;a+=1)e[a]!==l&&c[a]!==l&&(h[e[a]]=c[a]);return h},a:function(a){for(var b in a)return n;return m},e:function(){var d={},b;for(b in a)a[b]&&(a[b].name&&
a[b].type&&a[b].scope&&a[b].defaultValue!==l)&&(d[b]={name:a[b].name,type:a[b].type,scope:a[b].scope,defaultValue:a[b].defaultValue,index:a[b].index});return d},j:function(){d.matchDataStorageService&&d.matchDataStorageService.setDescriptor&&d.matchDataStorageService.setDescriptor(this.e())},d:function(){if(d.matchDataStorageService)return d.matchDataStorageService.getProtocolConstants()},i:function(a,b){return d.matchDataStorageService?(d.matchDataStorageService.get(a,k(this,b)),m):n},g:function(a,
b){return d.matchDataStorageService?(d.matchDataStorageService.set(a,e(this,b)),m):n}};f.prototype.getDescriptor=f.prototype.e;f.prototype.provideDescriptor=f.prototype.j;return{dependencies:function(a){d=a},implementation:{Manager:f}}};t("PENGO.client.shared.runEngine.matchDataStorage.actuators.setMatchData");
(function(){function f(e,d){e.secure=d!==l&&d["0_S_0"]}function k(e){e.setting=n}window.PENGO.client.shared.runEngine.matchDataStorage.actuators.setMatchData.resolve=function(){function e(a,e,f,b){function k(b,d){var e;e=b?1:d.result===h.OK?0:d.result===h.KO?1:d.result===h.USER_KO?2:1;a.callOnNextUpdateDraw(function(a){c.setting=n;c.fireOutput(e,a)})}var c=new d.runEngine.Blackbox(a,e,f,b,"_SetMatchData_key");c.createOutput("done",0);c.createOutput("error",1);c.createOutput("accessDenied",2);c.createOutput("onPrevious",
3);c.secure=m;c.setting=n;var h=l,g=d.runEngine.getManager();c.createInput("set",0,function(a){var b,d,e,f;if(c.secure&&c.setting)c.fireOutput(3,a);else if(e=c.getInParams(),e.length){d={};for(b=0;b<e.length;b+=1)f=c.getInParamValue(e[b].index),f!==l&&g.b[e[b].nameKey]&&(d[g.b[e[b].nameKey]]=f);g.a(d)?c.fireOutput(0,a):(h||(h=g.d()),h?(c.setting=m,g.g(d,k)||(c.setting=n,c.fireOutput(1,a),h=l)):c.fireOutput(1,a))}});return c}var d;e.prototype={};return{dependencies:function(a){a.runEngine.blackboxRepository.addBlackboxType("_SetMatchData_key",
e);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SetMatchData_key",k,f);d=a},implementation:{m:e}}}})();t("PENGO.client.shared.runEngine.matchDataStorage.actuators.resetMatchData");
(function(){function f(e,d){e.secure=d["0_S_0"];e.keysToReset={};for(var a in d)"0_S_0"!=a&&(e.keysToReset[a]=m)}function k(e){e.setting=n}window.PENGO.client.shared.runEngine.matchDataStorage.actuators.resetMatchData.resolve=function(){function e(a,e,f,b){function k(b,d){var e;e=b?1:d.result===h.OK?0:d.result===h.KO?1:d.result===h.USER_KO?2:1;a.callOnNextUpdateDraw(function(a){c.setting=n;c.fireOutput(e,a)})}var c=new d.runEngine.Blackbox(a,e,f,b,"_ResetMatchData_key");c.createOutput("done",0);c.createOutput("error",
1);c.createOutput("accessDenied",2);c.createOutput("onPrevious",3);c.secure=m;c.setting=n;c.keysToReset={};var h=l,g=d.runEngine.getManager();c.createInput("reset",0,function(a){var b,d;if(c.secure&&c.setting)c.fireOutput(3,a);else{d={};for(b in c.keysToReset)g.c[b]&&(d[b]=l);g.a(d)?c.fireOutput(0,a):(h||(h=g.d()),h?(c.setting=m,g.g(d,k)||(c.setting=n,c.fireOutput(1,a),h=l)):c.fireOutput(1,a))}});return c}var d;e.prototype={};return{dependencies:function(a){a.runEngine.blackboxRepository.addBlackboxType("_ResetMatchData_key",
e);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ResetMatchData_key",k,f);d=a},implementation:{l:e}}}})();t("PENGO.client.shared.runEngine.matchDataStorage.actuators.getMatchData");
window.PENGO.client.shared.runEngine.matchDataStorage.actuators.getMatchData.resolve=function(){function f(a,e,f,b){function k(b,d){function e(a){var c,b={};for(c in a)b[c]=a[c];return b}var f,p;b?f=1:d.result===h.OK?(f=0,p=e(d.data)):f=d.result===h.KO?1:d.result===h.USER_KO?2:1;a.callOnNextUpdateDraw(function(a){c.getting=n;if(p!==l){var b=g.c,d;for(d in p)b[d]&&(c.outParameters[b[d].name]=p[d])}c.fireOutput(f,a)})}var c=new d.runEngine.Blackbox(a,e,f,b,"_GetMatchData_key");c.createOutput("available",
0);c.createOutput("error",1);c.createOutput("accessDenied",2);c.createOutput("onPrevious",3);c.secure=m;c.getting=n;var h=l,g=d.runEngine.getManager();c.createInput("get",0,function(a){var b,d,e;if(c.secure&&c.getting)c.fireOutput(3,a);else if(e=c.getOutParams(),e.length){d=[];for(b=0;b<e.length;b+=1)c.isOutParamConnected(e[b].index)&&g.b[e[b].nameKey]&&d.push(g.b[e[b].nameKey]);d.length?(h||(h=g.d()),h?(c.getting=m,g.i(d,k)||(c.getting=n,c.fireOutput(1,a),h=l)):c.fireOutput(1,a)):c.fireOutput(0,
a)}});return c}function k(a,d){a.secure=d!==l&&d["0_S_0"]}function e(a){a.getting=n}var d;return{dependencies:function(a){a.runEngine.blackboxRepository.addBlackboxType("_GetMatchData_key",f);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetMatchData_key",e,k);d=a},implementation:{k:f}}};})();
