/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var c=void 0,t=!0,u=!1,w=this;function C(d){d=d.split(".");var l=w;!(d[0]in l)&&l.execScript&&l.execScript("var "+d[0]);for(var p;d.length&&(p=d.shift());)l=l[p]?l[p]:l[p]={}};C("PENGO.client.plugins.matchDataStorage.staticOps");window.PENGO.client.plugins.matchDataStorage.staticOps.resolve=function(){return{}};C("PENGO.client.plugins.matchDataStorage.errors");window.PENGO.client.plugins.matchDataStorage.errors.resolve=function(d){return{t:c,n:{"mod:conf#1":{msg:u,code:d.pengoError.codes.codes.NOT_FOUND},"mod:conf#2":{msg:u,code:d.pengoError.codes.codes.NOT_FOUND},"mod:conf#3":{msg:u,code:d.pengoError.codes.codes.INVALID_TYPE},"ctrl:noNet":{msg:u,code:d.pengoError.codes.codes.NETWORK_ERROR},"ctrl:keyNotDef":{msg:u,code:d.pengoError.codes.codes.NOT_FOUND}}}};C("PENGO.client.plugins.matchDataStorage.controller");
window.PENGO.client.plugins.matchDataStorage.controller.resolve=function(d){var l=d.pengoError.pengoError.StoredPengoError,p=d.storage.local.getInstance();return function(a){return{get:function(b,m){function d(){var b=[];q.forEach(function(e){b.push(function(m){var b,f,d,h=u;r[e]?m():(d=n+"#"+e,p.getItem(d,function(k,g){if(k)h=t,a.h.error("Unable to get key "+d+" due to "+k);else{f=g;b=a.a[e].type;if(f)try{f=JSON.parse(f),typeof f!==b&&(!("boolean"===typeof f&&"bool"===b)&&!("number"===typeof f&&
"string"===b))&&(a.h.error("Type mimstach expected "+b+" and is "+typeof f),h=t)}catch(l){a.h.error("Unexpected error "+l+" getting key "+d),h=t}else f=a.a[e].defaultValue;h||(r[e]=f)}m(h)}))})});async.parallel(b,function(e){e?m(c,{result:a.c.KO}):m(c,{result:a.c.OK,data:r})})}var g=[],q=[],r={},n=a.b!==c?a.b+"#"+a.e:a.e;if(a.a!==c&&Array.isArray(b)){for(var k=0;k<b.length;k++)if(a.a[b[k]])"server"===a.a[b[k]].scope?g.push(b[k]):"local"===a.a[b[k]].scope?q.push(b[k]):"local_server"===a.a[b[k]].scope&&
(a.b!==c?g.push(b[k]):q.push(b[k]));else{m(new l(a.f,"ctrl:keyNotDef",[b[k]]),c);return}0<g.length?a.d?a.d.call(a.k,"getMatchData",{id:a.e,keys:g},c,function(b,e){if(b)m(b,c);else if(e.result==a.i.results.KO_USER_NOT_AUTHENTICATED)m(c,{result:a.c.USER_KO});else if(e.result==a.i.results.OK){for(var k=0;k<g.length;k++)r[g[k]]=e.data[g[k]]!==c?e.data[g[k]]:a.a[g[k]].defaultValue;d()}else m(c,{result:a.c.KO})},this):m(new l(a.f,"ctrl:noNet"),c):d()}},set:function(b,m){function d(){var b=u,g;for(g in q)if(q[g]===
c)p.removeItem(r+"#"+g);else try{p.setItem(r+"#"+g,JSON.stringify(q[g]))}catch(e){b=t;break}b?m(c,{result:a.c.KO}):m(c,{result:a.c.OK})}var g={},q={},r=a.b===c?a.e:a.b+"#"+a.e;if(a.a!==c){for(var n in b)if(a.a[n])"server"===a.a[n].scope?g[n]=b[n]:"local"===a.a[n].scope?q[n]=b[n]:"local_server"===a.a[n].scope&&(a.b!==c?g[n]=b[n]:q[n]=b[n]);else{m(new l(a.f,"ctrl:keyNotDef",[n]),c);return}0<Object.keys(g).length?a.d?a.d.call(a.k,"setMatchData",{id:a.e,data:g},c,function(b,g){b?m(b,c):g.result==a.i.results.OK?
d():g.result==a.i.results.KO_USER_NOT_AUTHENTICATED?m(c,{result:a.c.USER_KO}):m(c,{result:a.c.KO})},this):m(new l(a.f,"ctrl:noNet"),c):d()}}}}};C("PENGO.client.plugins.matchDataStorage.module");
window.PENGO.client.plugins.matchDataStorage.module.resolve=function(d,l){function p(){var a=this;this.e=this.b=this.a=this.i=this.k=this.d=this.h=this.f=c;this.c={OK:0,KO:-1,USER_KO:-2};this.s=function(){};this.q=function(b){a.a=b};this.o=function(){return a.c}}var a=d.pengoError.pengoError.StoredPengoError,b={};p.prototype={p:function(b,d){this.f=b;if(d===c)throw new a(this.f,"mod:conf#1");this.k=d.remoteService},j:function(a){this.d!==c&&(this.i=c);this.d=a;this.d!==c&&(this.i=this.d.getServiceProtocolConstants(this.k))},
m:function(a){if(this.g!==a){if(this.g)try{this.g.removeEvents(b)}catch(d){this.h.warn("Error "+d+" while removing events when changing events manager")}(this.g=a)&&this.g.registerEvents(b)}return this.g!==c},start:function(a,b){this.h=a;this.m(b);this.l=new l.controller(this)},stop:function(){this.l=c;this.m(c);this.j(c);this.h=c}};return p};C("PENGO.client.plugins.matchDataStorage.activator");
(function(){function d(b){b===s.config.remoteService&&(f.off("REMOTE_SERVICE_AVAILABLE",d),h.j(f),a())}function l(a){a===s.config.remoteService&&(f.off("REMOTE_SERVICE_UNAVAILABLE",l),h.j(c),q(t))}function p(b){"net"===b&&(e.off("SERVICE_REGISTERED",p),f=e.getService("net")[0],a())}function a(){var a=u;if(f!==c)if(f.isConnected())if(f.isAnonymous()?h.b=c:h.b=f.whoAmI(),v.on("CONNECTION_LOST",m),f.isServiceAvailable(s.config.remoteService))f.on("REMOTE_SERVICE_UNAVAILABLE",l),a=t;else f.on("REMOTE_SERVICE_AVAILABLE",
d);else v.on(" CONNECTION_ESTABLISHED",b);a&&(h.j(f),z());return a}function b(){v.off(" CONNECTION_ESTABLISHED",b);a()}function m(){v.off("CONNECTION_LOST",m);h.b=c;h.j(c);q(t)}function z(){h.start(y,v);A={functions:{get:h.l.get,set:h.l.set,getProtocolConstants:h.o,setDescriptor:h.q},properties:{}};e.register(n,A);e.on("SERVICE_UNREGISTERED",r);e.on("SERVICE_UPDATED",B)}function g(){e.off("SERVICE_REGISTERED",g);y=e.getService("igloo.logger")[0];f=e.getService("net")[0];v=e.getService("igloo.eventsManager")[0];
if(!y||!e.getService("igloo.fatal")[0]||!v||!e.getService("game.gameManager")[0])e.on("SERVICE_REGISTERED",g);else{if(h===c){h=new k.module;try{h.p(s.config.errorsStore,s.config),h.e=e.getService("game.gameManager")[0].getGameProperty("id")}catch(b){e.getService("igloo.fatal")[0].handleFatal({Message:b.message,Source:"Setting plugin '"+e.getPluginId()+"'"});return}}k.errors.r=s.config.errorsStore;if(s.config.standalone)h.b=c,z();else if(!a())e.on("SERVICE_REGISTERED",p)}}function q(a){h!==c&&h.stop();
f!==c?(f.off("REMOTE_SERVICE_AVAILABLE",d),f.off("REMOTE_SERVICE_UNAVAILABLE",l)):e.off("SERVICE_REGISTERED",p);e.off("SERVICE_UNREGISTERED",r);e.off("SERVICE_UPDATED",B);if(a)e.on("SERVICE_REGISTERED",g);else e.off("SERVICE_REGISTERED",g);x.remove(s.config.errorsStore)}function r(b){switch(b){case "net":if(e.getService("net")[0]!==f&&(f!==c&&(f.off("REMOTE_SERVICE_UNAVAILABLE",l),f.off("REMOTE_SERVICE_AVAILABLE",d)),h.j(c),f=e.getService("net")[0],!a()))e.on("SERVICE_REGISTERED",p)}}var n="matchDataStorage",
k,x,e,s,y,f,v,h,A,B=r;window.PENGO.client.plugins.matchDataStorage.activator.activator=function(a,b){x=a.pengoError.pengoError.storage;return{start:function(a,d){e=a;s=d;k=b;x.add(d.config.errorsStore,b.errors.n);g()},stop:q}}})();})();
