/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var e=void 0,n=!0,s=this;function y(b){b=b.split(".");var f=s;!(b[0]in f)&&f.execScript&&f.execScript("var "+b[0]);for(var c;b.length&&(c=b.shift());)f=f[c]?f[c]:f[c]={}}Math.random();y("PENGO.client.plugins.game.gameRankings.model");
window.PENGO.client.plugins.game.gameRankings.model.resolve=function(b){var f=b.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e}}}),c=Backbone.Collection.extend({model:f,i:function(){for(var a=this.length-1;0<=a;a-=1)this.at(a).collection.remove(this.at(a))}});return{aa:function(){return b.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{texts:e,games:new c,usergames:new c}},fa:function(a){this.set("texts",a)},F:function(a){this.get("games").add(new f(a))},
P:function(a){this.get("usergames").add(new f(a))},i:function(){this.get("games").i();this.get("usergames").i()}})}}};y("PENGO.client.plugins.game.gameRankings.errors");window.PENGO.client.plugins.game.gameRankings.errors.resolve=function(b){return{ia:e,U:{"md:lang#1":{msg:!1,code:b.pengoError.codes.codes.NOT_FOUND}}}};y("PENGO.client.plugins.game.gameRankings.controller");
window.PENGO.client.plugins.game.gameRankings.controller.resolve=function(b){var f=b.util.callback,c={};return function(a){var l,b,q,d=a.f.getProtocolConstants().results,p=q=b=l=e,m={ca:function(d){d instanceof a.o&&(d.addControllerCallback("setCloseAction",m.Q),d.addControllerCallback("setCloseFromPauseAction",m.R))},u:e,v:function(){m.u===e&&(m.u=a.m.getGameProperty("id"));return m.u},Q:function(){a.h&&(a.w(m.v(),"quitRanking","fromMenuWiMi5"),a.h.hideSideView(),c.p&&f.call(c.p,c.context),c={})},
R:function(){a.h&&(a.w(m.v(),"quitRanking","fromPause"),a.h.hideSideView(),c.p&&f.call(c.p,c.context),c={})},Z:function(){function f(a,c){if(a===e&&c.result===d.OK){l=[];b={};for(var h in c.data.columns)c.data.columns[h].visible===n&&(l[parseInt(c.data.columns[h].priority)]=h,b[h]=c.data.columns[h].tk)}}var c=a.m.getGameProperty("id");a.f.e(c,function(a,c){a!==e||c.result===d.OK&&(p=c.data.showMenuBtn)});a.f.a(c,function(b,l){b===e&&l.result===d.OK&&(q=l.data[0],a.f.d(c,q,f))})},ga:function(f,b,g,
p){function t(f,c){if(f!==e)a.model.i(),a.view.q(n),a.view.$el.find(".WaitView").hide();else if(c.result===d.OK){var b=e,g=e,k=e;a.model.i();a.view.$el.find(".WaitView").hide();if(c.b!==e&&c.b.pos!==e)if(c.b.data===e)g=c.b.pos.toString();else for(var h in c.b.data){b={_id:parseInt(h)+c.b.pos};for(k=0;k<l.length;k+=1)b[l[k]]=c.b.data[h][k];b.name=c.b.data[h][k];"1"===h&&(b.pointed=n);a.model.P(b)}for(h in c.a){b={_id:parseInt(h)+1};for(k=0;k<l.length;k+=1)b[l[k]]=c.a[h][k];b.name=c.a[h][k];g!==e&&
g===h&&(b.pointed=n);a.model.F(b)}k=e;for(b===e?k=1:b._id<a.l.topRankingRows&&(k=b._id+1);k<=a.l.topRankingRows;k+=1){b={_id:k};for(g=0;g<l.length;g+=1)b[l[g]]="-";b.name="-";b.empty=n;a.model.F(b)}}else a.model.i(),a.view.q(n),a.view.$el.find(".WaitView").hide()}c.p=b;c.context=g;p!==n&&a.w(m.v(),"ranking","fromBB");a.f===e?(a.model.i(),a.view.q(n),a.h.showSideView("RankingsView")):(a.view.q(!1),f===e&&(f=a.m.getGameProperty("id")),a.model.i(),a.view.$el.find(".WaitView").show(),a.h.showSideView("RankingsView"),
a.f.b(f,q,a.l.topRankingRows,t))},ja:function(c,l,g,m){function p(c,b){c!==e?r.result=a.k.KO:b.result===d.OK?(r.result=a.k.OK,r.a=null===b.a||b.a===e?0:b.a+1):r.result=b.result===d.KO_NOT_ALLOWED?a.k.USER_KO:a.k.KO;f.call(g,m,e,r)}var x={},r={};a.f===e?(r.result=a.k.KO,f.call(g,m,e,r)):(x[b[l[0]._id]]=l[0].val,a.f.c(c,q,x,p))},G:function(a,b){p===e?setTimeout(m.G,100,a,b):f.call(a,b,p)}};return m}};y("PENGO.client.plugins.game.gameRankings.view");
window.PENGO.client.plugins.game.gameRankings.view.resolve=function(b){return{Y:function(f,c){return b.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.s();this.template=_.template(c.module);this.model.set({texts:f.g},{ha:n});this.firstRender()},s:function(){this.listenTo(this.model.get("games"),"add",this.N,this);this.listenTo(this.model.get("usergames"),"add",this.O,this);this.listenTo(this.model.get("usergames"),"remove",this.da,this)},S:function(){},render:function(){this.$el.html(this.template());
this.$el.find("#mainView > h1#title").text(f.g.tableTitle);this.$el.find("#mainView #userRankingContainer .header").text(f.g.userRanking);this.$el.find("#mainView > h2.header").text(f.g.topN+f.l.topRankingRows);this.$el.find("#userRankingContainer").hide();this.$el.find("#rankingsContainer .error").append(f.g.rankingDataError);this.addControllerCallbacks();return this},q:function(a){a===n?(this.$el.find("#rankingsContainer .error").show(),this.$el.find("#userRankingContainer").hide(),this.$el.find("#mainView > h2.header").hide()):
(this.$el.find("#rankingsContainer .error").hide(),this.$el.find("#mainView > h2.header").show())},N:function(a){a=new f.D({model:a,viewsMgr:this.options.viewsMgr});this.$el.find("#rankingsContainer").append(a.$el)},O:function(a){var b=new f.D({model:a,viewsMgr:this.options.viewsMgr});this.$el.find("#userRankingContainer").append(b.$el);1===a.collection.length&&(this.$el.find(".gameRankingsMain").removeClass("full"),this.$el.find("#userRankingContainer").show())},da:function(a){0===a.collection.length&&
(this.$el.find("#userRankingContainer").hide(),this.$el.find(".gameRankingsMain").addClass("full"))},setCloseAction:function(a){this.$el.find("#closeRankingsBut").off("click");this.$el.find("#closeRankingsBut").click(a)},setCloseFromPauseAction:function(a){this.$el.find(".background-side").off("click");this.$el.find(".background-side").click(a)}})},X:function(f,c){return b.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.s();this.template=_.template(c.RankingRow);this.ka=
_.template(c.RankingRowPointed);this.model.set({texts:f.g},{ha:n});this.firstRender()},s:function(){this.listenTo(this.model,"remove",this.ba,this)},S:function(){},render:function(){this.$el.html(this.template({rank:this.model.get("_id"),user:this.model.get("name"),points:this.model.get("points")}));this.model.get("pointed")===n&&(this.$el.find(".gameData").append(this.ka()),this.$el.find(".gameData").addClass("selected"));1===this.model.get("_id")&&!1===this.model.get("empty")&&this.$el.find(".gameData").addClass("first-ranking");
this.addControllerCallbacks();return this},ba:function(){this.options.viewsMgr.removeView(this.model.get("_id"),this.na);this.remove()}})}}};y("PENGO.client.plugins.game.gameRankings.module");
window.PENGO.client.plugins.game.gameRankings.module.resolve=function(b,f){function c(a,b){var c=this;this.ma=this.l=this.T=e;this.M=a;this.la=b;this.view=this.model=this.j=this.oa=this.f=this.m=this.h=this.V=this.n=this.H=this.o=this.g=e;this.k={OK:0,KO:-1,USER_KO:-2};this.W=function(){return c.k}}c.prototype={ea:function(a){this.l=a;this.T=a.errorsStore},B:function(a){this.L=a},w:function(a,b,c,f){this.L!==e&&this.L.emit(a,b,c,f)},A:function(a){this.n=a;return this.n!==e},K:function(a){a===e?this.t!==
e&&(this.t.off("LANGUAGE_UPDATED",this.I),this.V=e):(this.t=a,this.t.on("LANGUAGE_UPDATED",this.I,this))},C:function(a){this.h=a;return this.h!==e},z:function(a){this.m=a;return this.m!==e},r:function(a){this.f=a;return this.f!=e},start:function(a,c,t,q,d,p,m,h){this.H=a;this.A(c);this.J(function(a,c){a||(this.r(d),this.g=c,this.C(q),this.z(p),this.model=new (f.model.aa(this))({_id:"PENGO.client.plugins.game.gameRankings.module.Module",texts:c}),this.j=f.controller(this),this.K(t),this.o=f.view.Y(this,
this.M),this.D=f.view.X(this,this.M),this.view=new this.o({model:this.model,viewsMgr:(new b.bbWrappers.viewsManager.ViewsManager).addCallback(this.j.ca)}),this.h.addCartView(this.view),this.j.Z());b.util.callback.call(m,h||this,a)},this)},stop:function(){this.view!==e&&(this.view.remove(),this.view=e);this.C(e);this.z(e);this.r(e);this.o=e;this.K(e);this.g=this.model=this.j=e;this.A(e);this.H=e},J:function(a,b){this.n===e||null===this.n||this.n.getTexts(this.la,a,b||this)},I:function(){this.J(function(a,
b){!a&&this.view!==e&&(this.g=b,this.model.fa(b))},this)}};return c};y("PENGO.client.plugins.game.gameRankings.activator");
(function(){function b(){d.off("SERVICE_REGISTERED",b);v=d.getService("igloo.logger")[0];if(!v||!d.getService("igloo.fatal")[0]||!d.getService("languageManager")[0]||!d.getService("igloo.eventsManager")[0]||!d.getService("game.uiManager")[0]||!d.getService("gameRankings.execution")[0]||!d.getService("game.gameManager")[0])d.on("SERVICE_REGISTERED",b);else{g||(g=new m.module(h.templates,h.textsURL));try{g.ea(h.config)}catch(a){d.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:'Setting plugin "'+
d.getPluginId()+'"'})}m.errors.ia=h.config.errorsStore;d.getService("stats")[0]&&g.B(d.getService("stats")[0]);d.on("SERVICE_REGISTERED",f);d.on("SERVICE_UNREGISTERED",c);g.start(v,d.getService("languageManager")[0],d.getService("igloo.eventsManager")[0],d.getService("game.uiManager")[0],d.getService("gameRankings.execution")[0],d.getService("game.gameManager")[0],function(a){a?d.getService("igloo.fatal")[0].handleFatal({Message:'Error "'+a.message+'" while starting plugin "'+d.getPluginId()+'"',
Source:'Starting plugin "'+d.getPluginId()+'"'}):(u={functions:{getConstants:g.W,a:g.j.ga,b:g.j.ja,c:g.j.G},properties:{}},d.register(q,u),d.on("SERVICE_UNREGISTERED",l),d.on("SERVICE_UPDATED",w),d.on("SERVICE_REGISTERED",t))},this)}}function f(a){"stats"===a&&g.B(d.getService(a)[0])}function c(a){"stats"===a&&g.B(d.getService(a)[0])}function a(a,c){u!==e&&d.unregister(q,u);g!==e&&g.stop();d.off("SERVICE_UNREGISTERED",l);d.off("SERVICE_UPDATED",w);if(a&&!c)d.on("SERVICE_REGISTERED",b);else d.off("SERVICE_REGISTERED",
b);p.remove(h.errorsStore)}function l(b){switch(b){case "languageManager":if(g.A(d.getService("languageManager")[0]))return;break;case "game.uiManager":if(g.C(d.getService("game.uiManager")[0]))return;break;case "gameRankings.execution":g.r(d.getService("gameRankings.execution")[0]);return;case "game.gameManager":if(g.z(d.getService("game.gameManager")[0]))return;break;default:return}a(n)}function t(a){switch(a){case "gameRankings.execution":g.r(d.getService("gameRankings.execution")[0])}}var q="game.gameRankings",
d,p,m,h,v,g,u,w=l;window.PENGO.client.plugins.game.gameRankings.activator.activator=function(c,f){p=c.pengoError.pengoError.storage;return{start:function(a,c){d=a;h=c;m=f;p.add(c.config.errorsStore,f.errors.U);b()},stop:a}}})();})();
