/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var e=void 0;function p(){return function(){}}var q=this;function w(a){a=a.split(".");var d=q;!(a[0]in d)&&d.execScript&&d.execScript("var "+a[0]);for(var h;a.length&&(h=a.shift());)d=d[h]?d[h]:d[h]={}};w("PENGO.client.plugins.paymentsMgr.module");
window.PENGO.client.plugins.paymentsMgr.module.resolve=function(a,d){function h(){this.b=this.g=this.e=e;this.a={};this.s=p()}var k=a.util.callback,m=a.pengoError.pengoError.StoredPengoError,n={};h.prototype={p:function(){return{MPG:"mpg",PYL:"pYL",FTM:"ftM",FTM_CM:"ftM_cm",G2A:"G2a"}},q:function(a,f){this.e=a;if(f===e)throw new m(this.e,"mod:conf#1");if(f.remoteService===e)throw new m(this.e,"mod:conf#2",["remoteService"]);if("string"!==typeof f.remoteService)throw new m(this.e,"mod:conf#3",["remoteService"]);
this.a.remoteService=f.remoteService},f:function(a,f,b){this.b!==e&&this.b.isServiceAvailable(this.a.remoteService)&&this.b.unbind(this.a.remoteService,["new"],function(){this.b.call(this.a.remoteService,"unsubscribe",e,e,p(),this)},this);this.b=a;this.b!==e?this.b.call(this.a.remoteService,"subscribe",e,e,function(a,d){a||(this.a.maxResSize=d.config.maxResSize,this.a.maxStorageSize=d.config.maxStorageSize,this.b.bind(this.a.remoteService,{update:{callback:p(),context:this}},e,function(c){k.call(f,
b,c)},this))},this):k.call(f,b);k.call(f,b)},i:function(a){if(this.d!==a){if(this.d)try{this.d.removeEvents(n)}catch(d){this.g.warn("Error "+d+" while removing events when changing events manager")}(this.d=a)&&this.d.registerEvents(n)}return this.d!==e},start:function(a,f,b,g,h){this.g=a;this.f(f,function(a){a||(this.i(b),this.h=new d.model(this.b.getServiceProtocolConstants(this.a.remoteService)),this.c=new d.controller(this.h,this.a,this.b));k.call(g,h,a)},this)},stop:function(){this.h=this.c=e;
this.i(e);this.f(e);this.g=e}};return h};w("PENGO.client.plugins.paymentsMgr.controller");
window.PENGO.client.plugins.paymentsMgr.controller.resolve=function(a){var d=a.util.callback;return function(a,k,m){var n=m.getServiceProtocolConstants(k.remoteService);return{l:function(){return n},k:function(a,f,b,g){m.call(k.remoteService,"getPaymentGateways",{pVersion:1,selector:a,fields:f},e,function(a,c){d.call(b,g,a,c)},this)},m:function(a,f,b,g,h){m.call(k.remoteService,"pay",{pg:a,order:f,project:b},e,function(a,b){d.call(g,h,a,b)},this)},n:function(a,f,b,g){m.call(k.remoteService,"payAsDeveloper",
{pg:a,order:f},e,function(a,c){d.call(b,g,a,c)},this)},o:function(a,f,b,g){m.call(k.remoteService,"payTrackLost",{pg:a,orderId:f},e,function(a,c){d.call(b,g,a,c)},this)},t:p(),u:p()}}};w("PENGO.client.plugins.paymentsMgr.model");window.PENGO.client.plugins.paymentsMgr.model.resolve=function(){function a(){}a.prototype={};return a};w("PENGO.client.plugins.paymentsMgr.errors");window.PENGO.client.plugins.paymentsMgr.errors.resolve=function(a){return{r:e,j:{"mod:conf#1":{msg:!1,code:a.pengoError.codes.codes.NOT_FOUND},"mod:conf#2":{msg:!1,code:a.pengoError.codes.codes.NOT_FOUND},"mod:conf#3":{msg:!1,code:a.pengoError.codes.codes.INVALID_TYPE},"ct:vgid#1":{msg:!1,code:a.pengoError.codes.codes.INVALID_DATA},"ct:rget#1":{msg:!1,code:a.pengoError.codes.codes.UNEXPECTED}}}};w("PENGO.client.plugins.paymentsMgr.staticOps");window.PENGO.client.plugins.paymentsMgr.staticOps.resolve=function(){return{}};w("PENGO.client.plugins.paymentsMgr.activator");
(function(){function a(b){b===g.config.remoteService&&(c.off("REMOTE_SERVICE_AVAILABLE",a),h())}function d(a){a===g.config.remoteService&&(c.off("REMOTE_SERVICE_UNAVAILABLE",d),k(!0,!0))}function h(){b.off("SERVICE_REGISTERED",h);t=b.getService("igloo.logger")[0];c=b.getService("net")[0];if(!t||!c||!b.getService("igloo.fatal")[0]||!b.getService("igloo.eventsManager")[0])b.on("SERVICE_REGISTERED",h);else if(c.isServiceAvailable(g.config.remoteService)){c.on("REMOTE_SERVICE_UNAVAILABLE",d);l===e&&(l=
new s.module);try{l.q(g.config.errorsStore,g.config)}catch(f){b.getService("igloo.fatal")[0].handleFatal({Message:f.message,Source:"Setting plugin '"+b.getPluginId()+"'"});return}s.errors.r=g.config.errorsStore;l.start(t,c,b.getService("igloo.eventsManager")[0],function(a){a?b.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"Starting plugin '"+b.getPluginId()+"'"}):(r={functions:{getProtocolConstants:l.c.l,getPaymentGateways:l.c.k,getPGModes:l.p,pay:l.c.m,payAsDeveloper:l.c.n,payTrackLost:l.c.o},
properties:{}},b.register(n,r),b.on("SERVICE_UNREGISTERED",m),b.on("SERVICE_UPDATED",v))},this)}else c.on("REMOTE_SERVICE_AVAILABLE",a)}function k(k,u){r!==e&&(b.unregister(n,r),r=e);l!==e&&l.stop();if(c!==e)if(!k||!u)c.off("REMOTE_SERVICE_AVAILABLE",a),c.off("REMOTE_SERVICE_UNAVAILABLE",d);else if(u)c.on("REMOTE_SERVICE_AVAILABLE",a);b.off("SERVICE_UNREGISTERED",m);b.off("SERVICE_UPDATED",v);if(k&&!u)b.on("SERVICE_REGISTERED",h);else b.off("SERVICE_REGISTERED",h);f.remove(g.config.errorsStore)}function m(f){switch(f){case "net":if(b.getService("net")[0]!==
c&&(c!==e&&(c.off("REMOTE_SERVICE_UNAVAILABLE",d),c.off("REMOTE_SERVICE_AVAILABLE",a)),l.f(e),c=b.getService("net")[0],c!==e)){if(c.isServiceAvailable(g.config.remoteService)&&c.isServiceAvailable(g.config.remoteService))l.f(c,function(a){if(a)b.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"When unregistered service '"+f+"', plugin: '"+b.getPluginId()+"'"});else c.on("REMOTE_SERVICE_UNAVAILABLE",d)});else c.on("REMOTE_SERVICE_AVAILABLE",a);return}break;default:return}k(!0)}var n=
"paymentsMgr",s,f,b,g,t,c,l,r,v=m;window.PENGO.client.plugins.paymentsMgr.activator.activator=function(a,c){f=a.pengoError.pengoError.storage;return{start:function(a,d){b=a;g=d;s=c;f.add(d.config.errorsStore,c.errors.j);h()},stop:k}}})();})();
