/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var f=void 0;Math.random();var g;
g=function(d){function h(a){var b=this;h.super_.constructor.call(this,k,s,a);this.h=function(a,c){b.addView(new l({el:a,model:new m({_id:"PENGO.client.plugins.game.uiManager.uiManager"}),viewsMgr:new d.bbWrappers.viewsManager.ViewsManager}),c)};this.f=function(a){b.addView(a)};this.e=function(a){b.addView(a)};this.g=function(a){b.addView(a)};this.o=function(a){$("div#SideView #SideViewContent").children().hide();$("div#SideView #SideViewContent").children("#"+a).show();$("div#SideView").show();$("div#SideView").addClass("shown")};
this.k=function(){$("div#SideView ").hide();$("div#SideView #SideViewContent").children().hide();$("div#SideView").removeClass("shown")};this.n=function(a,b){for(var d=$("#pengoApp > #NotifView #notificationContainer"),c=d.find(".notification-text"),n=0;n<c.length;n+=1)"0"===$(c[n]).css("opacity")&&$(c[n]).detach();d.append('<div class="notification-text <%= notifType %>"> <span class="icon"></span> <span><%= notifText %></span> \x3c!--  <div id="cancel" class="notification-close has-tooltip"><i class="toolbar-remove"></i> <div class="help">Close</div> </div> --\x3e </div> '.replace("<%= notifType %>",
b).replace("<%= notifText %>",a))};$("body").on("contextmenu",function(){return!1}).attr("tabindex","-1");$("div#game").on("touchstart",c);$("div#game").on("touchcancel",c);$("div#game").on("touchend",c);$("div#game").on("touchmove",c);$("div#game").on("mouseup",c);if(window.top===window.self)$("div#game").on("mousedown",c);$("div#game").on("click",c);$("div#game").on("dblclick",c);$("div#game").on("mouseover",c);$("div#game").on("mouseout",c);$(document).on("keydown",function(a){"BODY"===(a.target||
a.srcElement).nodeName&&a.preventDefault()});p.getItem("W5CookiePolicyAccepted",function(a,c){try{b.b=c,b.b=JSON.parse(b.b)}catch(d){b.b=!1}$("div#pengoApp").find("footer .notify.cookies input").one("click",function(){$("div#pengoApp").find("footer .notify.cookies").remove();b.a.emit("COOKIEPOLICY_ACCEPTED");p.setItem("W5CookiePolicyAccepted",JSON.stringify(!0))})})}function c(a){a.preventDefault()}function s(a){switch(a.get("view").model.id){case "PENGO.client.plugins.game.uiManager.uiManager":$(this.el).find(a.get("view").el).remove();
break;case "PENGO.client.plugins.shoppingCart.module.Module":$(this.el).find(a.get("view").el).remove();break;case "PENGO.client.plugins.game.gameRankings.module.Module":$(this.el).find(a.get("view").el).remove();break;case "PENGO.client.plugins.game.accountManager.module.Module":$(this.el).find(a.get("view").el).remove();break;case "PENGO.client.plugins.netManager.wsManager.WSManager":$(this.el).find(a.get("view").el).remove()}}function k(a){switch(a.get("view").model.id){case "PENGO.client.plugins.game.uiManager.uiManager":$(this.el).find("div#game").append(a.get("view").el);
break;case "PENGO.client.plugins.shoppingCart.module.Module":$(this.el).find("div#CartView").append(a.get("view").el);break;case "PENGO.client.plugins.game.gameRankings.module.Module":$(this.el).find("div#RankingsView").append(a.get("view").el);break;case "PENGO.client.plugins.game.accountManager.module.Module":$(this.el).find("div#account").prepend(a.get("view").el);break;case "PENGO.client.plugins.netManager.wsManager.WSManager":$(this.el).find("div#account").append(a.get("view").el)}}var p=d.storage.local.getInstance(),
m=d.bbWrappers.pengoModel.PengoModel.extend({}),b={COOKIEPOLICY_ACCEPTED:"cookiepolicy/accepted"},l=d.bbWrappers.pengoView.PengoView.extend({initialize:function(){this.firstRender()}});h.prototype={l:function(a){this.i=a;(!0===this.b||!0!==this.i.showCookiePolicyAcceptance)&&$("div#pengoApp").find("footer .notify.cookies").remove()},d:function(a){this.j=a;return this.j!==f},m:function(a){this.a!==a&&(this.a=a,this.a.registerEvents(b));return this.a!==f},c:function(a){this.p=a;!0===this.b&&this.a.emit("COOKIEPOLICY_ACCEPTED");
return this.p!==f}};d.inheritance.inheritance.inherits(h,d.uiManager.uiManager.UIManager);return h};var q="PENGO client plugins game uiManager activator".split(" "),r=this;!(q[0]in r)&&r.execScript&&r.execScript("var "+q[0]);for(var u;q.length&&(u=q.shift());){var v;if(v=!q.length)v=!1;v?r[u]=f:r=r[u]?r[u]:r[u]={}}
(function(){function d(){b.off("SERVICE_REGISTERED",d);if(w=b.getService("igloo.logger")[0])if(e=b.getService("uiManager")[0])if(x=b.getService("igloo.eventsManager")[0])a||(a=new m(l.templates)),a.setLogger(w),a.l(l.config),a.d(e),a.m(x),b.getService("stats")[0]&&a.c(b.getService("stats")[0]),b.on("SERVICE_REGISTERED",h),b.on("SERVICE_UNREGISTERED",c),a.start(),t={functions:{addView:a.h,showWaitView:e.showWaitView,hideWaitView:e.hideWaitView,showDomElemWaitView:e.showDomElemWaitView,hideDomElemWaitView:e.hideDomElemWaitView,
showModalView:e.showModalView,hideModalView:e.hideModalView,showMessageDialog:e.showMessageDialog,showNotification:a.n,showSideView:a.o,hideSideView:a.k,addCartView:a.f,addAccountView:a.e,addConnectionView:a.g},properties:{}},b.register(p,t),b.on("SERVICE_UNREGISTERED",k),b.on("SERVICE_UPDATED",y);else b.on("SERVICE_REGISTERED",d);else b.on("SERVICE_REGISTERED",d);else b.on("SERVICE_REGISTERED",d)}function h(c){"stats"===c&&a.c(b.getService(c)[0])}function c(c){"stats"===c&&a.c(b.getService(c)[0])}
function s(c){a&&a.stop();t&&b.unregister(p,t);b.off("SERVICE_UNREGISTERED",k);b.off("SERVICE_UPDATED",y);if(c)b.on("SERVICE_REGISTERED",d);else b.off("SERVICE_REGISTERED",d)}function k(c){switch(c){case "uiManager":if(b.getService("uiManager")[0]!==e&&(a.d(f),e=b.getService("uiManager")[0],e!==f))return;break;default:return}s(!0)}var p="game.uiManager",m,b,l,a,w,e,x,t,y=k;window.PENGO.client.plugins.game.uiManager.activator.activator=function(a){return{start:function(c,e){b=c;l=e;if(!m){if(!g)throw new a.pengoError.pengoError.PengoError("'PENGO.client.plugins.languageManager.languageManager' can't be resolved.",
a.pengoError.codes.NOT_FOUND);m=g(a);a.require.remove.deleteByName("PENGO.client.plugins.game.uiManager.uiManager")}d()},stop:s}}})();})();
