/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var e=void 0,n=!1,p=this;function s(d){d=d.split(".");var c=p;!(d[0]in c)&&c.execScript&&c.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)c=c[f]?c[f]:c[f]={}}Math.random();s("PENGO.client.plugins.uitools.slideshow.module");
window.PENGO.client.plugins.uitools.slideshow.module.resolve=function(d,c){function f(a,b){var l=this;this.T=this.B=e;this.z=a;this.R=b;this.view=this.model=this.b=this.W=this.D=this.f=this.t=this.l=this.k=this.d=e;this.n=function(a){return l.b.n(a)};this.g=function(a){return l.b.g(a)};this.e=function(a){return l.b.e(a)};this.j=function(a,b){l.b.j(a,b)}}f.prototype={J:function(a){this.B=a.errorsStore;this.S=a.wimilogo},s:function(a){this.f=a;return this.f!==e},w:function(a){a===e?this.q!==e&&(this.q.off("LANGUAGE_UPDATED",
this.u),this.D=e):(this.q=a,this.q.on("LANGUAGE_UPDATED",this.u,this))},start:function(a,b,l,m,g){this.t=a;this.s(b);this.v(function(a,b){a||(this.d=b,this.model=new (c.model.H(this))({_id:"PENGO.client.plugins.uitools.slideshow.module.Module",texts:b}),this.b=c.controller(this),this.w(l),this.k=c.view.F(this,this.z),this.l=c.view.G(this,this.z),this.view=new this.k({model:this.model,viewsMgr:(new d.bbWrappers.viewsManager.ViewsManager).addCallback(this.b.I)}));d.util.callback.call(m,g||this,a)},
this)},stop:function(){this.view!==e&&(this.view.remove(),this.view=e);this.k=this.l=e;this.w(e);this.d=this.model=this.b=e;this.s(e);this.t=e},v:function(a,b){this.f===e||null===this.f||this.f.getTexts(this.R,a,b||this)},u:function(){this.v(function(a,b){!a&&this.view!==e&&(this.d=b,this.model.h(b))},this)}};return f};s("PENGO.client.plugins.uitools.slideshow.errors");window.PENGO.client.plugins.uitools.slideshow.errors.resolve=function(d){return{P:e,C:{"md:lang#1":{msg:n,code:d.pengoError.codes.codes.NOT_FOUND}}}};s("PENGO.client.plugins.uitools.slideshow.controller");window.PENGO.client.plugins.uitools.slideshow.controller.resolve=function(){return function(d){return{I:function(){},n:function(c){return d.model.get("slideshows").m(c)},g:function(){},e:function(c){return d.view.e(c)},j:function(c,f){d.view.j(c,f)}}}};s("PENGO.client.plugins.uitools.slideshow.model");
window.PENGO.client.plugins.uitools.slideshow.model.resolve=function(d){var c=d.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e,texts:e,pages:new b}},h:function(a){this.set({texts:a})}}),f=Backbone.Collection.extend({model:c,r:1,h:function(a){for(var b=0;b<this.length;b++)this.at(b).h(a)},m:function(a){var b=new c({_id:this.r++}),g;for(g in a)b.get("pages").A(a[g]);this.add(b);return b.id}}),a=d.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e,text:e,
imageUrl:e,html:e}},h:function(a){this.set({texts:a})}}),b=Backbone.Collection.extend({model:a,r:10001,A:function(b){b=new a({_id:this.r++,text:b.text,imageUrl:b.imageUrl,html:b.html});this.add(b);return b.id}});return{H:function(){return d.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{_id:e,texts:e,slideshows:new f}},h:function(a){this.set("texts",a)}})}}};s("PENGO.client.plugins.uitools.slideshow.view");
window.PENGO.client.plugins.uitools.slideshow.view.resolve=function(d){return{F:function(c,f){return d.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.p();this.template=_.template(f.module);this.model.set({texts:c.d},{O:!0});this.firstRender()},p:function(){this.listenTo(this.model.get("slideshows"),"add",this.m)},o:function(){},render:function(){this.$el.html(this.template());this.o();this.addControllerCallbacks();return this},m:function(a){new c.l({model:a,viewsMgr:this.options.viewsMgr,
V:this})},e:function(a){for(var b=this.options.viewsMgr.getAllViews(),c=e,d=e,c=0;c<b.length;c++)b[c].model.id===a&&(d=b[c]);return d},j:function(a,b){function c(){setTimeout(function(){0<$("#pengoApp").find(f.$el).length&&f.M();c()},b)}for(var d=this.options.viewsMgr.getAllViews(),g=e,f=e,g=0;g<d.length;g++)d[g].model.id===a&&(f=d[g]);c()}})},G:function(c,f){return d.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{"class":"slideshowView"},a:e,i:n,initialize:function(){this.p();this.template=
_.template(f.slideshow);this.Q=_.template(f.slideshowDot);this.model.set({texts:c.d},{O:!0});this.firstRender()},p:function(){this.listenTo(this.model,"remove",this.g)},o:function(){var a=this;this.$el.find(".icon-arrow-left").on("click",function(){a.N()});this.$el.find(".icon-arrow-right").on("click",function(){a.L()});this.$el.find(".icon-dot").on("click",function(b){a.K(b)})},render:function(){this.$el.attr("id",this.model.id);this.$el.html(this.template({wimilogo:c.S}));0<this.model.get("pages").length&&
this.c(0);for(var a=0;a<this.model.get("pages").length;a+=1)this.$el.find(".action-bar").append(this.Q({id:a})),0===a&&this.$el.find(".action-bar").children().addClass("selected");this.$el.find("label").append(c.d.dontShowWelcome);this.o();this.addControllerCallbacks();return this},g:function(){this.options.viewsMgr.removeView(this.model.get("_id"),this.U);this.$el.detach()},N:function(){0<this.a&&this.c(this.a-1)},L:function(){this.a<this.model.get("pages").length-1&&this.c(this.a+1)},M:function(){this.a<
this.model.get("pages").length-1?this.c(this.a+1):this.c(0)},K:function(a){this.c(parseInt(a.target.id))},c:function(a){if(a!==this.a&&this.i===n){var b=this,c=e,d=this.model.get("pages").at(a),g=e,f=e,h=e,k=e;this.i=!0;d!==e&&(c=$("<div></div>"),c.addClass("slidePage"),d.get("imageUrl")!==e&&c.css({"background-image":"url("+d.get("imageUrl")+")","background-size":"contain","background-repeat":"no-repeat","background-position":"center center"}),d.get("html")!==e&&c.append(d.get("html")),this.a===
e?(this.$el.find(".slidesWrap").append(c),this.i=n):a>this.a?(g=this.$el.find(".slideAnim"),f=this.$el.find(".slideAnim :nth-child(1)"),h=this.$el.find(".slideAnim :nth-child(2)"),k=b.$el.find(".slidesWrap"),g.show(),f.append(k.children()),h.append(c),g.bind("webkitAnimationEnd animationend msAnimationEnd oAnimationEnd animationEnd",function(){k.empty().append(h.children());g.hide();f.empty();h.empty();g.removeClass("slideToLeft");g.unbind("webkitAnimationEnd animationend msAnimationEnd oAnimationEnd animationEnd");
b.i=n}),g.addClass("slideToLeft")):a<this.a&&(g=this.$el.find(".slideAnim"),f=this.$el.find(".slideAnim :nth-child(1)"),h=this.$el.find(".slideAnim :nth-child(2)"),k=b.$el.find(".slidesWrap"),g.addClass("initiallyLeft"),g.show(),f.append(c),h.append(k.children()),g.bind("webkitAnimationEnd animationend msAnimationEnd oAnimationEnd animationEnd",function(){k.empty().append(f.children());g.hide();g.removeClass("initiallyLeft");f.empty();h.empty();g.removeClass("slideToRight");g.unbind("webkitAnimationEnd animationend msAnimationEnd oAnimationEnd animationEnd");
b.i=n}),g.addClass("slideToRight")),0===a?this.$el.find(".icon-arrow-left").addClass("hidden"):this.$el.find(".icon-arrow-left").removeClass("hidden"),a===this.model.get("pages").length-1?this.$el.find(".icon-arrow-right").addClass("hidden"):this.$el.find(".icon-arrow-right").removeClass("hidden"),this.a=a,this.$el.find("article header h2").text(d.get("text")),this.$el.find(".action-bar .selected").removeClass("selected"),this.$el.find(".action-bar :nth-child("+(a+1)+")").addClass("selected"))}}})}}};s("PENGO.client.plugins.uitools.slideshow.activator");
(function(){function d(){b.off("SERVICE_REGISTERED",d);q=b.getService("igloo.logger")[0];if(!q||!b.getService("igloo.fatal")[0]||!b.getService("languageManager")[0]||!b.getService("igloo.eventsManager")[0])b.on("SERVICE_REGISTERED",d);else{h||(h=new m.module(g.templates,g.textsURL));try{h.J(g.config)}catch(c){b.getService("igloo.fatal")[0].handleFatal({Message:c.message,Source:'Setting plugin "'+b.getPluginId()+'"'})}m.errors.P=g.config.errorsStore;h.start(q,b.getService("languageManager")[0],b.getService("igloo.eventsManager")[0],
function(c){c?b.getService("igloo.fatal")[0].handleFatal({Message:'Error "'+c.message+'" while starting plugin "'+b.getPluginId()+'"',Source:'Starting plugin "'+b.getPluginId()+'"'}):(k={functions:{createSlideshow:h.n,removeSlideshow:h.g,getSlideshowView:h.e,startAutoSlide:h.j},properties:{}},b.register(a,k),b.on("SERVICE_UNREGISTERED",f),b.on("SERVICE_UPDATED",r))},this)}}function c(c,m){k!==e&&b.unregister(a,k);h!==e&&h.stop();b.off("SERVICE_UNREGISTERED",f);b.off("SERVICE_UPDATED",r);if(c&&!m)b.on("SERVICE_REGISTERED",
d);else b.off("SERVICE_REGISTERED",d);l.remove(g.errorsStore)}function f(a){switch(a){case "languageManager":if(h.s(b.getService("languageManager")[0]))return;break;default:return}c(!0)}var a="uitools.slideshow",b,l,m,g,q,h,k,r=f;window.PENGO.client.plugins.uitools.slideshow.activator.activator=function(a,f){l=a.pengoError.pengoError.storage;return{start:function(a,c){b=a;g=c;m=f;l.add(c.config.errorsStore,f.errors.C);d()},stop:c}}})();})();
