/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var e=void 0,t=this;function A(f){f=f.split(".");var h=t;!(f[0]in h)&&h.execScript&&h.execScript("var "+f[0]);for(var b;f.length&&(b=f.shift());)h=h[b]?h[b]:h[b]={}};A("PENGO.client.plugins.virtualGoods.staticOps");window.PENGO.client.plugins.virtualGoods.staticOps.resolve=function(){return{}};A("PENGO.client.plugins.virtualGoods.module");
window.PENGO.client.plugins.virtualGoods.module.resolve=function(f,h){function b(){this.d=this.c=this.h=e;this.b={};this.J=function(){}}var g=f.util.callback,q=f.pengoError.pengoError.StoredPengoError,p={},n=e;b.prototype={G:function(b){n&&n(b)},D:function(b){n=b},F:function(b,g){this.h=b;if(g===e)throw new q(this.h,"mod:conf#1");this.b.remoteEditionService=g.remoteEditionService;this.b.remoteExecutionService=g.remoteExecutionService;this.b.remoteOrdersService=g.remoteOrdersService},g:function(b,
h,f){function l(){c.d=b;c.d!==e&&d!==e?c.d.bind(c.b.remoteOrdersService,{vgAmountUpdated:{callback:c.a.f,context:c}},e,function(l){l!==e?(c.c.error("Error "+l+" binding notification for service "+config.remoteOrdersService),g.call(h,f)):b.call(c.b.remoteOrdersService,"listenToVGAmountUpdated",{type:d.type,projectId:d.l},e,function(b,a){(b||a.result!==c.a.i().results.OK)&&c.c.error("There was an error on vg update start listening");g.call(h,f)},c)},c):g.call(h,f)}var d,c=this;this.a!==e&&(d=this.a.n());
this.d!==e?d!==e?this.d.call(this.b.remoteOrdersService,"stopListeningToVGAmountUpdated",{type:d.type,projectId:d.l},e,function(){c.d.unbind(this.b.remoteOrdersService,{vgAmountUpdated:{callback:c.a.f,context:c}},function(b){b!==e&&c.c.error("Error "+b+" unbinding notification for service "+config.remoteOrdersService);l()},c)},this):l():l()},m:function(b){if(this.e!==b){if(this.e)try{this.e.removeEvents(p)}catch(g){this.c.warn("Error "+g+" while removing events when changing events manager")}(this.e=
b)&&this.e.registerEvents(p)}return this.e!==e},start:function(b,f,q,l,d){this.c=b;this.g(f,function(b){b||(this.m(q),this.a===e&&(this.a=new h.controller(this.b,this.d,this.c)));g.call(l,d,b)},this)},stop:function(){this.m(e);this.g(e);this.c=e}};return b};A("PENGO.client.plugins.virtualGoods.controller");
window.PENGO.client.plugins.virtualGoods.controller.resolve=function(f){var h=f.util.callback;return function(b,g,f){function p(a){c!==e&&d!==e&&g.call(b.remoteOrdersService,"stopListeningToVGAmountUpdated",{type:c,projectId:d},e,function(){g.unbind(b.remoteOrdersService,{vgAmountUpdated:{callback:k.f,context:this}},function(c){c!==e?f.error("Error "+c+" unbinding notification for service "+b.remoteOrdersService):1===m?n(a):m=0},this)},this)}function n(a){d=a.projectId;c=a.type;g.bind(b.remoteOrdersService,
{vgAmountUpdated:{callback:k.f,context:this}},e,function(s){s!==e?f.error("Error "+s+" binding notification for service "+b.remoteOrdersService):1===m&&g.call(b.remoteOrdersService,"listenToVGAmountUpdated",{type:c,projectId:d},e,function(b,c){b||c.result!==r.results.OK?f.error("There was an error on vg update start listening"):2===m?p(a):m=3},this)},this)}var v,w,r,l={},d,c,m=0;b.remoteEditionService&&(v=g.getServiceProtocolConstants(b.remoteEditionService));b.remoteExecutionService&&(w=g.getServiceProtocolConstants(b.remoteExecutionService));
b.remoteOrdersService&&(r=g.getServiceProtocolConstants(b.remoteOrdersService));var k={t:function(){return v},s:function(a,c,d,f){g.call(b.remoteEditionService,"readVGs",{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},k:function(a,c,d){g.call(b.remoteEditionService,"getTexts",{lang:a},e,function(a,b){h.call(c,d,a,b)},this)},create:function(a,c,d){g.call(b.remoteEditionService,"createVG",a,e,function(a,b){h.call(c,d,a,b)},this)},update:function(a,c,d,f){g.call(b.remoteEditionService,
"updateVGSettings",{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},rename:function(a,c,d,f){g.call(b.remoteEditionService,"renameVG",{selector:a,name:c},e,function(a,b){h.call(d,f,a,b)},this)},j:function(a,c,d){g.call(b.remoteEditionService,"getTypePrices",a,e,function(a,b){h.call(c,d,a,b)},this)},remove:function(a,c,d){g.call(b.remoteEditionService,"removeVG",a,e,function(a,b){h.call(c,d,a,b)},this)},v:function(){return w},u:function(a,c,d,f){g.call(b.remoteExecutionService,"readVG",
{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},z:function(a,c,d,f){g.call(b.remoteExecutionService,"getProjectVGs",{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},i:function(){return r},B:function(a,c,d,f){g.call(b.remoteOrdersService,"getUserPurchasableVGs",{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},r:function(a,c,d,f){g.call(b.remoteOrdersService,"getDeveloperPurchasableVGs",{selector:a,fields:c},e,function(a,b){h.call(d,f,a,b)},this)},w:function(a,
c){g.call(b.remoteOrdersService,"getMaxOrderTotalPrice",{type:"game"},e,function(b,d){h.call(a,c,b,d)},this)},o:function(a,c,d,f){g.call(b.remoteOrdersService,"typeSpecificOp",{operation:"consumeVG",type:"game",data:{selector:a,amount:c}},e,function(a,b){h.call(d,f,a,b)},this)},q:function(a,c,d){g.call(b.remoteOrdersService,"getUserVGAmount",a,e,function(a,b){h.call(c,d,a,b)},this)},A:function(a,c){g.call(b.remoteOrdersService,"getTaxInfo",{type:"game"},e,a,c)},C:function(a,b){a._id!==e&&b!==e&&(0===
m?(n(a),m=1):2===m&&(m=1),l[a._id]||(l[a._id]=[]),-1===l[a._id].indexOf(b)&&l[a._id].push(b))},I:function(a,b){var c;a._id!==e&&b!==e&&l[a._id]!==e&&(c=l[a._id].indexOf(b),-1!==c&&(l[a._id].splice(c,1),0===l[a._id].length&&(delete l[a._id],0===Object.keys(l).length&&(3===m&&p(a),m=2))))},f:function(a){for(var b in a.virtualGoods)if(l[b]!==e)for(var c=0;c<l[b].length;c++)l[b][c](a.virtualGoods[b])},n:function(){if(0<Object.keys(l).length)return{type:c,l:d}}};return k}};A("PENGO.client.plugins.virtualGoods.model");window.PENGO.client.plugins.virtualGoods.model.resolve=function(){function f(){}f.prototype={};return f};A("PENGO.client.plugins.virtualGoods.errors");window.PENGO.client.plugins.virtualGoods.errors.resolve=function(f){return{H:e,p:{"mod:conf#1":{msg:!1,code:f.pengoError.codes.codes.NOT_FOUND},"mod:conf#2":{msg:!1,code:f.pengoError.codes.codes.NOT_FOUND},"mod:conf#3":{msg:!1,code:f.pengoError.codes.codes.INVALID_TYPE},"ct:vgid#1":{msg:!1,code:f.pengoError.codes.codes.INVALID_DATA},"ct:rget#1":{msg:!1,code:f.pengoError.codes.codes.UNEXPECTED}}}};A("PENGO.client.plugins.virtualGoods.activator");
(function(){function f(a){if(c.config.remoteEditionService&&a===c.config.remoteEditionService||c.config.remoteExecutionService&&a===c.config.remoteExecutionService||c.config.remoteOrdersService&&a===c.config.remoteOrdersService)k.off("REMOTE_SERVICE_AVAILABLE",f),b()}function h(a){if(c.config.remoteEditionService&&a===c.config.remoteEditionService||c.config.remoteExecutionService&&a===c.config.remoteExecutionService||c.config.remoteOrdersService&&a===c.config.remoteOrdersService)k.off("REMOTE_SERVICE_UNAVAILABLE",
h),g(!0,!0)}function b(){d.off("SERVICE_REGISTERED",b);m=d.getService("igloo.logger")[0];k=d.getService("net")[0];a===e&&(a=new r.module);u==e&&(u={functions:{showCart:a.G,registerShowShoppingCartFunction:a.D},properties:{}},d.register(w,u));if(!m||!k||!d.getService("igloo.fatal")[0]||!d.getService("igloo.eventsManager")[0])d.on("SERVICE_REGISTERED",b);else if(c.config.remoteEditionService&&!k.isServiceAvailable(c.config.remoteEditionService)||c.config.remoteExecutionService&&!k.isServiceAvailable(c.config.remoteExecutionService)||
c.config.remoteQueryService&&!k.isServiceAvailable(c.config.remoteQueryService))k.on("REMOTE_SERVICE_AVAILABLE",f);else{k.on("REMOTE_SERVICE_UNAVAILABLE",h);try{a.F(c.config.errorsStore,c.config)}catch(g){d.getService("igloo.fatal")[0].handleFatal({Message:g.message,Source:"Setting plugin '"+d.getPluginId()+"'"});return}r.errors.H=c.config.errorsStore;a.start(m,k,d.getService("igloo.eventsManager")[0],function(b){b?d.getService("igloo.fatal")[0].handleFatal({Message:b.message,Source:"Starting plugin '"+
d.getPluginId()+"'"}):(c.config.remoteEditionService&&(x={functions:{get:a.a.s,create:a.a.create,update:a.a.update,rename:a.a.rename,remove:a.a.remove,getPrices:a.a.j,getProtocolConstants:a.a.t,getServerTexts:a.a.k},properties:{}},d.register(n,x)),c.config.remoteExecutionService&&(s={functions:{get:a.a.u,getProjectVGs:a.a.z,getProtocolConstants:a.a.v,getServerTexts:a.a.k},properties:{}},d.register(v,s)),c.config.remoteOrdersService&&(y={functions:{get:a.a.B,getDeveloperPurchasableVGs:a.a.r,getPrices:a.a.j,
consume:a.a.o,getCount:a.a.q,getMaxOrderTotalPrice:a.a.w,getTaxInfo:a.a.A,registerOnCountModified:a.a.C,unregisterOnCountModified:a.a.I,getProtocolConstants:a.a.i},properties:{}},d.register(p,y)),d.on("SERVICE_UNREGISTERED",q),d.on("SERVICE_UPDATED",z))},this)}}function g(g,m){x!==e&&d.unregister(n,x);s!==e&&d.unregister(v,s);y!==e&&d.unregister(p,y);if(k!==e)if(!g||!m)k.off("REMOTE_SERVICE_AVAILABLE",f),k.off("REMOTE_SERVICE_UNAVAILABLE",h);else if(m)k.on("REMOTE_SERVICE_AVAILABLE",f);d.off("SERVICE_UNREGISTERED",
q);d.off("SERVICE_UPDATED",z);if(g)if(m)d.off("SERVICE_REGISTERED",b);else d.on("SERVICE_REGISTERED",b);else u!==e&&(d.unregister(w,u),u=e),a!==e&&a.stop();l.remove(c.config.errorsStore)}function q(b){switch(b){case "net":if(d.getService("net")[0]!==k&&(k!==e&&(k.off("REMOTE_SERVICE_UNAVAILABLE",h),k.off("REMOTE_SERVICE_AVAILABLE",f)),a.g(e),k=d.getService("net")[0],k!==e)){if(c.config.remoteEditionService&&k.isServiceAvailable(c.config.remoteEditionService)||c.config.remoteExecutionService&&k.isServiceAvailable(c.config.remoteExecutionService)||
c.config.remoteOrdersService&&k.isServiceAvailable(c.config.remoteOrdersService))a.g(k,function(a){if(a)d.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"When unregistered service '"+b+"', plugin: '"+d.getPluginId()+"'"});else k.on("REMOTE_SERVICE_UNAVAILABLE",h)});else k.on("REMOTE_SERVICE_AVAILABLE",f);return}break;default:return}g(!0)}var p="virtualGoods.orders",n="virtualGoods.edition",v="virtualGoods.execution",w="virtualGoods.cart",r,l,d,c,m,k,a,s,x,y,u,z=q;window.PENGO.client.plugins.virtualGoods.activator.activator=
function(a,f){l=a.pengoError.pengoError.storage;return{start:function(a,g){d=a;c=g;r=f;l.add(g.config.errorsStore,f.errors.p);b()},stop:g}}})();})();
