/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var h=void 0,k=!0,n=!1,q=this;function t(b){b=b.split(".");var d=q;!(b[0]in d)&&d.execScript&&d.execScript("var "+b[0]);for(var a;b.length&&(a=b.shift());)d=d[a]?d[a]:d[a]={}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.consumeVirtualGood");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.consumeVirtualGood.resolve=function(){function b(a,m,b,f){function l(e,m){var f,b;e?f=3:m.result===d.OK?(b=m.data.amountLeft,f=0):f=m.result===d.KO_TYPE_SPECIFIC_ERROR&&3==m.data.errCode?1:3;a.callOnNextUpdateDraw(function(a){c.consuming=n;b!==h&&(c.outParameters.amountLeft=b);c.fireOutput(f,a)})}var c=new e.runEngine.Blackbox(a,m,b,f,"_consumeVg_key");c.createInParam("virtualGood",0);c.createInParam("outlay",1);c.createOutParam("amountLeft",
0);c.createOutput("done",0);c.createOutput("notEnough",1);c.createOutput("onPrevious",2);c.createOutput("error",3);c.secure=k;c.consuming=n;var d=h,r=e.runEngine.getManager();c.createInput("consume",0,function(a){c.inParameters.virtualGood&&c.inParameters.outlay!==h&&(c.secure&&c.consuming?c.fireOutput(2,a):(d||(d=r.a()),d?(c.consuming=k,r.c(c.inParameters.virtualGood._id,Math.ceil(Math.abs(c.inParameters.outlay)),l)||(c.consuming=n,c.fireOutput(3,a),d=h)):c.fireOutput(3,a)))});return c}function d(a,
e){a.secure=e!==h&&e.S}function a(a){a.consuming=n}var e;return{dependencies:function(g){g.runEngine.blackboxRepository.addBlackboxType("_consumeVg_key",b);g.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_consumeVg_key",a,d);e=g},implementation:{j:b}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.showShoppingCart");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.showShoppingCart.resolve=function(){function b(g,b,d,f){var l=new a.runEngine.Blackbox(g,b,d,f,"_ShowShoppingCart_key");e=a.runEngine.getManager();l.createOutput("shown",0);l.createOutput("closed",1);l.createInput("show",0,function(a){e.g(function(){g.setPauseState(n);g.callOnNextUpdateDraw(function(a){l.fireOutput(1,a)})})&&(g.setPauseState(k),l.fireOutput(0,a))});return l}function d(){e.f()}var a,e;b.prototype={};return{dependencies:function(e){e.runEngine.blackboxRepository.addBlackboxType("_ShowShoppingCart_key",
b);e.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ShowShoppingCart_key",d);a=e},implementation:{l:b}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.virtualGoodListener");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.virtualGoodListener.resolve=function(){function b(a,e,g,b){function s(e){function g(a){e!==h&&(f.outParameters.remainingAmount=e);f.fireOutput(0,a)}c.b&&a.callOnNextUpdateDraw(g)}var f=new d.runEngine.Blackbox(a,e,g,b,"_listenVg_key");f.createInParam("virtualGood",0);f.createOutParam("remainingAmount",0);f.createOutput("updated",0);f.createOutput("error",1);var l=h,c=d.runEngine.getManager(),p=n;f.offListenVG=function(){p&&f.inParameters.virtualGood!==
h&&(l||(l=c.a()),l&&c.i(f.inParameters.virtualGood._id,s));p=n};f.createInput("on",0,function(a){!p&&f.inParameters.virtualGood!==h&&(l||(l=c.a()),l?(p=c.h(f.inParameters.virtualGood._id,s),p||(f.fireOutput(1,a),l=h)):f.fireOutput(1,a))});f.createInput("off",1,f.offListenVG);return f}var d;return{dependencies:function(a){a.runEngine.blackboxRepository.addBlackboxType("_listenVg_key",b);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_listenVg_key",function(a,g){a.offListenVG(g)},
h);d=a},implementation:{m:b}}};t("PENGO.client.shared.runEngine.virtualGoods.manager");
window.PENGO.client.shared.runEngine.virtualGoods.manager.resolve=function(){function b(a,g){this.n=g;var b,d={b:h};for(b in d);Object.defineProperty(this,b,{get:function(){return a.isOnPlay()},enumerable:k,configurable:n})}function d(a,g){return function(b,d){a.b&&g(b,d)}}var a;b.prototype={e:function(e,g){function b(a,c){if(!a&&c.result===d.OK)c.virtualGood&&c.virtualGood.name?g(c.virtualGood,c.virtualGood.name,n):g(h,h,k);else throw"Error getting Virtual Good. "+a;}var d,f={type:"game"};if(e)if(a.virtualGoodsService&&
a.virtualGoodsService.execution)d=a.virtualGoodsService.execution.getProtocolConstants().results,f._id=e,f.projectId=a.GAME_PROPERTIES.id,f.projectVersion=a.GAME_PROPERTIES.version,a.virtualGoodsService.execution.get(f,{},b);else throw"Virtual Goods service not available.";},a:function(){if(a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.getProtocolConstants)return a.virtualGoodsService.orders.getProtocolConstants().results},d:function(e,b){var m={type:"game",_id:e,
projectId:a.GAME_PROPERTIES.id};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.getCount?(a.virtualGoodsService.orders.getCount(m,d(this,b)),k):n},c:function(e,b,m){e={type:"game",_id:e,projectId:a.GAME_PROPERTIES.id,projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.consume?(a.virtualGoodsService.orders.consume(e,b,d(this,m)),k):n},h:function(b,d){var m={type:"game",_id:b,projectId:a.GAME_PROPERTIES.id,
projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.registerOnCountModified?(a.virtualGoodsService.orders.registerOnCountModified(m,d),k):n},i:function(b,d){var m={type:"game",_id:b,projectId:a.GAME_PROPERTIES.id,projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.unregisterOnCountModified?(a.virtualGoodsService.orders.unregisterOnCountModified(m,
d),k):n},g:function(b){return a.virtualGoodsService&&a.virtualGoodsService.cart&&a.virtualGoodsService.cart.showCart?(a.virtualGoodsService.cart.showCart(b),k):n},f:function(){return a.virtualGoodsService&&a.virtualGoodsService.cart&&a.virtualGoodsService.cart.hideCart?(a.virtualGoodsService.cart.hideCart(),k):n}};b.prototype.getVirtualGood=b.prototype.e;return{dependencies:function(b){a=b;b.runEngine.paramManager.addParamType("_VG_","VirtualGood",{},n)},implementation:{Manager:b,config:{}}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.getVirtualGoodAmount");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.getVirtualGoodAmount.resolve=function(){function b(a,b,d,f){function l(b,d){var e,f;b?e=2:d.result===p.OK?(f=d.amount,e=0):e=2;a.callOnNextUpdateDraw(function(a){c.getting=n;f!==h&&(c.outParameters.amount=f);c.fireOutput(e,a)})}var c=new e.runEngine.Blackbox(a,b,d,f,"_GetVgAmount_key");c.createInParam("virtualGood",0);c.createOutParam("amount",0);c.createOutput("done",0);c.createOutput("onPrevious",1);c.createOutput("error",2);c.secure=k;
c.getting=n;var p=h,r=e.runEngine.getManager();c.createInput("get",0,function(a){c.inParameters.virtualGood&&c.outParameters.amount!==h&&(c.secure&&c.getting?c.fireOutput(1,a):(p||(p=r.a()),p?(c.getting=k,e.runEngine.getManager().d(c.inParameters.virtualGood._id,l)||(c.getting=n,c.fireOutput(2,a),p=h)):c.fireOutput(2,a)))});return c}function d(a,b){a.secure=b!==h&&b.S}function a(a){a.getting=n}var e;return{dependencies:function(g){g.runEngine.blackboxRepository.addBlackboxType("_GetVgAmount_key",
b);g.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetVgAmount_key",a,d);e=g},implementation:{k:b}}};})();
