/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var g=void 0,q=this;function t(b){b=b.split(".");var h=q;!(b[0]in h)&&h.execScript&&h.execScript("var "+b[0]);for(var l;b.length&&(l=b.shift());)h=h[l]?h[l]:h[l]={}};t("PENGO.client.plugins.game.loader.errors");window.PENGO.client.plugins.game.loader.errors.resolve=function(b){return{t:g,n:{"ldr:cfg#1":{msg:!1,code:b.pengoError.codes.codes.INVALID_DATA},"ldr:gr#1":{msg:!1,code:b.pengoError.codes.codes.NOT_FOUND},"ldr:gr#2":{msg:!1,code:b.pengoError.codes.codes.UNEXPECTED},"ldr:st#1":{msg:!1,code:b.pengoError.codes.codes.UNEXPECTED}}}};t("PENGO.client.plugins.game.loader.loader");
window.PENGO.client.plugins.game.loader.loader.resolve=function(b){function h(){var a=this;this.f=this.e=this.b=this.c=g;this.i=[];this.a=g;this.p=function(c,m){b.require.require.requireJSON(a.q(),function(e,b){if(!e)try{b=JSON.parse(b)}catch(d){b=g,e=d}c.call(m||a,e,b)})};this.r=function(c,m,e,k){if(a.b[c]===g)e.call(k||a,new l(a.c.errorsStore,"ldr:gr#1",[c]),c);else switch(a.b[c][0]){case g:e.call(k||a,new l(a.c.errorsStore,"ldr:gr#1",[c]),c);break;case a.d().IMAGE:case a.d().AUDIO:m||(m={});m.onerror=
m.onabort=function(d){e.call(k||a,d,c)};m.onloaded=function(d){e.call(k||a,g,{id:c,data:d,type:a.b[c][0]})};b.require.staticOps.downloadStaticRes({type:a.b[c][0],resTypes:a.d(),src:a.j([[c,a.b[c][1]]])[0]},m,k);break;default:b.require.require.requireJSON(a.j([[c,a.b[c][1]]])[0],function(d,b){if(d)e.call(k||a,d,c);else{try{b={id:c,data:JSON.parse(b),type:a.b[c][0]}}catch(m){e.call(k||a,l(a.c.errorsStore,"ldr:gr#2",[b]),c);return}e.call(k||a,g,b)}},k)}}}var l=b.pengoError.pengoError.StoredPengoError;
h.prototype={s:function(a,c){if(!b.util.object.isObject(a))throw new b.pengoError.pengoError.PengoError("Configuration must be a defined Object",b.pengoError.codes.codes.NOT_FOUND);if(a.errorsStore===g||"string"!==typeof a.errorsStore)throw new b.pengoError.pengoError.PengoError("Expected config. param. 'errorsStore' must be a defined string, but it is '"+a.errorsStore+"'",b.pengoError.codes.codes.INVALID_DATA);if(a.resTypes===g||"string"!==typeof a.resTypes)throw new l(a.errorsStore,"ldr:cfg#1",
["resTypes",a.resTypes]);if(a.resourcesPath===g||"string"!==typeof a.resTypes)throw new l(a.errorsStore,"ldr:cfg#1",["resourcesPath",a.resourcesPath]);this.c=a;this.m=c},g:function(a){this.a=a;return this.a!==g},l:function(a){var c=this;this.o=a;this.o.on("RUNNERMANAGER/GAME/ONPLAY",function(){var a;a={};try{c.f?c.f.emit(c.a.getGameProperty("id"),"GameLoaded",c.m.type,window.location&&window.location.href&&window.location.href.split("?")[0]):c.i.push(a)}catch(b){throw new l(c.c.errorsStore,"ldr:st#1",
b);}})},h:function(a){var c=this;this.f=a;this.i.forEach(function(a){c.f.emit(a)})},k:function(a,c){var b,e=[],k=this.c.resourcesPath,d,k=a?k+this.a.getGameProperty("root")+this.a.getGameProperty(a):k+this.a.getGameProperty("root");if(c!==g&&Array.isArray(c))for(b=0;b<c.length;b++)d=this.a.getGameProperty("origin")+(k+"/"+c[b][0]).replace("//","/"),c[b][1]&&(""!=c[b][1]&&0!==c[b][1].split(".").length)&&(d+=c[b][1]),e[b]=d+"?gv="+this.a.getGameProperty("version");return e},q:function(){return this.k(g,
[[0,".json"]])[0]},j:function(a){return this.k("resources",a)},d:function(){return{IMAGE:0,AUDIO:1,VIDEO:2,VIEW:10,LAYER:11,OBJ_2D:12,TEXT:13,BITMAP:14,SPRITE:15,JSON:16}},start:function(a,c,l,e,k){var d=this,h,n;this.e=a;this.l(c);this.g(l);async.parallel([function(a){n=d.c.resourcesPath+d.a.getGameProperty("root")+"/"+d.c.resTypes;n=n.replace("//","/");n=d.a.getGameProperty("origin")+n+"?gv="+d.a.getGameProperty("version");d.b===g?d.b=b.require.require.requireJSON(n,function(b,c){if(b)a(b);else{try{d.b=
JSON.parse(c)}catch(e){d.b=g;a(e);return}a()}},d):a()},function(a){try{h=d.c.resourcesPath+d.a.getGameProperty("root")+d.c.codeRunnerPath,h=h.replace("//","/"),h=d.a.getGameProperty("origin")+h+"?gv="+d.a.getGameProperty("version"),b.require.require.requireJS(h,g,function(b){b&&d.e.error("Failed to load script.js due to "+b+", continue loading.");a()},d)}catch(c){d.e.error("Unexpected error loading script.js due to "+c+", continue loading.")}}],function(a){e&&e.call(k||this,a)})},stop:function(){this.b=
g;this.g();this.l();this.e=g}};return h};t("PENGO.client.plugins.game.loader.activator");
(function(){function b(){f.off("SERVICE_REGISTERED",b);if(!f.getService("igloo.logger")[0]||!f.getService("igloo.fatal")[0]||!f.getService("igloo.eventsManager")[0]||!f.getService("game.gameManager")[0])f.on("SERVICE_REGISTERED",b);else{e||(e=new d.loader);try{e.s(n.config,r)}catch(a){f.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"Setting plugin '"+f.getPluginId()+"'"});return}f.getService("stats")[0]&&e.h(f.getService("stats")[0]);f.on("SERVICE_REGISTERED",h);f.on("SERVICE_UNREGISTERED",
l);e.start(f.getService("igloo.logger")[0],f.getService("igloo.eventsManager")[0],f.getService("game.gameManager")[0],function(a){a?f.getService("igloo.fatal")[0].handleFatal({Message:a.message,Source:"Starting plugin '"+f.getPluginId()+"'"}):(p={functions:{getGame:e.p,getRes:e.r,getTypes:e.d},properties:{}},f.register(m,p),f.on("SERVICE_UNREGISTERED",c),f.on("SERVICE_UPDATED",s))},this)}}function h(a){"stats"===a&&e.h(f.getService(a)[0])}function l(a){"stats"===a&&e.h(f.getService(a)[0])}function a(a,
d){p!==g&&f.unregister(m,p);e!==g&&e.stop();f.off("SERVICE_UNREGISTERED",c);f.off("SERVICE_UPDATED",s);if(a&&!d)f.on("SERVICE_REGISTERED",b);else f.off("SERVICE_REGISTERED",b);k.remove(n.config.errorsStore);f.off("SERVICE_REGISTERED",h);f.off("SERVICE_UNREGISTERED",l)}function c(b){switch(b){case "game.gameManager":if(e.g(f.getService(b)[0]))return;break;default:return}a(!0)}var m="game.loader",e,k,d,r,n,f,p,s=c;window.PENGO.client.plugins.game.loader.activator.activator=function(c,e){k=c.pengoError.pengoError.storage;
return{start:function(a,c,h,l){f=a;n=c;d=e;r=l;k.add(c.config.errorsStore,e.errors.n);b()},stop:a}}})();})();
