/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var k=void 0,l=!1,n=this;function s(b){b=b.split(".");var c=n;!(b[0]in c)&&c.execScript&&c.execScript("var "+b[0]);for(var a;b.length&&(a=b.shift());)c=c[a]?c[a]:c[a]={}};s("PENGO.client.shared.runEngine.webAudio.actuators.mute");
window.PENGO.client.shared.runEngine.webAudio.actuators.mute.resolve=function(){function b(b,c,h,m){var e=new a.runEngine.Blackbox(b,c,h,m,"Mute");e.createOutput("muted",0);e.createOutput("notMuted",1);e.createInput("on",0,function(b){a.runEngine.getManager().e(!0);e.fireOutput(0,b)});e.createInput("off",1,function(b){a.runEngine.getManager().e(l);e.fireOutput(1,b)});return e}function c(){a.runEngine.getManager().e(l)}var a;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("MuteWebAudio",
b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("MuteWebAudio",c,k);a=d},implementation:{l:b}}};s("PENGO.client.shared.runEngine.webAudio.actuators.soundShooter");
window.PENGO.client.shared.runEngine.webAudio.actuators.soundShooter.resolve=function(){function b(b,c,h,m){function e(){g.inParameters.sound&&g.inParameters.sound.j()}function p(){g.inParameters.sound&&g.inParameters.sound.i()}var g=new a.runEngine.Blackbox(b,c,h,m,"SoundShooter");g.createInParam("sound",0);a.runEngine.getManager().d||(e=p=function(){});g.createInput("play",0,p);g.createInput("stop",1,e);return g}function c(a,b){a.callInput("stop",b)}var a;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("SoundShooterWebAudio",
b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SoundShooterWebAudio",c,k);a=d},implementation:{n:b}}};s("PENGO.client.shared.runEngine.webAudio.actuators.soundPlayer");
window.PENGO.client.shared.runEngine.webAudio.actuators.soundPlayer.resolve=function(){function b(b,c,m,e){function p(){f.inParameters.sound&&f.inParameters.sound.stop()}function g(){f.inParameters.sound&&f.inParameters.sound.pause()}function r(){f.inParameters.sound&&(d=f.inParameters.loop?!0:l,f.inParameters.sound.play(d))}var f=new a.runEngine.Blackbox(b,c,m,e,"SoundPlayer");f.createInParam("sound",0);f.createInParam("loop",1);a.runEngine.getManager().d||(p=g=r=function(){});f.createInput("play",
0,r);f.createInput("pause",1,g);f.createInput("stop",2,p);return f}function c(a,b){a.callInput("stop",b)}var a,d;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("SoundPlayerWebAudio",b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SoundPlayerWebAudio",c,k);d.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SoundPlayerWebAudio","loop",l);a=d},implementation:{m:b}}};s("PENGO.client.shared.runEngine.webAudio.sound");
window.PENGO.client.shared.runEngine.webAudio.sound.resolve=function(){function b(){this.source=this.buffer=this.url=k;this.h=this.c=0;this.a=[];this.f=0.5}var c;b.prototype={load:function(a,b){this.url=a;var q=this;c.fileTools.loader.Loader.getInstance().load(a,"arraybuffer",a,function(h){c.runEngine.manager.Manager.prototype.b.decodeAudioData(h.data,function(c){c?(q.buffer=c,b&&b(q)):alert("error decoding file data: "+a)})})},i:function(){if(this.buffer){var a=this.a.push(c.runEngine.manager.Manager.prototype.b.createBufferSource())-
1;this.a[a].buffer=this.buffer;this.a[a].connect(c.runEngine.manager.Manager.prototype.b.destination);this.a[a].noteOn(0);this.k()}},k:function(){for(var a=0;a<this.a.length;)3==this.a[a].playbackState?(this.a[a].disconnect(),this.a.splice(a,1)):a++},j:function(){for(var a=this.a.length;0<=a;a--)this.a[a].noteOff(0),this.a[a].disconnect();this.a.length=0},play:function(a){this.source&&3==this.source.playbackState&&(this.source.disconnect(),this.source=k);this.source||(this.source=c.runEngine.manager.Manager.prototype.b.createBufferSource(),
this.source.buffer=this.buffer,this.source.connect(c.runEngine.manager.Manager.prototype.b.destination),this.source.gain(c.runEngine.manager.Manager.prototype.b.createGainNode()),this.source.gain.value=this.f,a=a?a:l,(this.source.loop=a)?(a=this.source.buffer.duration,this.c>this.source.buffer.duration&&(this.c%=this.source.buffer.duration)):a=this.source.buffer.duration-this.c,this.h=c.runEngine.manager.Manager.prototype.b.currentTime,this.source.noteGrainOn(0,this.c,a),this.c=0)},pause:function(){this.source&&
2==this.source.playbackState&&(this.source.noteOff(0),this.source.disconnect(),this.source=k,this.c=c.runEngine.manager.Manager.prototype.b.currentTime-this.h)},stop:function(){this.source&&3!=this.source.playbackState&&(this.source.noteOff(0),this.source.disconnect(),this.source=k);this.c=0},e:function(a){this.f=a?0:0.5;this.source&&this.source.gain&&(this.source.gain=this.f)}};return{dependencies:function(a){c=a},implementation:{Sound:b}}};s("PENGO.client.shared.runEngine.webAudio.manager");
window.PENGO.client.shared.runEngine.webAudio.manager.resolve=function(){function b(a,d,q){function h(a,d){if(b.prototype.d){var h=new c.runEngine.sound.Sound;h.load(a,d);e.push(h)}else d()}function m(a){a&&(a=e.indexOf(a),-1!=a&&e.splice(a,1))}this.o=d;b.prototype.b||("function"==typeof window.AudioContext?(b.prototype.b=new window.AudioContext,b.prototype.d=!0):"function"==typeof window.webkitAudioContext?(b.prototype.b=new window.webkitAudioContext,b.prototype.d=!0):(b.prototype.d=l,c.logger&&
c.logger.error("ERROR: Web Audio API is not supported in this browser")));(a=c.resourceManager.getStaticTypes()["static"].WEBAUDIO)&&q.registerAssetType({type:a,callbacks:{load:h,unload:m}});var e=this.g=[]}var c;b.prototype={b:k,d:l,e:function(a){for(var b=0;b<this.g.length;b++)this.g[b].e(a)}};return{dependencies:function(a){c=a;a.runEngine.paramManager.addParamType("Sound","Sound",k)},implementation:{Manager:b}}};})();
