/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var l=void 0,m=!0,p=!1,r=this;function t(a){a=a.split(".");var b=r;!(a[0]in b)&&b.execScript&&b.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)b=b[c]?b[c]:b[c]={}};t("PENGO.client.shared.runEngine.ranking.actuators.submitScore");
(function(){function a(c){c.secure=c.existOutput(3)}function b(c){c.setting=p}window.PENGO.client.shared.runEngine.ranking.actuators.submitScore.resolve=function(){function c(c,a,b,k){function g(d,a){var b;d?b=1:a.result===q.OK?("number"==typeof e.outParameters.position&&(e.outParameters.position=a.a),b=0):b=a.result===q.KO?1:a.result===q.USER_KO?2:1;c.callOnNextUpdateDraw(function(c){e.setting=p;e.fireOutput(b,c)})}var e=new d.runEngine.Blackbox(c,a,b,k,"_SubmitScore_key");e.createOutParam("position",
0);e.createOutput("done",0);e.createOutput("error",1);e.createOutput("accessDenied",2);e.createOutput("onPrevious",3);e.secure=m;e.setting=p;var q=l,s=d.runEngine.getManager();e.createInput("submit",0,function(c){var d,a,f,b;if(e.secure&&e.setting)e.fireOutput(3,c);else if(f=e.getInParams(),f.length){a={};for(d=0;d<f.length;d+=1)b=e.getInParamValue(f[d].index),b!==l&&(a[f[d].index]={_id:f[d].nameKey,val:b});s.l(a)?e.fireOutput(0,c):(q||(q=s.j()),q?(e.setting=m,s.s(a,g)||(e.setting=p,e.fireOutput(1,
c),q=l)):e.fireOutput(1,c))}});return e}var d;c.prototype={};return{dependencies:function(f){f.runEngine.blackboxRepository.addBlackboxType("_SubmitScore_key",c);f.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SubmitScore_key",b,a);d=f},implementation:{e:c}}}})();t("PENGO.client.shared.runEngine.ranking.manager");
window.PENGO.client.shared.runEngine.ranking.manager.resolve=function(){function a(c,a){this.t=a;var b,h={o:l};for(b in h);Object.defineProperty(this,b,{get:function(){return c.isOnPlay()},enumerable:m,configurable:p})}function b(c,a){return function(b,h){c.o&&a(b,h)}}var c;a.prototype={l:function(c){for(var a in c)return p;return m},j:function(){if(c.gameRankingService)return c.gameRankingService.getConstants()},s:function(a,f){return c.gameRankingService&&c.gameRankingService.b?(c.gameRankingService.b(c.GAME_PROPERTIES.id,
a,b(this,f)),m):p},r:function(a){return c.gameRankingService?(c.gameRankingService.a(c.GAME_PROPERTIES.id,a),m):p},k:function(){return c.gameRankingService&&c.gameRankingService.hideRankings?(c.gameRankingService.hideRankings(),m):p}};a.prototype.requestRankingDescription=a.prototype.u;return{dependencies:function(a){c=a},implementation:{Manager:a}}};t("PENGO.client.shared.runEngine.ranking.actuators.showRanking");
window.PENGO.client.shared.runEngine.ranking.actuators.showRanking.resolve=function(){function a(a,b,h,k){var g=new c.runEngine.Blackbox(a,b,h,k,"_ShowRanking_key");d=c.runEngine.getManager();g.createOutput("shown",0);g.createOutput("closed",1);g.createInput("show",0,function(c){d.r(function(){a.setPauseState(p);a.callOnNextUpdateDraw(function(c){g.fireOutput(1,c)})})&&(a.setPauseState(m),g.fireOutput(0,c))});return g}function b(){d.k()}var c,d;a.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("_ShowRanking_key",
a);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ShowRanking_key",b);c=d},implementation:{d:a}}};t("PENGO.client.ide.runEngine.ranking.actuators.showRanking");window.PENGO.client.ide.runEngine.ranking.actuators.showRanking.resolve=function(){function a(c,a,f,n){return b.runEngine.actuators.showRanking.base.d(c,a,f,n)}var b;return{dependencies:function(c){c.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_ShowRanking_key",a,"ShowRanking","Rankings/async");c.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_ShowRanking_key",["sync","async"]);b=c},implementation:{d:a}}};t("PENGO.client.ide.runEngine.ranking.actuators.submitScore");
window.PENGO.client.ide.runEngine.ranking.actuators.submitScore.resolve=function(){var a,b=function d(b,n,h,k){var g=a.runEngine.actuators.submitScore.base.e(b,n,h,k);d.prototype.h(g);var e=a.runEngine.getManager();d.prototype.f(g,e,e.q);g.onRankingUpdated=function(a){d.prototype.f(g,e,a)};e.g(b.getID(g),g);return g};b.prototype={h:function(a){a.addBoolProperty("secure",function(a,b){a?b.secure||(b.createOutput("onPrevious",3),b.secure=a):b.secure&&(b.delOutput(3),b.secure=a)},l,m)},f:function(b,
f,n){var h;h=b.getInParams();f=[];for(var k=0;k<h.length;k+=1)f[h[k].index]=h[k].nameKey;for(var g in n)h=parseInt(g),f[h]===l?(b.createInParam(n[g]._id,h),b.setParamConnectorValidTypes(h,m,n[g].type),b.setParamConnectorAggregation(h,m,p)):(b.changeParamConnectorName(h,m,n[g]._id),b.setParamConnectorValidTypes(h,m,n[g].type),delete f[h]);for(k=0;k<f.length;k+=1)f[k]!=l&&b.delInParam(k);a.runEngine.blackboxRepository.setOutParamConnectionRulesToBlackboxType("_SubmitScore_key","position",p,"number",
"Position in ranking")},n:function(a){a.setProperty("secure",a.existOutput(3))},m:function(b,f){a.runEngine.getManager().i(f)}};return{dependencies:function(d){d.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_SubmitScore_key",b,"SubmitScore","Rankings/async");d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_SubmitScore_key",l,b.prototype.n,l,b.prototype.m);d.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_SubmitScore_key",["both","both","both","sync"]);a=
d},implementation:{e:b}}};t("PENGO.client.ide.runEngine.ranking.manager");
window.PENGO.client.ide.runEngine.ranking.manager.resolve=function(){function a(c,d,f,n,h,k,g){this.c={};var e={q:l},q;for(q in e);Object.defineProperty(this,q,{get:function(){return b||{}},enumerable:m,configurable:p});a.super_.constructor.call(this,c,d,f,n,h,k,g)}var b;a.prototype={p:function(a){b=a},g:function(a,b){this.c[a]=b},i:function(a){delete this.c[a]},update:function(){if(b)for(var a in this.c)this.c[a].onRankingUpdated(b)}};a.prototype.provideColumnsDescriptor=a.prototype.p;a.prototype.update=
a.prototype.update;return{dependencies:function(b){b.inheritance.inheritance.inherits(a,b.runEngine.manager.base.Manager)},implementation:{Manager:a}}};})();
