/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var h=void 0,k=!0,l=!1,q=this;function t(b){b=b.split(".");var e=q;!(b[0]in e)&&e.execScript&&e.execScript("var "+b[0]);for(var a;b.length&&(a=b.shift());)e=e[a]?e[a]:e[a]={}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.consumeVirtualGood");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.consumeVirtualGood.resolve=function(){function b(c,a,b,e){function m(a,d){var b,p;a?b=3:d.result===n.OK?(p=d.data.amountLeft,b=0):b=d.result===n.KO_TYPE_SPECIFIC_ERROR&&3==d.data.errCode?1:3;c.callOnNextUpdateDraw(function(a){f.consuming=l;p!==h&&(f.outParameters.amountLeft=p);f.fireOutput(b,a)})}var f=new d.runEngine.Blackbox(c,a,b,e,"_consumeVg_key");f.createInParam("virtualGood",0);f.createInParam("outlay",1);f.createOutParam("amountLeft",
0);f.createOutput("done",0);f.createOutput("notEnough",1);f.createOutput("onPrevious",2);f.createOutput("error",3);f.secure=k;f.consuming=l;var n=h,s=d.runEngine.getManager();f.createInput("consume",0,function(a){f.inParameters.virtualGood&&f.inParameters.outlay!==h&&(f.secure&&f.consuming?f.fireOutput(2,a):(n||(n=s.a()),n?(f.consuming=k,s.h(f.inParameters.virtualGood._id,Math.ceil(Math.abs(f.inParameters.outlay)),m)||(f.consuming=l,f.fireOutput(3,a),n=h)):f.fireOutput(3,a)))});return f}function e(a,
d){a.secure=d!==h&&d.S}function a(a){a.consuming=l}var d;return{dependencies:function(c){c.runEngine.blackboxRepository.addBlackboxType("_consumeVg_key",b);c.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_consumeVg_key",a,e);d=c},implementation:{c:b}}};t("PENGO.client.ide.runEngine.virtualGoods.actuators.consumeVirtualGood");
window.PENGO.client.ide.runEngine.virtualGoods.actuators.consumeVirtualGood.resolve=function(){function b(a,b,e,g){a=d.runEngine.actuators.consumeVirtualGood.base.c(a,b,e,g);a.addBoolProperty("secure",function(a,c){a?c.secure||(c.createOutput("on previous",2),c.secure=a):c.secure&&(c.delOutput(2),c.secure=a)},h,k);return a}function e(a){if(a.getProperty("secure")===k)return{S:k}}function a(a,d){a.setProperty("secure",d!==h&&d.S)}var d;return{dependencies:function(c){c.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_consumeVg_key",
b,"ConsumeVirtualGood","VirtualGoods/sensors");c.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_consumeVg_key",h,a,e);c.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("_consumeVg_key","virtualGood",l,"_VG_","the Virtual Good to request to consume.");c.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("_consumeVg_key","outlay",l,"number","the spent amount.");c.runEngine.blackboxRepository.setOutParamConnectionRulesToBlackboxType("_consumeVg_key",
"amountLeft",l,"number","the remaining amount of the virtual Good after the execution.");c.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_consumeVg_key",["async","async","sync","both"]);d=c},implementation:{c:b}}};t("PENGO.client.shared.runEngine.virtualGoods.manager");
window.PENGO.client.shared.runEngine.virtualGoods.manager.resolve=function(){function b(a,c){this.o=c;var b,e={g:h};for(b in e);Object.defineProperty(this,b,{get:function(){return a.isOnPlay()},enumerable:k,configurable:l})}function e(a,c){return function(b,e){a.g&&c(b,e)}}var a;b.prototype={b:function(d,c){function b(a,d){if(!a&&d.result===e.OK)d.virtualGood&&d.virtualGood.name?c(d.virtualGood,d.virtualGood.name,l):c(h,h,k);else throw"Error getting Virtual Good. "+a;}var e,g={type:"game"};if(d)if(a.virtualGoodsService&&
a.virtualGoodsService.execution)e=a.virtualGoodsService.execution.getProtocolConstants().results,g._id=d,g.projectId=a.GAME_PROPERTIES.id,g.projectVersion=a.GAME_PROPERTIES.version,a.virtualGoodsService.execution.get(g,{},b);else throw"Virtual Goods service not available.";},a:function(){if(a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.getProtocolConstants)return a.virtualGoodsService.orders.getProtocolConstants().results},j:function(d,c){var b={type:"game",_id:d,
projectId:a.GAME_PROPERTIES.id};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.getCount?(a.virtualGoodsService.orders.getCount(b,e(this,c)),k):l},h:function(d,c,b){d={type:"game",_id:d,projectId:a.GAME_PROPERTIES.id,projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.consume?(a.virtualGoodsService.orders.consume(d,c,e(this,b)),k):l},m:function(d,c){var b={type:"game",_id:d,projectId:a.GAME_PROPERTIES.id,
projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.registerOnCountModified?(a.virtualGoodsService.orders.registerOnCountModified(b,c),k):l},n:function(d,c){var b={type:"game",_id:d,projectId:a.GAME_PROPERTIES.id,projectVersion:a.GAME_PROPERTIES.version};return a.virtualGoodsService&&a.virtualGoodsService.orders&&a.virtualGoodsService.orders.unregisterOnCountModified?(a.virtualGoodsService.orders.unregisterOnCountModified(b,
c),k):l},l:function(d){return a.virtualGoodsService&&a.virtualGoodsService.cart&&a.virtualGoodsService.cart.showCart?(a.virtualGoodsService.cart.showCart(d),k):l},k:function(){return a.virtualGoodsService&&a.virtualGoodsService.cart&&a.virtualGoodsService.cart.hideCart?(a.virtualGoodsService.cart.hideCart(),k):l}};b.prototype.getVirtualGood=b.prototype.b;return{dependencies:function(d){a=d;d.runEngine.paramManager.addParamType("_VG_","VirtualGood",{},l)},implementation:{Manager:b,config:{}}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.showShoppingCart");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.showShoppingCart.resolve=function(){function b(c,b,e,g){var m=new a.runEngine.Blackbox(c,b,e,g,"_ShowShoppingCart_key");d=a.runEngine.getManager();m.createOutput("shown",0);m.createOutput("closed",1);m.createInput("show",0,function(a){d.l(function(){c.setPauseState(l);c.callOnNextUpdateDraw(function(a){m.fireOutput(1,a)})})&&(c.setPauseState(k),m.fireOutput(0,a))});return m}function e(){d.k()}var a,d;b.prototype={};return{dependencies:function(c){c.runEngine.blackboxRepository.addBlackboxType("_ShowShoppingCart_key",
b);c.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_ShowShoppingCart_key",e);a=c},implementation:{e:b}}};t("PENGO.client.ide.runEngine.virtualGoods.manager");
window.PENGO.client.ide.runEngine.virtualGoods.manager.resolve=function(){function b(a,c,e,r,g,m,f){b.super_.constructor.call(this,a,c,e,r,g,m,f)}var e,a={};b.prototype={i:function(d){if(e.virtualGoodsService&&e.virtualGoodsService.execution)a[d]&&(e.virtualGoodsService.execution.unregisterModifiedCbk(d,a[d]),delete a[d]);else throw"Virtual Goods service not available.";},b:function(d,c,p){function r(a){a?p(a,a.name,l):p(h,h,k)}b.super_.b.call(this,d,c);e.virtualGoodsService&&e.virtualGoodsService.execution&&
(a[d]=r,e.virtualGoodsService.execution.registerModifiedCbk(d,a[d]))}};b.prototype.freeVirtualGood=b.prototype.i;b.prototype.getVirtualGood=b.prototype.b;return{dependencies:function(a){e=a;a.inheritance.inheritance.inherits(b,a.runEngine.manager.base.Manager);a.runEngine.paramManager.addParamTypeIdeEx("_VG_","VirtualGoods")},implementation:{Manager:b,config:{}}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.virtualGoodListener");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.virtualGoodListener.resolve=function(){function b(a,b,c,p){function r(c){function b(a){c!==h&&(g.outParameters.remainingAmount=c);g.fireOutput(0,a)}f.g&&a.callOnNextUpdateDraw(b)}var g=new e.runEngine.Blackbox(a,b,c,p,"_listenVg_key");g.createInParam("virtualGood",0);g.createOutParam("remainingAmount",0);g.createOutput("updated",0);g.createOutput("error",1);var m=h,f=e.runEngine.getManager(),n=l;g.offListenVG=function(){n&&g.inParameters.virtualGood!==
h&&(m||(m=f.a()),m&&f.n(g.inParameters.virtualGood._id,r));n=l};g.createInput("on",0,function(a){!n&&g.inParameters.virtualGood!==h&&(m||(m=f.a()),m?(n=f.m(g.inParameters.virtualGood._id,r),n||(g.fireOutput(1,a),m=h)):g.fireOutput(1,a))});g.createInput("off",1,g.offListenVG);return g}var e;return{dependencies:function(a){a.runEngine.blackboxRepository.addBlackboxType("_listenVg_key",b);a.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_listenVg_key",function(a,c){a.offListenVG(c)},
h);e=a},implementation:{f:b}}};t("PENGO.client.ide.runEngine.virtualGoods.actuators.virtualGoodListener");
window.PENGO.client.ide.runEngine.virtualGoods.actuators.virtualGoodListener.resolve=function(){function b(a,b,c,p){return e.runEngine.actuators.virtualGoodListener.base.f(a,b,c,p)}var e;return{dependencies:function(a){a.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_listenVg_key",b,"VirtualGoodListener","VirtualGoods/sensors");a.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("_listenVg_key","virtualGood",l,"_VG_","The virtual good whose changes of amount will be listened to.");
a.runEngine.blackboxRepository.setOutParamConnectionRulesToBlackboxType("_listenVg_key","remainingAmount",l,"number","The remaining amount of the virtual good.");a.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_listenVg_key",["async","sync"]);e=a},implementation:{f:b}}};t("PENGO.client.shared.runEngine.virtualGoods.actuators.getVirtualGoodAmount");
window.PENGO.client.shared.runEngine.virtualGoods.actuators.getVirtualGoodAmount.resolve=function(){function b(a,b,e,g){function m(b,d){var e,g;b?e=2:d.result===n.OK?(g=d.amount,e=0):e=2;a.callOnNextUpdateDraw(function(a){f.getting=l;g!==h&&(f.outParameters.amount=g);f.fireOutput(e,a)})}var f=new d.runEngine.Blackbox(a,b,e,g,"_GetVgAmount_key");f.createInParam("virtualGood",0);f.createOutParam("amount",0);f.createOutput("done",0);f.createOutput("onPrevious",1);f.createOutput("error",2);f.secure=k;
f.getting=l;var n=h,s=d.runEngine.getManager();f.createInput("get",0,function(a){f.inParameters.virtualGood&&f.outParameters.amount!==h&&(f.secure&&f.getting?f.fireOutput(1,a):(n||(n=s.a()),n?(f.getting=k,d.runEngine.getManager().j(f.inParameters.virtualGood._id,m)||(f.getting=l,f.fireOutput(2,a),n=h)):f.fireOutput(2,a)))});return f}function e(a,b){a.secure=b!==h&&b.S}function a(a){a.getting=l}var d;return{dependencies:function(c){c.runEngine.blackboxRepository.addBlackboxType("_GetVgAmount_key",
b);c.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetVgAmount_key",a,e);d=c},implementation:{d:b}}};t("PENGO.client.ide.runEngine.virtualGoods.actuators.getVirtualGoodAmount");
window.PENGO.client.ide.runEngine.virtualGoods.actuators.getVirtualGoodAmount.resolve=function(){function b(a,b,e,g){a=d.runEngine.actuators.getVirtualGoodAmount.base.d(a,b,e,g);a.addBoolProperty("secure",function(a,b){a?b.secure||(b.createOutput("on previous",1),b.secure=a):b.secure&&(b.delOutput(1),b.secure=a)},h,k);return a}function e(a){if(a.getProperty("secure")===k)return{S:k}}function a(a,b){a.setProperty("secure",b!==h&&b.S)}var d;return{dependencies:function(c){c.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_GetVgAmount_key",
b,"GetVirtualGoodAmount","VirtualGoods/sensors");c.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("_GetVgAmount_key",h,a,e);c.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("_GetVgAmount_key","virtualGood",l,"_VG_","the Virtual Good to request its amount");c.runEngine.blackboxRepository.setOutParamConnectionRulesToBlackboxType("_GetVgAmount_key","amount",l,"number","amount of Virtual Good");c.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_GetVgAmount_key",
["async","sync","both"]);d=c},implementation:{d:b}}};t("PENGO.client.ide.runEngine.virtualGoods.actuators.showShoppingCart");
window.PENGO.client.ide.runEngine.virtualGoods.actuators.showShoppingCart.resolve=function(){function b(a,b,c,p){return e.runEngine.actuators.showShoppingCart.base.e(a,b,c,p)}var e;return{dependencies:function(a){a.runEngine.blackboxRepository.updateBlackboxTypeToIDE("_ShowShoppingCart_key",b,"ShowShoppingCart","VirtualGoods/actuators");a.runEngine.blackboxRepository.setOuputsFireModeToBlackboxType("_ShowShoppingCart_key",["sync","async"]);e=a},implementation:{e:b}}};})();
