/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var g=void 0,m=!1,n=this;function s(b){b=b.split(".");var c=n;!(b[0]in c)&&c.execScript&&c.execScript("var "+b[0]);for(var a;b.length&&(a=b.shift());)c=c[a]?c[a]:c[a]={}};s("PENGO.client.shared.runEngine.webAudio.actuators.mute");
window.PENGO.client.shared.runEngine.webAudio.actuators.mute.resolve=function(){function b(b,c,k,p){var e=new a.runEngine.Blackbox(b,c,k,p,"Mute");e.createOutput("muted",0);e.createOutput("notMuted",1);e.createInput("on",0,function(b){a.runEngine.getManager().e(!0);e.fireOutput(0,b)});e.createInput("off",1,function(b){a.runEngine.getManager().e(m);e.fireOutput(1,b)});return e}function c(){a.runEngine.getManager().e(m)}var a;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("MuteWebAudio",
b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("MuteWebAudio",c,g);a=d},implementation:{m:b}}};s("PENGO.client.ide.runEngine.webAudio.actuators.mute");window.PENGO.client.ide.runEngine.webAudio.actuators.mute.resolve=function(){return{dependencies:function(b){b.runEngine.blackboxRepository.updateBlackboxTypeToIDE("MuteWebAudio",g,"MuteSwitcher","webaudio/actuators")}}};s("PENGO.client.shared.runEngine.webAudio.manager");
window.PENGO.client.shared.runEngine.webAudio.manager.resolve=function(){function b(a,d,h){function k(a,d){if(b.prototype.d){var h=new c.runEngine.sound.Sound;h.load(a,d);e.push(h)}else d()}function p(a){a&&(a=e.indexOf(a),-1!=a&&e.splice(a,1))}this.p=d;b.prototype.b||("function"==typeof window.AudioContext?(b.prototype.b=new window.AudioContext,b.prototype.d=!0):"function"==typeof window.webkitAudioContext?(b.prototype.b=new window.webkitAudioContext,b.prototype.d=!0):(b.prototype.d=m,c.logger&&
c.logger.error("ERROR: Web Audio API is not supported in this browser")));(a=c.resourceManager.getStaticTypes()["static"].WEBAUDIO)&&h.registerAssetType({type:a,callbacks:{load:k,unload:p}});var e=this.g=[]}var c;b.prototype={b:g,d:m,e:function(a){for(var b=0;b<this.g.length;b++)this.g[b].e(a)}};return{dependencies:function(a){c=a;a.runEngine.paramManager.addParamType("Sound","Sound",g)},implementation:{Manager:b}}};s("PENGO.client.ide.runEngine.webAudio.manager");
window.PENGO.client.ide.runEngine.webAudio.manager.resolve=function(){function b(a,d,h,k,p,e,q){b.super_.constructor.call(this,a,d,h,k,p,e,q);(a=c.resourceManager.getStaticTypes()["static"].WEBAUDIO)&&h.registerAssetCallback(a,"getDescription",this.i)}var c;b.prototype={i:function(a){var b;"wav"==a.split(".").pop()&&(b={type:"Sound"});return b}};return{dependencies:function(a){c=a;a.inheritance.inheritance.inherits(b,a.runEngine.manager.base.Manager);a.runEngine.paramManager.addParamTypeIdeEx("Sound",
"WebAudio")},implementation:{Manager:b,config:{}}}};s("PENGO.client.shared.runEngine.webAudio.actuators.soundShooter");
window.PENGO.client.shared.runEngine.webAudio.actuators.soundShooter.resolve=function(){function b(b,c,k,p){function e(){l.inParameters.sound&&l.inParameters.sound.k()}function q(){l.inParameters.sound&&l.inParameters.sound.j()}var l=new a.runEngine.Blackbox(b,c,k,p,"SoundShooter");l.createInParam("sound",0);a.runEngine.getManager().d||(e=q=function(){});l.createInput("play",0,q);l.createInput("stop",1,e);return l}function c(a,b){a.callInput("stop",b)}var a;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("SoundShooterWebAudio",
b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SoundShooterWebAudio",c,g);a=d},implementation:{o:b}}};s("PENGO.client.ide.runEngine.webAudio.actuators.soundShooter");window.PENGO.client.ide.runEngine.webAudio.actuators.soundShooter.resolve=function(){return{dependencies:function(b){b.runEngine.blackboxRepository.updateBlackboxTypeToIDE("SoundShooterWebAudio",g,"SoundShooter","webAudio/actuators");b.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("SoundShooterWebAudio","sound",m,"Sound","The Sound to be shot")}}};s("PENGO.client.shared.runEngine.webAudio.sound");
window.PENGO.client.shared.runEngine.webAudio.sound.resolve=function(){function b(){this.source=this.buffer=this.url=g;this.h=this.c=0;this.a=[];this.f=0.5}var c;b.prototype={load:function(a,b){this.url=a;var h=this;c.fileTools.loader.Loader.getInstance().load(a,"arraybuffer",a,function(k){c.runEngine.manager.Manager.prototype.b.decodeAudioData(k.data,function(c){c?(h.buffer=c,b&&b(h)):alert("error decoding file data: "+a)})})},j:function(){if(this.buffer){var a=this.a.push(c.runEngine.manager.Manager.prototype.b.createBufferSource())-
1;this.a[a].buffer=this.buffer;this.a[a].connect(c.runEngine.manager.Manager.prototype.b.destination);this.a[a].noteOn(0);this.l()}},l:function(){for(var a=0;a<this.a.length;)3==this.a[a].playbackState?(this.a[a].disconnect(),this.a.splice(a,1)):a++},k:function(){for(var a=this.a.length;0<=a;a--)this.a[a].noteOff(0),this.a[a].disconnect();this.a.length=0},play:function(a){this.source&&3==this.source.playbackState&&(this.source.disconnect(),this.source=g);this.source||(this.source=c.runEngine.manager.Manager.prototype.b.createBufferSource(),
this.source.buffer=this.buffer,this.source.connect(c.runEngine.manager.Manager.prototype.b.destination),this.source.gain(c.runEngine.manager.Manager.prototype.b.createGainNode()),this.source.gain.value=this.f,a=a?a:m,(this.source.loop=a)?(a=this.source.buffer.duration,this.c>this.source.buffer.duration&&(this.c%=this.source.buffer.duration)):a=this.source.buffer.duration-this.c,this.h=c.runEngine.manager.Manager.prototype.b.currentTime,this.source.noteGrainOn(0,this.c,a),this.c=0)},pause:function(){this.source&&
2==this.source.playbackState&&(this.source.noteOff(0),this.source.disconnect(),this.source=g,this.c=c.runEngine.manager.Manager.prototype.b.currentTime-this.h)},stop:function(){this.source&&3!=this.source.playbackState&&(this.source.noteOff(0),this.source.disconnect(),this.source=g);this.c=0},e:function(a){this.f=a?0:0.5;this.source&&this.source.gain&&(this.source.gain=this.f)}};return{dependencies:function(a){c=a},implementation:{Sound:b}}};s("PENGO.client.ide.runEngine.webAudio.sound");window.PENGO.client.ide.runEngine.webAudio.sound.resolve=function(){var b=function a(b,h,k){a.super_.constructor.call(this,b,h,k)};b.prototype={};return{dependencies:function(a){a.inheritance.inheritance.inherits(b,a.runEngine.audio.base.Sound)},implementation:{Sound:b}}};s("PENGO.client.shared.runEngine.webAudio.actuators.soundPlayer");
window.PENGO.client.shared.runEngine.webAudio.actuators.soundPlayer.resolve=function(){function b(b,c,p,e){function q(){f.inParameters.sound&&f.inParameters.sound.stop()}function l(){f.inParameters.sound&&f.inParameters.sound.pause()}function r(){f.inParameters.sound&&(d=f.inParameters.loop?!0:m,f.inParameters.sound.play(d))}var f=new a.runEngine.Blackbox(b,c,p,e,"SoundPlayer");f.createInParam("sound",0);f.createInParam("loop",1);a.runEngine.getManager().d||(q=l=r=function(){});f.createInput("play",
0,r);f.createInput("pause",1,l);f.createInput("stop",2,q);return f}function c(a,b){a.callInput("stop",b)}var a,d;b.prototype={};return{dependencies:function(d){d.runEngine.blackboxRepository.addBlackboxType("SoundPlayerWebAudio",b);d.runEngine.blackboxRepository.setSpecificCallbacksToBlackboxType("SoundPlayerWebAudio",c,g);d.runEngine.blackboxRepository.setInParamDefaultValueToBlackboxType("SoundPlayerWebAudio","loop",m);a=d},implementation:{n:b}}};s("PENGO.client.ide.runEngine.webAudio.actuators.soundPlayer");
window.PENGO.client.ide.runEngine.webAudio.actuators.soundPlayer.resolve=function(){return{dependencies:function(b){b.runEngine.blackboxRepository.updateBlackboxTypeToIDE("SoundPlayerWebAudio",g,"SoundPlayer","webAudio/actuators");b.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("SoundPlayerWebAudio","sound",m,"Sound","The Sound to be played");b.runEngine.blackboxRepository.setInParamConnectionRulesToBlackboxType("SoundPlayerWebAudio","loop",m,"bool","repeat when the play end")}}};})();
