/** Copyright (c) 2016 WIMI5. All rights reserved. */ (function(){var f=void 0,l=!0,m=!1;Math.random();var n;
n=function(d){function q(a,c){var b=this;h=a;this.N=c;this.b=this.i=this.c=f;this.j={};this.o=m;this.n=f;this.S=function(){return b.o};this.z=function(){b.G(function(a){a?b.c.warn("Error "+a+" while updating texts"):b.h!==f&&b.h.render()})};this.w=function(a){b.o=m;b.f.off("CONNECTION_LOST",b.w);switch(a.code){case d.net.constants.error.codes.SESSION_NOT_VALID:b.e.invalidateSession();break;case d.net.constants.error.codes.DUPLICATE_USER_SESSION:b.i.showMessageDialog({type:"message",title:g.DuplicateSessionTitle,text:g.DuplicateSessionMessage,
button1Text:"OK",button1Action:function(){b.e.signOut()},closeButton:m});break;case d.net.constants.results.CLOSE_NORMAL:break;default:this.j.hideReconnectDialog!==l&&b.i.showModalView(b.h),b.l()}};this.A=function(a){b.model.set({sessionID:a})};this.B=function(){b.model.set({sessionID:f})};this.I=function(a){a=a.attributes.sessionID;this.c.debug("Change sessionID "+a);if(b.a.getSessionID()!==f&&b.a.getSessionID()===a)b.c.debug("same sessionID");else switch(b.a.getReadyState()){case b.d.CONNECTED:case b.d.CONNECTING:case b.d.PENDING_VERIFICATION:(function(a){b.a.onReadyStateChange(b.d.VERIFIED,
function(){b.disconnect(d.net.constants.error.codes.SESSION_NOT_VALID,"New session ID detected, disconnect previously.");b.a.onReadyStateChange(b.d.DISCONNECTED,function(){a&&b.g(a)})})})(a);break;case b.d.VERIFIED:(function(a){b.disconnect(d.net.constants.error.codes.SESSION_NOT_VALID,"New session ID detected, disconnect previously.");b.a.onReadyStateChange(b.d.DISCONNECTED,function(){a&&b.g(a)})})(a);break;case b.d.DISCONNECTING:(function(a){b.a.onReadyStateChange(b.d.DISCONNECTED,function(){b.disconnect(d.net.constants.error.codes.SESSION_NOT_VALID,
"New session ID detected, disconnect previously.");a&&b.g(a)})})(a);break;case b.d.DISCONNECTED:a&&b.g(a);break;default:a&&b.g(a)}}}function p(a){var c={v:function(a){a instanceof r&&a.addControllerCallback("setConnectNowCallback",c.H(a.model,a))},H:function(){return function(){a.n!==f&&(clearTimeout(a.n),a.n=f);a.g()}}};return c}var h,g,w=d.bbWrappers.pengoModel.PengoModel.extend({defaults:function(){return{sessionID:f,state:0,ttr:f}}}),r=d.bbWrappers.pengoView.PengoView.extend({tagName:"div",initialize:function(){this.p();
this.M=_.template(h.connect);this.firstRender()},p:function(){this.model.on("change:state",this.F,this);this.model.on("change:ttr",this.P,this)},render:function(){this.$el.prop("id","connect");this.$el.addClass("modal-form");this.$el.html(this.M());this.$el.find("#title").text(g.connect);this.F();this.$el.find("#button").prop("value",g.connectNow);this.addControllerCallbacks();return this},F:function(){switch(this.model.get("state")){case 0:this.$el.find("#text1").text(g.disconnected);this.$el.find("#text2").text("");
this.$el.find("#button").hide();break;case 1:this.$el.find("#text1").text(g.connecting);this.$el.find("#text2").text("");this.$el.find("#button").hide();break;case 3:this.$el.find("#text1").text(g.disconnected+" "+g.waitingToConnect+" ");this.$el.find("#text2").text(this.model.get("ttr"));this.$el.find("#button").show();break;default:this.$el.find("#text1").text(""),this.$el.find("#text2").text(""),this.$el.find("#button").hide()}},P:function(){this.$el.find("#text2").text(this.model.get("ttr"))},
setConnectNowCallback:function(a){this.$el.find("#button").on("click",a)}}),s=d.bbWrappers.pengoView.PengoView.extend({tagName:"div",attributes:{"class":"netManagerView"},initialize:function(){this.p();this.template=_.template(h.mainbarNet);this.firstRender()},p:function(){this.listenTo(this.model,"change:state",this.O,this)},Q:function(){},render:function(){this.$el.html(this.template());this.addControllerCallbacks();return this},O:function(){2===this.model.get("state")?(this.$el.find(".ConnStatus").addClass("ConnStatus-conn"),
this.$el.parent().removeClass("not-connected")):(this.$el.find(".ConnStatus").removeClass("ConnStatus-conn"),this.$el.parent().addClass("not-connected"))}});q.prototype={J:function(a){if(a===f)throw new d.pengoError.pengoError.PengoError("Config can't be undefined",d.pengoError.codes.codes.NOT_FOUND);if(a.reconnect&&"number"!==typeof a.reconnect)throw new d.pengoError.pengoError.PengoError("If exists, config property 'reconnect' must be a Number",d.pengoError.codes.codes.INVALID_TYPE);this.j=a},K:function(a){this.c=
a},L:function(a){this.b=a},s:function(a){this.f!==a&&(a&&(a.on("LANGUAGE_UPDATED",this.z,this),a&&(a.on("USER_SIGNED_IN",this.A,this),a.on("USER_SIGNED_OUT",this.B,this))),this.f&&(this.f.off("LANGUAGE_UPDATED",this.z),this.f.off("USER_SIGNED_IN",this.A),this.f.off("USER_SIGNED_OUT",this.B)),this.f=a);return this.f!==f},r:function(a){this.e=a;return this.e!==f},t:function(a){this.k=a;return this.k!==f},C:function(a){this.i=a;return this.i!==f},m:function(a){this.a=a;this.d=this.a.getReadyStates();
return this.a!==f},G:function(a,c){this.k?this.k.getTexts(this.N,function(b,k){b?d.util.callback.call(a,c||this,b):(g=k,d.util.callback.call(a,c||this))},c||this):a?d.util.callback.call(a,c||this,new d.pengoError.pengoError.PengoError("WSManager can't update texts because its langMgr is undefined",d.pengoError.codes.codes.NOT_FOUND)):this.c.warn("Manager can't update texts because its langMgr is "+this.k)},start:function(a,c,b){function k(){e.b.off("SERVICE_REGISTERED",k);var a=e.b.getService("uiMainbar")[0];
if(a!==f)e.T=a.addMainbarSection({view:e.q,index:1,align:"right"}),e.b.on("SERVICE_UNREGISTERED",g);else e.b.on("SERVICE_REGISTERED",k)}function g(){e.b.off("SERVICE_UNREGISTERED",g);if(e.b.getService("uiMainbar")[0]===f)e.b.on("SERVICE_REGISTERED",k);else e.b.on("SERVICE_UNREGISTERED",g)}function h(){e.b.off("SERVICE_REGISTERED",h);var a=e.b.getService("game.uiManager")[0];if(a!==f)a.addConnectionView(e.q);else e.b.on("SERVICE_REGISTERED",h)}var e=this;this.D=l;this.G(function(z){z?d.util.callback.call(c,
b||this,z):(e.model||(e.model=new w({_id:"PENGO.client.plugins.netManager.wsManager.WSManager"})),e.h||(e.h=new r({model:e.model,viewsMgr:(new d.bbWrappers.viewsManager.ViewsManager).addCallback(p(this).v)})),e.q||(e.q=new s({model:e.model,viewsMgr:(new d.bbWrappers.viewsManager.ViewsManager).addCallback(p(this).v)})),k(),h(),this.model.on("change:sessionID",this.I,this),e.e.isSignedIn()&&e.model.set({sessionID:e.e.getSessionId()}),this.s(a),d.util.callback.call(c,b||this))},this)},g:function(a){var c=
this;a||(a=this.model.get("sessionID"));this.a?(this.model.set({state:1}),this.a.connect(a,function(b,g){if(b)c.c.warn("Error '"+b+"' while using session to connect"),c.l(a);else switch(c.f.on("CONNECTION_LOST",c.w,c),g){case d.net.constants.results.OK:c.c.info("Successfully connected using session "+c.model.get("sessionID"));c.i.hideModalView(c.h);c.model.set({state:2});c.o=l;break;case d.net.constants.error.codes.SESSION_NOT_VALID:c.c.warn("Session "+c.model.get("sessionID")+" not valid connecting");
c.e.invalidateSession();break;case d.net.constants.error.codes.DUPLICATE_USER_SESSION:c.c.warn("Duplicate user session "+c.model.get("sessionID")+" detected");c.e.signOut();break;default:c.c.warn("Unexpected result"),c.l(a)}})):this.l()},l:function(a){this.D&&(this.j.reconnect!==f?(this.model.set({state:3,ttr:this.j.reconnect}),this.j.hideReconnectDialog!==l&&this.i.showModalView(this.h),this.u(a)):this.model.set({state:0}))},u:function(a){var c=this;this.D&&this.e.isSignedIn()&&3===this.model.get("state")&&
(this.model.set({ttr:this.model.get("ttr")-1}),0>=this.model.get("ttr")?this.g(a):c.n=setTimeout(function(){c.u(a)},1E3))},disconnect:function(a,c,b){this.a.disconnect(c,b)}};return q};var t=["PENGO","client","plugins","netManager","activator"],u=this;!(t[0]in u)&&u.execScript&&u.execScript("var "+t[0]);for(var x;t.length&&(x=t.shift());){var y;if(y=!t.length)y=m;y?u[x]=f:u=u[x]?u[x]:u[x]={}}
(function(){function d(){a.off("SERVICE_REGISTERED",d);k=a.getService("igloo.logger")[0];if(!k||!a.getService("igloo.eventsManager")[0]||!a.getService("igloo.fatal")[0]||!a.getService("accountManager")[0]||!a.getService("languageManager")[0]||!a.getService("net")[0]||!a.getService("uiManager")[0])a.on("SERVICE_REGISTERED",d);else{b||(b=new s(c.templates,c.textsURL));b.K(k);b.r(a.getService("accountManager")[0]);b.t(a.getService("languageManager")[0]);b.C(a.getService("uiManager")[0]);try{b.J(c.config),
b.L(a)}catch(e){a.getService("igloo.fatal")[0].R({Message:e.message,Source:"Setting net view config as "+c.config});return}b.m(a.getService("net")[0]);b.start(a.getService("igloo.eventsManager")[0],function(b){b?a.getService("igloo.fatal")[0].handleFatal({Message:b.message,Source:"Starting plugin '"+a.getPluginId()+"'"}):(v={functions:{},properties:{}},a.register(r,v),a.on("SERVICE_UNREGISTERED",p),a.on("SERVICE_UPDATED",A))},this)}}function q(c){b&&(b.C(f),b.t(f),b.r(f),b.s(f));v&&a.unregister(r,
v);a.off("SERVICE_UNREGISTERED",p);a.off("SERVICE_UPDATED",A);if(c)a.on("SERVICE_REGISTERED",d);else a.off("SERVICE_REGISTERED",d)}function p(c){switch(c){case "igloo.logger":k=a.getService("igloo.logger")[0];b.U(k);return;case "igloo.eventsManager":if(b.s(a.getService("igloo.eventsManager")[0]))return;break;case "accountManager":if(b.r(a.getService("accountManager")[0]))return;break;case "languageManager":if(b.t(a.getService("languageManager")[0]))return;break;case "dashboard.uiManager":if(b.V(a.getService("uiManager")[0]))return;
break;default:return}q(l)}function h(){a.off("SERVICE_REGISTERED",h);if(a.getService("net")[0]==f)a.on("SERVICE_REGISTERED",h);else b!==f&&b.m(a.getService("net")[0])}function g(c){b!==f&&b.m(f);a.off("SERVICE_UNREGISTERED",w);a.off("SERVICE_UPDATED",e);if(c)a.on("SERVICE_REGISTERED",h);else a.off("SERVICE_REGISTERED",h)}function w(c){switch(c){case "net":if(a.getService("net")[0]){b!==f&&b.m(a.getService("net")[0]);return}break;default:return}g(l)}var r="netManager",s,a,c,b,k,v,A=p,e=w;window.PENGO.client.plugins.netManager.activator.activator=
function(b){return{start:function(e,g){a=e;c=g;if(!s){if(!n)throw new b.pengoError.pengoError.PengoError("'PENGO.client.plugins.netManager.wsManager' can't be resolved.",b.pengoError.codes.NOT_FOUND);s=n(b);b.require.remove.deleteByName("PENGO.client.plugins.netManager.wsManager")}d();h()},stop:function(){q(m);g(m)}}}})();})();
